import { useEffect, useRef, useState, type ReactNode } from "react";
import type { PackProofApi } from "../api/client";
import { ApiError } from "../api/types";
import { Brand, Glyph } from "../site/Brand";
import { useTheme } from "../theme/ThemeProvider";
import { randomId } from "../random-id";
import type { Action, AdminIdentity, Detail, Metric, Overview, Scalar, Section, Trend } from "./types";
import "./admin.css";

const NAV=[
  ["overview","Overview","grid"],["users","Users","settings"],["proofs","Proofs","shield"],
  ["evidence","Evidence","film"],["integrations","Integrations","link"],["analytics","Analytics","activity"],
  ["billing","Billing","store"],["infrastructure","Infrastructure","code"],["errors","Errors","alert"],
  ["security","Security","shield"],["system","System","panel"],
] as const;
const PERIODS=[["today","Today"],["7d","7 days"],["30d","30 days"],["90d","90 days"],["1y","1 year"],["all","All time"]];
const TRENDS=[["proofs_created","Proofs created"],["proofs_finalized","Proofs finalized"],["registrations","Registrations"],["evidence_captures","Evidence captures"],["successful_uploads","Committed uploads"],["failed_uploads","Rejected uploads"],["proof_views","Proof views"],["marketplace_imports","Marketplace imports"],["active_users","Active users"],["shared_links","Shared links"],["carrier_events","Carrier events"],["api_requests","API requests"]];
function currentLocation(){return window.location.pathname+window.location.search;}
function message(error:unknown){return error instanceof ApiError&&error.status===403?"Your account does not have administration access.":error instanceof Error?error.message:"This information is temporarily unavailable.";}
function date(value:Scalar){if(!value)return "—";const parsed=new Date(String(value));return Number.isNaN(parsed.getTime())?String(value):parsed.toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"});}
function shortDate(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleDateString(undefined,{month:"short",day:"numeric",timeZone:"UTC"});}
function format(value:number|null|undefined,unit?:string){
  if(value===null||value===undefined)return "—";
  if(unit==="percent")return `${value.toLocaleString(undefined,{maximumFractionDigits:1})}%`;
  if(unit==="bytes"){const n=Math.max(value,0),i=n?Math.min(4,Math.floor(Math.log(n)/Math.log(1024))):0;return `${(n/1024**i).toLocaleString(undefined,{maximumFractionDigits:1})} ${["B","KB","MB","GB","TB"][i]}`;}
  if(unit==="currency")return new Intl.NumberFormat(undefined,{style:"currency",currency:"USD"}).format(value);
  return value.toLocaleString(undefined,{maximumFractionDigits:1})+(unit==="ms"?" ms":"");
}
function safeHref(href:unknown){return typeof href==="string"&&/^\/admin(?:\/|\?|$)/.test(href)&&!href.includes("..")?href:undefined;}
function LocalLink({href,onGo,children,className}:{href:string;onGo:(path:string)=>void;children:ReactNode;className?:string}){
  return <a href={href} className={className} onClick={event=>{if(!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();onGo(href);}}}>{children}</a>;
}
function useRemote<T>(api:PackProofApi,path:string|null,revision=0){
  const [state,setState]=useState<{path:string;api:PackProofApi;data:T|null;error:string|null;loading:boolean}|null>(null);
  useEffect(()=>{let active=true;if(!path)return;
    setState(previous=>({path,api,data:previous?.path===path&&previous.api===api?previous.data:null,error:null,loading:true}));
    void api.adminRequest<T>(path).then(data=>{if(active)setState({path,api,data,error:null,loading:false});}).catch(error=>{if(active)setState({path,api,data:null,error:message(error),loading:false});});
    return()=>{active=false;};
  },[api,path,revision]);
  if(!path)return {data:null,error:null,loading:false};
  return state?.path===path&&state.api===api?state:{data:null,error:null,loading:true};
}
function Loading(){return <div className="admin-skeleton" aria-label="Loading administrative data" role="status"><div/><div/><div/></div>;}
function Unavailable({error,onRetry}:{error:string;onRetry?:()=>void}){return <div className="admin-empty" role="status"><Glyph name="info"/><strong>Information unavailable</strong><p>{error}</p>{onRetry&&<button className="admin-button" onClick={onRetry}>Try again</button>}</div>;}
function Panel({title,aside,children,className=""}:{title:string;aside?:ReactNode;children:ReactNode;className?:string}){return <section className={`admin-panel ${className}`}><header className="admin-panel-header"><h2>{title}</h2>{aside}</header>{children}</section>;}
function MetricCards({metrics,onGo}:{metrics:Metric[];onGo:(path:string)=>void}){
  return <div className="admin-metrics">{metrics.map(metric=>{
    const change=metric.previous!==null&&metric.previous!==0&&metric.value!==null?(metric.value-metric.previous)/Math.abs(metric.previous)*100:null;
    const content=<><span className="admin-metric-label">{metric.label}</span><strong>{format(metric.value,metric.unit)}</strong><span className="admin-metric-comparison">{metric.status!=="available"?"Not currently measured":change!==null?`${change>0?"+":""}${change.toFixed(1)}% vs previous period`:metric.previous===0&&metric.value!==0?"No previous-period baseline":metric.previous!==null?"No change vs previous period":"Current total"}</span>{metric.note&&<span className="admin-metric-note">{metric.note}</span>}</>;
    const href=safeHref(metric.href);return href?<LocalLink key={metric.key} className="admin-metric" href={href} onGo={onGo}>{content}</LocalLink>:<div key={metric.key} className="admin-metric">{content}</div>;
  })}</div>;
}
function TrendChart({api,period,revision,onGo}:{api:PackProofApi;period:string;revision:number;onGo:(path:string)=>void}){
  const [metric,setMetric]=useState("proofs_created"),[compare,setCompare]=useState(true);
  const result=useRemote<Trend>(api,`/analytics/trend?metric=${metric}&period=${period}`,revision);
  const points=result.data?.points??[],max=Math.max(4,Math.ceil(Math.max(0,...points.flatMap(p=>[p.value,compare?p.previous??0:0]))/4)*4);
  const width=760,height=220,left=46,top=16,innerW=694,innerH=166;
  const x=(i:number)=>left+(points.length>1?i/(points.length-1):.5)*innerW;
  const y=(value:number)=>top+innerH-value/max*innerH;
  const path=(previous=false)=>points.map((p,i)=>`${i?"L":"M"}${x(i)},${y(previous?p.previous??0:p.value)}`).join(" ");
  return <Panel title="Platform activity" aside={<select aria-label="Activity metric" value={metric} onChange={event=>setMetric(event.target.value)}>{TRENDS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}>
    <div className="admin-chart-controls"><span>{result.data?.bucketLabel??"Activity totals"} · UTC</span><label><input type="checkbox" checked={compare} onChange={event=>setCompare(event.target.checked)}/> Previous period</label></div>
    {result.loading&&!result.data?<Loading/>:result.error?<Unavailable error={result.error}/>:result.data?.status!=="available"?<Unavailable error={result.data?.note??"This event is not currently measured."}/>:!points.length?<div className="admin-empty">No activity in this period.</div>:<>
      <svg className="admin-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${result.data.label}, ${points.length} intervals. Current total ${points.reduce((n,p)=>n+p.value,0)}.`}>
        {[0,.25,.5,.75,1].map(t=><g key={t}><line x1={left} x2={width-20} y1={y(max*t)} y2={y(max*t)} className="admin-chart-grid"/><text x={left-10} y={y(max*t)+4} textAnchor="end">{format(max*t)}</text></g>)}
        {compare&&<path d={path(true)} className="admin-chart-previous"/>}<path d={path()} className="admin-chart-current"/>
        {points.length===1&&<circle cx={x(0)} cy={y(points[0].value)} r="4" className="admin-chart-dot"/>}
        {points.map((p,i)=><g key={p.date}><rect x={x(i)-Math.max(4,innerW/points.length/2)} width={Math.max(8,innerW/points.length)} y={top} height={innerH} fill="transparent"><title>{shortDate(p.date)}: {format(p.value)}{compare?` · previous ${format(p.previous)}`:""}</title></rect>{(i===0||i===points.length-1||i===Math.floor(points.length/2))&&<text x={x(i)} y={height-13} textAnchor={i===0?"start":i===points.length-1?"end":"middle"}>{shortDate(p.date)}</text>}</g>)}
      </svg><details className="admin-chart-data"><summary>View values by period</summary><table><thead><tr><th>Date</th><th>Current</th>{compare&&<th>Previous</th>}</tr></thead><tbody>{points.map(p=><tr key={p.date}><td><button className="admin-text-button" onClick={()=>onGo(`/admin/${metric==="registrations"?"users":metric.startsWith("evidence")||metric.includes("uploads")?"evidence":"proofs"}?from=${encodeURIComponent(p.date)}&to=${encodeURIComponent(p.endDate??new Date(new Date(p.date).getTime()+86400000).toISOString())}`)}>{shortDate(p.date)}</button></td><td>{format(p.value)}</td>{compare&&<td>{format(p.previous)}</td>}</tr>)}</tbody></table></details>
    </>}{result.data?.note&&<p className="admin-panel-note">{result.data.note}</p>}
  </Panel>;
}
function OverviewScreen({api,period,revision,onGo}:{api:PackProofApi;period:string;revision:number;onGo:(path:string)=>void}){
  const result=useRemote<Overview>(api,`/overview?period=${period}`,revision);
  const [paused,setPaused]=useState(false),[activityFilter,setActivityFilter]=useState("all"),[activity,setActivity]=useState<Overview["activity"]>([]);
  useEffect(()=>{if(!paused&&result.data)setActivity(result.data.activity);},[result.data,paused]);
  if(result.loading&&!result.data)return <Loading/>;
  if(result.error)return <Unavailable error={result.error}/>;
  const data=result.data;if(!data)return null;
  const warning=data.health.some(h=>h.status==="warning"||h.status==="critical"||h.status==="unhealthy"),unknown=data.health.some(h=>h.status==="unavailable");
  const filteredActivity=activity.filter(event=>activityFilter==="all"||event.type.toLowerCase().includes(activityFilter));
  return <><div className="admin-health"><div className="admin-health-summary"><span className={`admin-status-dot ${warning?"warning":unknown?"unknown":"healthy"}`}/><strong>{warning?"Attention required":unknown?"Available checks passing":"All monitored systems operational"}</strong><span>{unknown?"Some checks unavailable":`Updated ${new Date(data.updatedAt).toLocaleTimeString(undefined,{timeZone:"UTC"})}`}</span></div><div className="admin-health-items">{data.health.map(health=><span key={health.key} title={`${health.detail} · ${date(health.checkedAt)}`}><i className={`admin-status-dot ${health.status}`}/>{health.label}<small>{health.status==="unavailable"?"Unknown":""}</small></span>)}</div></div>
    <MetricCards metrics={data.metrics.slice(0,6)} onGo={onGo}/>
    <div className="admin-main-grid"><TrendChart api={api} period={period} revision={revision} onGo={onGo}/><Panel title="Attention required" aside={<span className="admin-count">{data.attention.length}</span>}><div className="admin-alerts">{data.attention.length?data.attention.map(alert=><LocalLink key={alert.id} className={`admin-alert ${alert.severity.toLowerCase()}`} href={safeHref(alert.href)??"/admin/errors"} onGo={onGo}><div><span className="admin-tag">{alert.severity}</span><small>{alert.component}</small></div><strong>{alert.title}</strong><span>{alert.count.toLocaleString()} affected · Latest {date(alert.lastSeen)}</span><small>First observed {date(alert.firstSeen)}</small></LocalLink>):<div className="admin-clear"><Glyph name="check" size={25}/><strong>No observed issues requiring attention</strong><p>Based on the operational data available.</p></div>}</div></Panel></div>
    {data.metrics.length>6&&<MetricCards metrics={data.metrics.slice(6)} onGo={onGo}/>}
    <div className="admin-main-grid"><Panel title="Recent activity" aside={<button className="admin-button small" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?"Resume updates":"Pause updates"}</button>}><div className="admin-toolbar"><select aria-label="Filter activity" value={activityFilter} onChange={e=>setActivityFilter(e.target.value)}><option value="all">All activity</option><option value="proof">Proofs</option><option value="evidence">Evidence</option><option value="user">Accounts</option><option value="admin">Administration</option></select><span>{paused?"Updates paused":"Refreshes every 45 seconds"}</span></div><ol className="admin-activity">{filteredActivity.map(event=><li key={event.id}><span className="admin-event-icon"><Glyph name={event.type.includes("EVIDENCE")?"film":"clock"} size={17}/></span><div><strong>{event.summary}</strong><span>{event.proofId&&<LocalLink href={`/admin/proofs/${encodeURIComponent(event.proofId)}`} onGo={onGo}>Open Proof</LocalLink>}{event.userId&&<LocalLink href={`/admin/users/${encodeURIComponent(event.userId)}`} onGo={onGo}>Open user</LocalLink>}</span></div><time dateTime={event.createdAt}>{date(event.createdAt)}</time></li>)}</ol>{!filteredActivity.length&&<p className="admin-panel-note">No matching activity in the available events.</p>}</Panel>
    <Panel title="Investigate"><div className="admin-quick-links">{[["users","Find an account","Account state, activity and controls"],["proofs","Inspect a Proof","Evidence, hashes and recorded history"],["evidence","Check evidence operations","Committed media and outstanding uploads"],["audit","Review admin actions","Who changed what, when and why"]].map(([key,title,description])=><LocalLink key={key} href={`/admin/${key}`} onGo={onGo}><div><strong>{title}</strong><span>{description}</span></div><Glyph/></LocalLink>)}</div><p className="admin-panel-note">Reporting times use UTC. Each section shows the availability and freshness of its sources.</p></Panel></div>
  </>;
}
function Cell({value,column}:{value:Scalar|undefined;column:string}){if(value===null||value===undefined||value==="")return <span className="admin-muted">—</span>;if(typeof value==="boolean")return <span className="admin-tag">{value?"Yes":"No"}</span>;if(typeof value==="number")return <>{value.toLocaleString()}</>;if(/(?:At|_at|Seen|date)$/i.test(column)&&!Number.isNaN(Date.parse(value)))return <time>{date(value)}</time>;if(/status|state|severity/i.test(column))return <span className={`admin-tag ${/FAIL|ERROR|CRITICAL|DISABLED/i.test(value)?"warning":""}`}>{value.replace(/_/g," ")}</span>;return <span>{value}</span>;}
function DataTable({data,onGo}:{data:Section;onGo:(path:string)=>void}){
  return data.rows.length?<div className="admin-table-wrap" tabIndex={0} role="region" aria-label={data.title}><table className="admin-table"><thead><tr>{data.columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{data.rows.map((row,index)=><tr key={String(row.id??row.userId??row.proofId??index)}>{data.columns.map((column,col)=>{const href=col===0?safeHref(row.href):undefined;return <td key={column.key}>{href?<LocalLink href={href} onGo={onGo}><Cell column={column.key} value={row[column.key]||row.id||row.username}/></LocalLink>:<Cell column={column.key} value={row[column.key]}/>}</td>;})}</tr>)}</tbody></table></div>:<div className="admin-empty"><Glyph name="search"/><strong>No records to display</strong><p>Try a different search or time period.</p></div>;
}
function SectionView({data,onGo}:{data:Section;onGo:(path:string)=>void}){return <><MetricCards metrics={data.metrics??[]} onGo={onGo}/>{data.notices?.map(note=><p className="admin-notice" key={note}><Glyph name="info" size={17}/>{note}</p>)}<Panel title={data.title}>{data.description&&<p className="admin-panel-note">{data.description}</p>}<DataTable data={data} onGo={onGo}/></Panel></>;}
function Explorer({api,section,period,location,revision,onGo,onAction}:{api:PackProofApi;section:string;period:string;location:string;revision:number;onGo:(path:string)=>void;onAction:(action:Action)=>void}){
  const params=new URL(location,window.location.origin).searchParams;
  const [query,setQuery]=useState(params.get("q")??"");
  useEffect(()=>setQuery(new URL(location,window.location.origin).searchParams.get("q")??""),[location]);
  const requestParams=new URLSearchParams(params);requestParams.set("period",period);requestParams.set("pageSize","25");
  const result=useRemote<Section>(api,`/sections/${section}?${requestParams}`,revision);
  const update=(patch:Record<string,string>)=>{const next=new URLSearchParams(params);for(const [key,value]of Object.entries(patch)){if(value)next.set(key,value);else next.delete(key);}onGo(`/admin/${section}?${next}`);};
  return <><form className="admin-toolbar" onSubmit={e=>{e.preventDefault();update({q:query,page:"1"});}}><label className="admin-filter-search"><Glyph name="search" size={18}/><input aria-label={`Search ${section}`} value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${section}…`}/></label><button className="admin-button" type="submit">Search</button><label className="admin-status-filter">Status<input aria-label="Filter by status" placeholder="Any status" defaultValue={params.get("status")??""} key={location} onBlur={e=>{if(e.target.value!==(params.get("status")??""))update({status:e.target.value,page:"1"});}}/></label><select aria-label="Sort records" value={params.get("direction")??"desc"} onChange={e=>update({direction:e.target.value,page:"1"})}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></form>
    {result.loading&&!result.data?<Loading/>:result.error?<Unavailable error={result.error}/>:result.data&&<><SectionView data={result.data} onGo={onGo}/>{result.data.actions?.length?<div className="admin-controls">{result.data.actions.map(action=><button className="admin-button" key={action.id} onClick={()=>onAction(action)}>{action.label}</button>)}</div>:null}{result.data.pagination&&<div className="admin-pagination"><span>{result.data.pagination.total.toLocaleString()} records · Page {result.data.pagination.page}</span><div><button className="admin-button" disabled={result.data.pagination.page<=1} onClick={()=>update({page:String(result.data!.pagination!.page-1)})}>Previous</button><button className="admin-button" disabled={result.data.pagination.page*result.data.pagination.pageSize>=result.data.pagination.total} onClick={()=>update({page:String(result.data!.pagination!.page+1)})}>Next</button></div></div>}<p className="admin-updated">Last updated {date(result.data.updatedAt)}</p></>}
  </>;
}
function DetailView({api,kind,id,revision,onGo,onAction}:{api:PackProofApi;kind:string;id:string;revision:number;onGo:(path:string)=>void;onAction:(action:Action)=>void}){
  const result=useRemote<Detail>(api,`/${kind}/${encodeURIComponent(id)}`,revision);
  const [integrity,setIntegrity]=useState<unknown>(null),[checking,setChecking]=useState(false),[checkError,setCheckError]=useState<string|null>(null),[copied,setCopied]=useState(false);
  useEffect(()=>{setIntegrity(null);setCheckError(null);setCopied(false);},[kind,id]);
  if(result.loading&&!result.data)return <Loading/>;if(result.error)return <Unavailable error={result.error}/>;if(!result.data)return null;
  const data=result.data;
  return <><div className="admin-detail-heading"><div><LocalLink href={`/admin/${kind}`} onGo={onGo}>← Back to {kind}</LocalLink><h2>{data.title}</h2><p>{data.subtitle}</p></div><button className="admin-button" onClick={()=>{void navigator.clipboard.writeText(id).then(()=>setCopied(true)).catch(()=>setCopied(false));}}>{copied?"Copied":"Copy ID"}</button></div><Panel title="Record details"><dl className="admin-fields">{data.fields.map((field,i)=><div key={`${field.label}-${i}`}><dt>{field.label}</dt><dd><Cell value={field.value} column={field.label}/></dd></div>)}</dl></Panel>
    {data.actions?.some(action=>action.method!=="GET")&&<Panel title="Administrative controls"><div className="admin-controls">{data.actions.filter(action=>action.method!=="GET").map(action=><button className="admin-button" key={action.id} onClick={()=>onAction(action)}>{action.label}</button>)}</div><p className="admin-panel-note">Changes require a reason and are recorded in the administrative audit trail.</p></Panel>}
    {kind==="proofs"&&<Panel title="Evidence integrity" aside={<button className="admin-button" disabled={checking} onClick={()=>{setChecking(true);setCheckError(null);void api.adminRequest(`/${kind}/${encodeURIComponent(id)}/integrity`).then(setIntegrity).catch(e=>setCheckError(message(e))).finally(()=>setChecking(false));}}>{checking?"Checking…":"Run integrity check"}</button>}><p className="admin-panel-note">Checks available stored evidence and canonical references. The result states which objects were checked and any limits.</p>{checkError&&<Unavailable error={checkError}/>} {!!integrity&&<TechnicalResult value={integrity}/>}</Panel>}
    {data.sections.map((section,i)=><SectionView key={`${section.title}-${i}`} data={section} onGo={onGo}/>)}
  </>;
}
function TechnicalResult({value}:{value:unknown}){
  const result=value as Record<string,unknown>;
  return <div className="admin-technical"><strong className="admin-tag">{String(result.status??result.result??"Complete")}</strong>{typeof result.summary==="string"&&<p>{result.summary}</p>}<details><summary>Technical details</summary><pre>{JSON.stringify(value,null,2)}</pre></details></div>;
}
function SystemScreen({api,revision,onAction}:{api:PackProofApi;revision:number;onAction:(action:Action)=>void}){
  const result=useRemote<{featureFlags:Array<{key:string;label?:string;description:string;enabled:boolean;version:number;updatedAt:string;actions:Action[]}>;security:{recentAuthenticationRequired:boolean;recentAuthenticationSeconds:number;roleSource:string;mfaPolicy:string};limitations:string[]}>(api,"/system",revision);
  if(result.loading&&!result.data)return <Loading/>;if(result.error)return <Unavailable error={result.error}/>;if(!result.data)return null;
  return <><Panel title="Operational controls"><p className="admin-panel-note">Pause supported entry points while existing records and recovery remain available.</p><div className="admin-system-flags">{result.data.featureFlags.map(flag=><article key={flag.key}><div><h3>{flag.label??flag.key.replace(/_/g," ").toLowerCase()}</h3><p>{flag.description}</p><small>Updated {date(flag.updatedAt)} · Revision {flag.version}</small></div><span className={`admin-tag ${flag.enabled?"warning":""}`}>{flag.enabled?"Paused":"Running"}</span>{flag.actions.map(action=><button className="admin-button" key={action.id} onClick={()=>onAction(action)}>{action.label}</button>)}</article>)}</div></Panel><Panel title="Access and change policy"><dl className="admin-fields"><div><dt>Administrator authorization</dt><dd>Current database role on every request</dd></div><div><dt>Sensitive actions</dt><dd>{result.data.security.recentAuthenticationRequired?`Sign-in within ${Math.floor(result.data.security.recentAuthenticationSeconds/60)} minutes required`:"Development authentication"}</dd></div><div><dt>Evidence</dt><dd>Finalized evidence cannot be edited</dd></div></dl></Panel>{result.data.limitations.map(note=><p className="admin-notice" key={note}><Glyph name="info" size={17}/>{note}</p>)}</>;
}
function ActionDialog({api,action,onClose,onComplete}:{api:PackProofApi;action:Action;onClose:()=>void;onComplete:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),operation=useRef(randomId());
  const [reason,setReason]=useState(""),[confirmation,setConfirmation]=useState(""),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  useEffect(()=>{const element=dialog.current;element?.showModal();return()=>{element?.close();};},[]);
  return <dialog ref={dialog} className="admin-dialog" onCancel={event=>{event.preventDefault();if(!busy)onClose();}} aria-labelledby="admin-action-title"><form onSubmit={e=>{e.preventDefault();if(!safeHref(action.path)||confirmation!==action.confirmation)return;setBusy(true);setError(null);const fields:Record<string,unknown>={};for(const field of action.fields??[])fields[field.key]=field.type==="number"?Number(values[field.key]):values[field.key];void api.adminRequest(action.path.slice(6),"POST",{...action.body,...fields,operationId:operation.current,reason,confirmation}).then(onComplete).catch(e=>setError(message(e))).finally(()=>setBusy(false));}}><header><h2 id="admin-action-title">{action.label}</h2><button aria-label="Close confirmation" type="button" className="admin-icon-button" disabled={busy} onClick={onClose}><Glyph name="close"/></button></header><p>This action changes the selected record. The reason and your administrator identity will be retained in the audit trail.</p>{action.fields?.map(field=><label key={field.key}>{field.label}<input type={field.type==="number"?"number":"text"} step={field.type==="number"?"1":undefined} required={field.required} value={values[field.key]??""} onChange={e=>setValues({...values,[field.key]:e.target.value})}/></label>)}<label>Reason<textarea autoFocus required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><label>Type <code>{action.confirmation}</code> to confirm<input required autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{error&&<p role="alert" className="admin-action-error">{error}</p>}<footer><button className="admin-button" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="admin-button primary" disabled={busy||confirmation!==action.confirmation||reason.trim().length<5||!safeHref(action.path)}>{busy?"Applying…":"Confirm action"}</button></footer></form></dialog>;
}
function GlobalSearch({api,onGo,inputRef}:{api:PackProofApi;onGo:(path:string)=>void;inputRef:React.RefObject<HTMLInputElement|null>}){
  const [query,setQuery]=useState(""),[debounced,setDebounced]=useState(""),[open,setOpen]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>setDebounced(query.trim()),250);return()=>clearTimeout(timer);},[query]);
  const result=useRemote<{results:Array<{kind:string;id:string;title:string;subtitle:string;href:string}>}>(api,debounced.length>=2?`/search?q=${encodeURIComponent(debounced)}`:null);
  return <div className="admin-global-search" onKeyDown={e=>{if(e.key==="Escape"){setOpen(false);inputRef.current?.blur();}}}><Glyph name="search" size={19}/><input ref={inputRef} value={query} onChange={e=>{setQuery(e.target.value);setOpen(true);}} onFocus={()=>setOpen(true)} aria-label="Search users, Proofs, orders and tracking" placeholder="Search users, Proofs, tracking…" aria-expanded={open&&query.length>=2} aria-controls="admin-search-results"/><kbd>⌘ K</kbd>{open&&query.length>=2&&<div id="admin-search-results" className="admin-search-results"><button className="admin-search-close" onClick={()=>setOpen(false)}>Close search</button>{result.loading?<p>Searching…</p>:result.error?<p>{result.error}</p>:result.data?.results.length?result.data.results.map(item=><LocalLink key={`${item.kind}:${item.id}`} href={safeHref(item.href)??"/admin"} onGo={path=>{setOpen(false);setQuery("");onGo(path);}}><span className="admin-tag">{item.kind}</span><div><strong>{item.title}</strong><small>{item.subtitle}</small></div><Glyph size={16}/></LocalLink>):<p>No matching records.</p>}</div>}</div>;
}
export default function AdminWorkspace({api,access,accountName,onGo,onSignOut}:{api:PackProofApi;access:{loading:boolean;allowed:boolean;identity:AdminIdentity|null};accountName:string;onGo:(path:string)=>void;onSignOut:()=>void}){
  const [location,setLocation]=useState(currentLocation),[revision,setRevision]=useState(0),[mobileOpen,setMobileOpen]=useState(false),[action,setAction]=useState<Action|null>(null),[notice,setNotice]=useState<string|null>(null);
  const theme=useTheme(),searchRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{const update=()=>{setLocation(currentLocation());setMobileOpen(false);setNotice(null);};window.addEventListener("popstate",update);window.addEventListener("packproof:navigate",update);return()=>{window.removeEventListener("popstate",update);window.removeEventListener("packproof:navigate",update);};},[]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();searchRef.current?.focus();}if(event.key==="Escape")setMobileOpen(false);};window.addEventListener("keydown",key);const timer=setInterval(()=>{if(document.visibilityState!=="hidden"&&!action)setRevision(n=>n+1);},45000);return()=>{window.removeEventListener("keydown",key);clearInterval(timer);};},[action]);
  const url=new URL(location,window.location.origin),segments=url.pathname.split("/").filter(Boolean),section=segments[1]??"overview",id=segments[2];
  const period=PERIODS.some(([key])=>key===url.searchParams.get("period"))?url.searchParams.get("period")!:"7d";
  const title=section==="audit"?"Administrative audit":NAV.find(([key])=>key===section)?.[1]??"Overview";
  useEffect(()=>{document.title=`${title} — PackProof Admin`;},[title]);
  if(access.loading)return <main className="admin-gate"><Brand/><Loading/></main>;
  if(!access.allowed)return <main className="admin-gate"><Brand/><Glyph name="shield" size={36}/><h1>Administration access unavailable</h1><p>Your account is not authorized, or its access could not be verified.</p><button className="admin-button" onClick={()=>onGo("/proofs")}>Return to your workspace</button></main>;
  const navigate=(path:string)=>{const destination=new URL(path,window.location.origin);if(destination.pathname.startsWith("/admin")&&!destination.searchParams.has("period"))destination.searchParams.set("period",period);onGo(destination.pathname+destination.search);};
  return <div className="admin-shell"><a className="skip-link" href="#admin-content">Skip to content</a><aside className={`admin-sidebar ${mobileOpen?"is-open":""}`}><Brand/><div className="admin-workspace-label"><span>Administration</span><small>System administrator</small></div><nav aria-label="Administration">{NAV.map(([key,label,icon])=><LocalLink key={key} href={key==="overview"?"/admin":`/admin/${key}`} className={section===key||key==="security"&&section==="audit"?"active":""} onGo={navigate}><Glyph name={icon} size={18}/><span>{label}</span></LocalLink>)}</nav><div className="admin-sidebar-bottom"><button onClick={()=>theme.setPreference(theme.scheme==="dark"?"light":"dark")}><Glyph name={theme.scheme==="dark"?"sun":"moon"} size={18}/>{theme.scheme==="dark"?"Light appearance":"Dark appearance"}</button><LocalLink href="/proofs" onGo={onGo}><Glyph name="arrow" size={18}/>Your workspace</LocalLink><details><summary><span className="admin-avatar">{accountName.slice(0,1).toUpperCase()}</span><span>{accountName}</span><Glyph name="chevron" size={16}/></summary><button onClick={onSignOut}>Sign out</button></details></div></aside>
    {mobileOpen&&<button className="admin-mobile-backdrop" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>}
    <div className="admin-body"><header className="admin-topbar"><button className="admin-icon-button admin-menu" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle administration navigation" aria-expanded={mobileOpen}><Glyph name="menu"/></button><span className="admin-breadcrumb">Admin <span>/</span> {title}</span><GlobalSearch api={api} onGo={navigate} inputRef={searchRef}/><span className="admin-environment">{access.identity?.environment??"Connected environment"}</span></header>
    <main id="admin-content" className="admin-content"><div className="admin-page-heading"><div><p className="admin-eyebrow">PACKPROOF / OPERATIONS</p><h1>{id?"Record inspection":title}</h1><p>{section==="overview"?"Platform activity, service health, and what needs your attention.":section==="users"?"Accounts, activity and administrative controls.":section==="proofs"?"Platform-wide records and their evidence history.":section==="analytics"?"Acquisition, product usage and returning creators.":"Inspect the source data and act where controls are available."}</p></div><div className="admin-heading-controls"><select aria-label="Reporting period" value={period} onChange={e=>{url.searchParams.set("period",e.target.value);url.searchParams.delete("page");navigate(url.pathname+url.search);}}>{PERIODS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className="admin-button" onClick={()=>setRevision(n=>n+1)}><Glyph name="activity" size={16}/>Refresh</button></div></div>
    {notice&&<div className="admin-notice" role="status"><Glyph name="check"/>{notice}</div>}
    {section==="security"||section==="audit"?<nav className="admin-tabs" aria-label="Security views"><LocalLink href="/admin/security" onGo={navigate} className={section==="security"?"active":""}>Security events</LocalLink><LocalLink href="/admin/audit" onGo={navigate} className={section==="audit"?"active":""}>Admin audit trail</LocalLink></nav>:null}
    {section==="analytics"?<nav className="admin-tabs" aria-label="Analytics views">{[["product","Product funnel"],["usage","Usage"],["acquisition","Website activity"],["cohorts","Retention cohorts"],["versions","Client versions"]].map(([view,label])=><LocalLink key={view} href={`/admin/analytics?view=${view}`} onGo={navigate} className={(url.searchParams.get("view")??"product")===view?"active":""}>{label}</LocalLink>)}</nav>:null}
    {section==="integrations"&&!id?<nav className="admin-tabs" aria-label="Integration views">{[["connections","Connections"],["webhooks","Webhook deliveries"]].map(([view,label])=><LocalLink key={view} href={`/admin/integrations?view=${view}`} onGo={navigate} className={(url.searchParams.get("view")??"connections")===view?"active":""}>{label}</LocalLink>)}</nav>:null}
    {section==="overview"?<OverviewScreen api={api} period={period} revision={revision} onGo={navigate}/>:section==="system"?<SystemScreen api={api} revision={revision} onAction={setAction}/>:id&&(section==="users"||section==="proofs"||section==="integrations"||section==="evidence"||section==="webhooks"||section==="errors")?<DetailView key={`${section}:${id}`} api={api} kind={section} id={decodeURIComponent(id)} revision={revision} onGo={navigate} onAction={setAction}/>:<Explorer api={api} section={section} period={period} location={location} revision={revision} onGo={navigate} onAction={setAction}/>}
    </main><footer className="admin-footer"><span>PackProof administration</span><span>Evidence stays immutable. Administrative changes are audited.</span></footer></div>
    {action&&<ActionDialog api={api} action={action} onClose={()=>setAction(null)} onComplete={()=>{setAction(null);setNotice("Action completed and recorded in the audit trail.");setRevision(n=>n+1);}}/>}
  </div>;
}
