#!/usr/bin/env node
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {generateKeyPairSync,randomBytes} from 'node:crypto';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {ClosedFmp4Stream,FragmentJournal,FRAGMENT_PROFILE,verifyFragmentManifest,nativeFragmentCapability} from '../../packages/evidence-contracts/fragments.mjs';
export async function captureSoftwareFragments({seconds=3,realTime=true}={}){
 const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),started=process.hrtime.bigint();
 const journal=new FragmentJournal({profile:FRAGMENT_PROFILE,proofId:'proof_software_fixture',captureSessionId:'cap_software_fixture',nonceDigest:randomBytes(32).toString('hex'),audioRequired:true,startedMonotonicNs:String(started)}),parser=new ClosedFmp4Stream();
 const args=['-hide_banner','-loglevel','error',...(realTime?['-re']:[]),'-f','lavfi','-i','testsrc2=size=320x240:rate=15','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t',String(seconds),'-map','0:v:0','-map','1:a:0','-c:v','libx264','-preset','ultrafast','-tune','zerolatency','-pix_fmt','yuv420p','-g','15','-keyint_min','15','-sc_threshold','0','-c:a','aac','-b:a','64k','-movflags','empty_moov+default_base_moof+frag_keyframe','-frag_duration','1000000','-f','mp4','pipe:1'];
 const processChild=spawn('ffmpeg',args,{stdio:['ignore','pipe','pipe']});let stderr='',appendTimeNs=0n,firstMediaAtNs=null,producerExitedAtNs=null,peakPendingBytes=0;const units=[];
 processChild.once('exit',()=>{producerExitedAtNs=process.hrtime.bigint();});
 processChild.stderr.on('data',chunk=>{stderr+=chunk.toString();if(stderr.length>16384)processChild.kill('SIGKILL');});
 const exit=new Promise((resolve,reject)=>{processChild.once('error',reject);processChild.once('close',code=>code===0?resolve():reject(Error(`FFMPEG_FAILED: ${stderr}`)));});
 try{for await(const chunk of processChild.stdout){const closed=parser.push(chunk);peakPendingBytes=Math.max(peakPendingBytes,parser.pending.length);for(const unit of closed){const now=process.hrtime.bigint();if(unit.kind==='MEDIA'&&firstMediaAtNs===null)firstMediaAtNs=now;const before=process.hrtime.bigint();journal.append({...unit,closedMonotonicNs:String(now)});appendTimeNs+=process.hrtime.bigint()-before;units.push(unit.bytes);}}
  await exit;parser.finish();
 }catch(error){processChild.kill('SIGKILL');await exit.catch(()=>{});throw error;}
 const ended=process.hrtime.bigint(),sealed=journal.seal(pair.privateKey),publicKeyPem=pair.publicKey.export({format:'pem',type:'spki'}).toString(),verification=verifyFragmentManifest(sealed,units,publicKeyPem);
 return {sealed,units,publicKeyPem,verification,report:{schemaVersion:'packproof.fragment-spike-report.v1',fixture:'SYNTHETIC_TEST_PATTERN_AND_SINE',producer:'LOCAL_FFMPEG_STREAMING_FMP4_STDOUT',profile:FRAGMENT_PROFILE,syntheticDurationSeconds:seconds,realTimePacing:realTime,mediaDeliveredBeforeProducerExit:firstMediaAtNs!==null&&producerExitedAtNs!==null&&firstMediaAtNs<producerExitedAtNs,firstMediaArrivalMs:Number((firstMediaAtNs??ended)-started)/1e6,producerWallMs:Number(ended-started)/1e6,journalHashParseMs:Number(appendTimeNs)/1e6,peakUnclosedChunkBytes:peakPendingBytes,totalEncodedBytes:units.reduce((n,b)=>n+b.length,0),unitCount:units.length,tracks:journal.tracks,verification,nativeProfiles:[nativeFragmentCapability('android'),nativeFragmentCapability('ios')],qualification:'SOFTWARE_PROTOCOL_ONLY',limitations:['Synthetic local encoder benchmark is not a mobile capture benchmark.','No finalized-file splitting is represented as incremental capture.','No sensor attestation, physical scene or safe native fragment timing is inferred.','AAC/video decode ranges are encoded timeline positions, not wall clock or sensor exposure time.','Native interruption/thermal/resource overhead remains unmeasured on devices.']}};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const output=path.resolve(process.argv[2]??'/tmp/packproof-fragment-spike');await mkdir(output,{recursive:true});const result=await captureSoftwareFragments();await writeFile(path.join(output,'manifest.json'),JSON.stringify(result.sealed,null,2));await writeFile(path.join(output,'public-key.pem'),result.publicKeyPem);await writeFile(path.join(output,'encoded-stream.mp4'),Buffer.concat(result.units));for(let index=0;index<result.units.length;index++)await writeFile(path.join(output,`unit-${index}.bin`),result.units[index]);await writeFile(path.join(output,'report.json'),JSON.stringify(result.report,null,2));console.log(JSON.stringify(result.report,null,2));}
