import {useEffect,useState} from 'react';
import type {PackProofApi} from '../api/client';
import {FEATURE_LABELS,type Feature} from '../../../packages/evidence-contracts/contracts.mjs';
import './rnd.css';
interface Metrics {witness?:{health:string;sampledCompleted:number;latestCheckpoints:Array<{analysisId:string;policyId:string;logId:string;checkpointAgeMs:number;treeSize:number;controlledSignatureCount:number;independentOperatorCount:number;assurance:string}>;attentionErrorsLast24Hours:Array<{code:string;jobs:number;stage:string}>;limitations:string[]};asOf:string;killSwitch:boolean;rows:Array<{feature:Feature;operational_state:string;jobs:number;attempts:number;expired_leases:number;average_completion_ms:number|null;oldest_age_ms:number}>;errors:Array<{feature:Feature;error_code:string;count:number}>;limitations:string[];}
/** Mounted only inside the existing administrator gate in an isolated research build. */
export function RndOperations({api,revision}:{api:PackProofApi;revision:number}) {
 const [data,setData]=useState<Metrics|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[analysisId,setAnalysisId]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let current=true;setData(null);setError('');void api.adminRequest<Metrics>('/rnd/metrics').then(value=>{if(current)setData(value);}).catch(e=>{if(current)setError(e instanceof Error?e.message:'Research operations unavailable.');});return()=>{current=false;};},[api,revision,refresh]);
 const alerts=data?.rows.flatMap(row=>[...(row.expired_leases?[`${FEATURE_LABELS[row.feature]} has ${row.expired_leases} expired worker lease(s).`]:[]),...(['QUEUED','RUNNING'].includes(row.operational_state)&&row.oldest_age_ms>600000?[`${FEATURE_LABELS[row.feature]} has work older than the 10-minute local queue threshold.`]:[])])??[];
 return <section className="rnd-panel" aria-label="Research operations">
  <div className="rnd-heading"><h2>Research operations</h2><button disabled={busy} onClick={()=>setRefresh(value=>value+1)}>Refresh research metrics</button></div>
  <p>Current cumulative research counters. Alert policy: expired leases and queued/running jobs older than ten minutes. These local alerts do not send messages.</p>
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {!data&&!error&&<p role="status">Loading research metrics…</p>}
  {data&&<><p>Global kill switch: <strong>{data.killSwitch?'closed — optional work disabled':'open — per-feature controls apply'}</strong>. Snapshot: {data.asOf}.</p>
   {alerts.length>0?<ul role="alert">{alerts.map((alert,index)=><li key={index}>{alert}</li>)}</ul>:<p>No configured local queue alert is active in this snapshot.</p>}
   <div className="rnd-table-scroll"><table><caption>Durable analysis queue</caption><thead><tr><th>Feature</th><th>State</th><th>Jobs</th><th>Attempts</th><th>Mean completion</th><th>Oldest job age</th><th>Expired leases</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.feature+row.operational_state}><th scope="row">{FEATURE_LABELS[row.feature]}</th><td>{row.operational_state}</td><td>{row.jobs}</td><td>{row.attempts}</td><td>{row.average_completion_ms===null?'Not measured':`${(row.average_completion_ms/1000).toFixed(2)} s`}</td><td>{(row.oldest_age_ms/60000).toFixed(1)} min</td><td>{row.expired_leases}</td></tr>)}</tbody></table></div>
   {data.errors.length>0&&<div className="rnd-table-scroll"><table><caption>Recorded operational errors</caption><thead><tr><th>Feature</th><th>Code</th><th>Count</th></tr></thead><tbody>{data.errors.map(row=><tr key={row.feature+row.error_code}><td>{FEATURE_LABELS[row.feature]}</td><td>{row.error_code}</td><td>{row.count}</td></tr>)}</tbody></table></div>}
   {data.witness&&<div><h3>Witness publication diagnostics</h3><p>{data.witness.health} · {data.witness.sampledCompleted} sampled completed receipts.</p><div className="rnd-table-scroll"><table><caption>Recent controlled witness checkpoints</caption><thead><tr><th>Policy and log</th><th>Age</th><th>Tree size</th><th>Controlled signatures</th><th>Independent operators</th><th>Assurance</th></tr></thead><tbody>{data.witness.latestCheckpoints.map(row=><tr key={row.analysisId}><td>{row.policyId} · {row.logId}</td><td>{(row.checkpointAgeMs/60000).toFixed(1)} min</td><td>{row.treeSize}</td><td>{row.controlledSignatureCount}</td><td>{row.independentOperatorCount}</td><td>{row.assurance}</td></tr>)}</tbody></table></div>{data.witness.attentionErrorsLast24Hours.map((row,index)=><p role="alert" key={index}>{row.stage} · {row.code} · {row.jobs} job(s) in the past day</p>)}{data.witness.limitations.map((limit,index)=><p className="rnd-limits" key={index}>{limit}</p>)}</div>}
   <p>Per-feature runtime and memory are retained in signed analysis details and benchmark reports. Attributable hosted unit cost, physical coverage and device overhead have not been measured. Local witness signatures represent controlled test operators; independent operator count remains zero.</p>
   <details><summary>Retry a terminal analysis failure</summary><p>A retry creates a new audited record, rechecks source access and consent, and preserves the failed attempt. Scene challenges require a new capture.</p><label>Failed analysis ID <input value={analysisId} maxLength={128} onChange={e=>setAnalysisId(e.target.value)}/></label><label>Retry reason <textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!/^rnd_analysis_[a-zA-Z0-9_-]+$/.test(analysisId)||reason.trim().length<3} onClick={()=>{setBusy(true);setError('');setNotice('');void api.rndRetry(analysisId,reason,crypto.randomUUID()).then(()=>{setNotice('A separate research retry was queued and audited.');setRefresh(value=>value+1);}).catch(e=>setError(e instanceof Error?e.message:'Retry unavailable.')).finally(()=>setBusy(false));}}>Queue an audited retry</button></details>
   {data.limitations.map((limit,index)=><p className="rnd-limits" key={index}>{limit}</p>)}
  </>}
 </section>;
}
