import {useMemo} from 'react';
import type {PackProofApi} from '../api/client';
import type {RndTransport} from './types';
import {RndReview} from './RndReview';
function saveBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function RndWebPanel({proofId,api,loadEvidence}:{proofId:string;api:PackProofApi;loadEvidence?:((id:string)=>Promise<Blob>)}) {
 const transport=useMemo<RndTransport>(()=>({grants:(id,analysis)=>api.rndGrants(id,analysis),createGrant:(id,analysis,input,key)=>api.rndCreateGrant(id,analysis,input,key),revokeGrant:(id,grant)=>api.rndRevokeGrant(id,grant),annotations:id=>api.rndAnnotations(id),annotate:(id,input,key)=>api.rndAnnotate(id,input,key),capabilities:()=>api.rndCapabilities(),list:id=>api.rndAnalyses(id),consent:(id,granted,key)=>api.rndWrite(id,'consents',{purpose:'EXPERIMENTAL_ANALYSIS',version:'packproof.research-consent.v1',granted},key),request:(id,input,key)=>api.rndRequest(id,input,key),export:(id,key)=>api.rndWrite(id,'exports',{},key),derivative:(id,input,key)=>api.rndWrite(id,'derivatives',input,key),artifact:async(id,analysisId,index)=>{const blob=await api.rndArtifact(id,analysisId,index);return {url:URL.createObjectURL(blob),mimeType:blob.type};},review:(id,analysisId,input,key)=>api.rndReview(id,analysisId,input,key),exportArchive:async(id,analysis)=>{const blob=await api.rndArchive(id,analysis);saveBlob(blob,`PackProof-${analysis?'Redacted':'Research'}-${id}.zip`);}}),[api]);
 if(import.meta.env.VITE_PACKPROOF_RND!=='1')return null;
 return <RndReview proofId={proofId} transport={transport} openSource={async(id,legId)=>{if(legId&&legId!=='OUTBOUND'){const blob=await api.featureDownload(proofId,`lifecycle/stages/${encodeURIComponent(legId)}/evidence/${encodeURIComponent(id)}`);return {url:URL.createObjectURL(blob),mimeType:blob.type};}if(!loadEvidence)throw new Error('Original media access is unavailable.');const blob=await loadEvidence(id);return {url:URL.createObjectURL(blob),mimeType:blob.type};}} saveExport={async bundle=>{const blob=new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`PackProof-RnD-${proofId}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}/>;
}
