version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      backend-minor-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      web-minor-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      mobile-minor-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
