import { installNavigationContext } from "../navigation-context";
import { SampleProof } from "./SampleProof";
import { ProofDiagram, type ProofDiagramKind } from "./ProofDiagram";



import { lazy, Suspense, useEffect, useState, type FormEvent, type ReactNode } from "react";
const App = lazy(() => import("../App").then(module => ({ default: module.App })));
import { loadSession } from "../auth/session";
import { legalDocumentByKind } from "../legal/documents";

import { Brand, Glyph } from "./Brand";
export { Brand, Glyph } from "./Brand";

function SiteHeader({ dark = false }: { dark?: boolean }) {
  const [open, setOpen] = useState(false);
  const signedIn = Boolean(loadSession());
  const features = [
    { title: "Your workspace", description: "Every Proof, beautifully organized.", href: "/app", icon: "grid" },
    { title: "Packing evidence", description: "The item, the packing, the final seal.", href: "/how-it-works", icon: "film" },
    { title: "Shipment timeline", description: "Follow the story of a Proof.", href: "/sample#tracking", icon: "pin" },
    { title: "Connected stores", description: "Bring your orders into the workflow.", href: "/stores", icon: "store" },
  ];
  return <header className={`site-header ${dark ? "header-dark" : ""}`} onKeyDown={event => { if (event.key === "Escape") { setOpen(false); event.currentTarget.querySelectorAll("details[open]").forEach(d => d.removeAttribute("open")); } }}>
    <div className="site-nav"><Brand dark={dark} />
      <nav id="public-navigation" className={open ? "public-nav is-open" : "public-nav"} aria-label="Main navigation">
        <details className="feature-menu"><summary>Product <Glyph name="chevron" size={14} /></summary>
          <div className="feature-menu-panel"><div className="feature-menu-grid">{features.map(feature => <a href={feature.href} key={feature.title}><span className="menu-feature-icon"><Glyph name={feature.icon} /></span><span><strong>{feature.title}</strong><small>{feature.description}</small></span></a>)}</div><a className="feature-menu-footer" href="/sample"><span><span className="status-dot" /> Take a look inside PackProof</span><Glyph size={17} /></a></div>
        </details>
        <a href="/how-it-works">How it works</a><a href="/about">About us</a><a href="/contact">Contact</a>
        <a className="mobile-nav-login" href={signedIn ? "/app" : "/login"}>{signedIn ? "My workspace" : "Log in"} <Glyph size={16} /></a>
      </nav>
      <div className="nav-actions"><a className="nav-login" href={signedIn ? "/app" : "/login"}>{signedIn ? "My workspace" : "Log in"}</a><a className="site-button small blue" href={signedIn ? "/new" : "/signup"}>Get started <Glyph size={16} /></a><button className="mobile-menu" aria-label={open ? "Close navigation" : "Open navigation"} aria-controls="public-navigation" aria-expanded={open} onClick={() => setOpen(!open)}><Glyph name={open ? "close" : "menu"} /></button></div>
    </div>
  </header>;
}

function Footer() {
  return <footer className="site-footer"><div className="footer-main"><div><Brand /><p>A clearer record.<br />From the first scan to the final seal.</p></div><div><span className="footer-label">PRODUCT</span><a href="/how-it-works">How it works</a><a href="/sample">Explore the app</a><a href="/proof-anywhere">Check an exported Proof</a><a href="/app">Your workspace</a></div><div><span className="footer-label">COMPANY</span><a href="/about">About PackProof</a><a href="/contact">Get in touch</a><a href="/login">Log in</a></div><div className="footer-signoff"><span className="status-dot" /> Built for the moments<br />that matter.</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} PackProof</span><div><a href="/privacy">Privacy policy</a><a href="/terms">Terms of service</a></div><span>Every package has a story.</span></div></footer>;
}

function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <p className={`site-eyebrow ${light ? "light" : ""}`}><span />{children}</p>; }
function CTA() { return <section className="closing-cta site-width"><div><Eyebrow light>YOUR NEXT SHIPMENT, DOCUMENTED.</Eyebrow><h2>Good packing deserves<br />a great record.</h2></div><div><a className="site-button blue" href="/signup">Create your first Proof <Glyph /></a><p>One order. One record. All in one place.</p></div></section>; }

const stepDiagrams: ProofDiagramKind[] = ["order", "capture", "share"];
const steps = [
  { title: "Start with the order.", body: "Add the transaction details or bring in an order from a connected store. Everything begins with one shared record.", icon: "box" },
  { title: "Capture the details.", body: "Record the item, the packing process, and the seal. Keep the evidence connected to the right shipment.", icon: "film" },
  { title: "Keep the whole story.", body: "Finalize your Proof, review its timeline, and share a read-only record when someone needs the details.", icon: "shield" },
];

export function SampleRecord({ large = false }: { large?: boolean }) { return <SampleProof compact={!large}/>; }

function Landing() {
  return <><main id="main-content"><div className="dark-intro"><SiteHeader dark /><section className="hero site-width"><div className="hero-copy"><Eyebrow light>EVIDENCE FOR EVERY SHIPMENT</Eyebrow><h1>Every package.<br />A clearer <span>record.</span></h1><p>What you packed. How you packed it. All in one Proof. Bring the details together before your shipment leaves your hands.</p><div className="hero-actions"><a className="site-button blue" href="/signup">Start your first Proof <Glyph /></a><a className="text-link light" href="/sample">Play a sample Proof <span>↗</span></a></div><div className="hero-note"><span className="status-dot" /> Your evidence. Connected to your order.</div></div><div className="hero-visual"><SampleRecord /></div></section><div className="hero-bottom site-width"><span>MADE FOR THE HANDOFF</span><div><Glyph name="box" size={17} /> Independent sellers</div><div><Glyph name="store" size={17} /> Growing stores</div><div><Glyph name="shield" size={17} /> Careful collectors</div><a href="#how-it-works">Discover PackProof <span>↓</span></a></div></div>
    <section className="section-space site-width" id="how-it-works"><div className="section-heading"><div><Eyebrow>LESS GUESSWORK. MORE CONTEXT.</Eyebrow><h2>From your packing table.<br />To a record you can share.</h2></div><p>The details that matter shouldn’t be scattered across your camera roll, inbox, and order history.</p></div><div className="steps-grid">{steps.map((s,i) => <article className="step-card" key={s.title}><div className="step-top"><span>0{i+1}</span></div><ProofDiagram kind={stepDiagrams[i]} /><h3>{s.title}</h3><p>{s.body}</p></article>)}</div></section>
    <section className="product-section"><div className="site-width product-grid"><div><Eyebrow>THE WHOLE PICTURE, IN ONE PLACE</Eyebrow><h2>Your evidence.<br />Without the<br /><span className="muted-heading">loose ends.</span></h2><p>Open any Proof and follow the story: the order, the evidence, and what happened along the way.</p><a href="/sample" className="text-link">Explore a sample Proof <Glyph size={18} /></a><div className="feature-points"><span><Glyph name="check" /> Order-linked evidence</span><span><Glyph name="check" /> A chronological activity record</span><span><Glyph name="check" /> Read-only sharing when you need it</span></div></div><SampleRecord /></div></section>
    <section className="section-space site-width"><div className="section-heading"><div><Eyebrow>BUILT AROUND YOUR WORKFLOW</Eyebrow><h2>A little more clarity.<br />At every handoff.</h2></div><a className="text-link" href="/how-it-works">See how it works <Glyph size={18} /></a></div><div className="bento-grid"><article className="bento-wide"><div className="bento-orbit"><Glyph name="box" size={60} /><span>ORDER</span><span>EVIDENCE</span><span>PROOF</span></div><div><span className="micro-label">STAY ORGANIZED</span><h3>One order. One source of context.</h3><p>Bring your transactions and packing evidence into a focused workspace. Find the right Proof without digging.</p></div></article><article className="bento-small"><ProofDiagram kind="share" /><h3>Ready to review.<br />Easy to share.</h3><p>Create a read-only link to the record you choose to share. Keep the conversation grounded in the details.</p><a className="text-link" href="/sample">See the record <Glyph size={17} /></a></article></div></section>
    <section className="problem-scale"><div className="site-width"><Eyebrow light>WHY THE RECORD MATTERS</Eyebrow><h2>Returns are large. The details still matter one shipment at a time.</h2><p className="problem-intro">When a shipment is questioned, assembling scattered evidence takes time. PackProof keeps the order, original recording, and source of each event together.</p><div className="problem-statistics"><article><strong>$849.9 billion</strong><p>Projected US retail merchandise returns in 2025. This is returned merchandise value, not fraud losses.</p><a href="https://nrf.com/media-center/press-releases/consumers-expected-to-return-nearly-850-billion-in-merchandise-in-2025" target="_blank" rel="noreferrer">NRF / Happy Returns · October 15, 2025 ↗</a></article><article><strong>$42 billion</strong><p>Forecast global merchant chargeback costs in 2028. This is a forecast, not an observed current loss.</p><a href="https://www.mastercard.com/us/en/news-and-trends/press/2025/june/first-party-trust-countering-friendly-fraud.html" target="_blank" rel="noreferrer">Mastercard · June 25, 2025 ↗</a></article></div><p className="problem-caveat">Different markets and measures; these figures should not be added together. They do not measure PackProof’s addressable market, preventable losses, or effectiveness.</p></div></section>
    <section className="section-space site-width"><Eyebrow>ONE RECORD, DIFFERENT QUESTIONS</Eyebrow><h2>Find the view you need.</h2><div className="trust-details"><article><ProofDiagram kind="capture" /><h3>For sellers</h3><p>Connect an available store, enable automatic eligible-order intake, and record from the packing queue.</p><a className="text-link" href="/stores">Open Connections →</a></article><article><ProofDiagram kind="share" /><h3>For buyers</h3><p>Review the seller’s selected record without an account. Sign in only to add a verified receipt or return recording.</p><a className="text-link" href="/sample?view=receipt">See a buyer receipt →</a></article><article><ProofDiagram kind="review" /><h3>For reviewers and platforms</h3><p>Follow source-linked chapters, inspect stated gaps, and review a selected case packet or portable archive.</p><a className="text-link" href="/sample?view=case">Explore a case preview →</a></article></div></section>
    <section className="section-space site-width"><Eyebrow>KNOW WHAT YOU ARE SHARING</Eyebrow><h2>Preserved originals. Deliberate sharing.</h2><div className="trust-details"><article><span className="feature-icon"><Glyph name="link" size={26} /></span><h3>Choose the recipient view</h3><p>Review fields and media before making a link. Redacted copies stay separate from originals. Links can expire or be revoked; a downloaded copy cannot be recalled.</p></article><article><span className="feature-icon"><Glyph name="info" size={26} /></span><h3>Understand the limits</h3><p>A preserved record shows what was recorded and reported. It cannot establish events outside the camera, authenticate an item, or guarantee a dispute outcome.</p></article><article><span className="feature-icon"><Glyph name="clock" size={26} /></span><h3>Plan your use</h3><p>Public pricing and a contractual retention period are not published yet. Contact us before relying on a paid rollout or a fixed storage commitment.</p><a href="/contact">Discuss your workflow →</a></article></div><p><a href="/privacy">Privacy and data handling</a> · <a href="/terms">Service terms</a></p></section>
    <FAQ /><CTA /></main><Footer /></>;
}

const questions = [
  ["What is a Proof?", "A Proof is a record connected to a transaction. It brings together order details, captured evidence, statements, and a timeline. Once finalized, its recorded evidence is preserved as part of that Proof."],
  ["Who is PackProof for?", "PackProof is built for people who want a clearer record of what they ship: independent sellers, online stores, collectors, and fulfillment teams."],
  ["Does the recipient need an account?", "A recipient does not have to join for you to create a Proof. You can share a read-only public link when you want someone to review a record."],
  ["Does a Proof guarantee a dispute outcome?", "No. PackProof organizes and preserves evidence. It does not decide disputes, guarantee an outcome, or independently verify everything that happened in the physical world."],
  ["Can I use it without connecting a store?", "Yes. You can add transaction details manually and create a Proof. Connected-store options are also available in the workspace, depending on the provider’s availability."],
];
function FAQ() { return <section className="faq-section site-width"><div><Eyebrow>A FEW GOOD QUESTIONS</Eyebrow><h2>Clear from<br />the start.</h2><a href="/contact" className="text-link">Ask us something <Glyph size={18} /></a></div><div>{questions.map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>; }

function About() { return <><section className="page-intro site-width"><Eyebrow>ABOUT PACKPROOF</Eyebrow><h1>Care goes into every package.<br /><span>Keep a record of it.</span></h1><p>PackProof exists to make the moments before a shipment easier to document, easier to find, and easier to understand.</p></section><section className="about-story site-width"><img src="/packproof-hero.png" alt="A shipment carefully sealed and ready for its next handoff" width="1536" height="1024" /><div><Eyebrow>WHY WE’RE BUILDING THIS</Eyebrow><h2>The handoff deserves<br />more clarity.</h2><p>You know the care that went into your packing. But once the box leaves, a scattered collection of photos and messages can make that story hard to tell.</p><p>We’re bringing those details into one transaction-linked record. A shared place for the order, the evidence, and the timeline—so there’s more context when it matters.</p><a className="text-link" href="/contact">Talk to the team <Glyph size={18} /></a></div></section><section className="section-space site-width"><Eyebrow>WHAT GUIDES THE PRODUCT</Eyebrow><div className="steps-grid">{[["Clarity over claims.", "We preserve the record and make it understandable. Evidence should inform a conversation, without pretending to decide it."], ["Connected from the start.", "Each Proof begins with a transaction. Its evidence and timeline stay together as the record develops."], ["Your work, respected.", "Thoughtful packing takes effort. Keeping a useful record of that effort should fit naturally into your workflow."]].map(([title,body],i) => <article className="step-card" key={title}><span className="micro-label">0{i+1}</span><ProofDiagram kind={(["review", "order", "capture"] as const)[i]} /><h3>{title}</h3><p>{body}</p></article>)}</div></section><CTA /></>; }

function HowItWorks() { return <><section className="page-intro site-width"><Eyebrow>HOW PACKPROOF WORKS</Eyebrow><h1>Pack with care.<br /><span>Leave a clear record.</span></h1><p>A simple workflow that connects your order, your evidence, and every important step along the way.</p><a href="/signup" className="site-button navy">Create your first Proof <Glyph /></a></section><section className="workflow site-width">{steps.map((s,i) => <article key={s.title}><span className="workflow-number">0{i+1}</span><div><h2>{s.title}</h2><p>{s.body}</p><ul>{(i === 0 ? ["Add the item and transaction details", "Import an available store order or enter it yourself", "Keep one Proof tied to the transaction"] : i === 1 ? ["Show the item’s condition", "Document packing and the final seal", "Review the evidence before finalizing"] : ["Preserve the completed record", "Review the chronological activity", "Share a read-only link or export the record"]).map(t => <li key={t}><Glyph name="check" size={17} />{t}</li>)}</ul></div><ProofDiagram kind={stepDiagrams[i]} /></article>)}</section><FAQ /><CTA /></>; }

function ProofAnywhere(){return <section className="page-intro site-width"><Eyebrow>PROOF ANYWHERE</Eyebrow><h1>Keep the record.<br/><span>Check it independently.</span></h1><p>Download a Proof as an ordinary ZIP from your workspace. A separately distributed verifier checks included files and signed snapshots without signing in or uploading your evidence.</p><div className="trust-details"><article><ProofDiagram kind="export" /><h3>1 · Export your record</h3><p>Open your Proof and choose its package export. The archive lists included, omitted and unavailable files. A scoped recipient export contains only that recipient’s selected view.</p><a href="/proofs">Open your Proofs →</a></article><article><ProofDiagram kind="integrity" /><h3>2 · Get the independent verifier</h3><p>The open-source verifier runs locally with Python 3.10 or later. Signature checking also needs OpenSSL. Download it separately from your evidence package.</p><a href="https://github.com/thepackproof/packproof-v2/tree/main/verifier" target="_blank" rel="noreferrer">Verifier, public format and test vectors ↗</a></article><article><ProofDiagram kind="review" /><h3>3 · Review the result</h3><p>Verified, unsigned, changed, missing, unknown key, stale trust and revoked key are separate outcomes. An optional static HTML report makes the inventory and limitations readable offline.</p><a href="/api/.well-known/packproof-trust.json" target="_blank" rel="noreferrer">Current public signing-key trust list ↗</a></article></div><p className="note">Obtain the verifier and trust list through trusted channels, separately from the archive. Included keys are never automatically trusted. Verification confirms the checked digital records; it does not authenticate an item or prove events outside the camera. Old unsigned records remain labeled unsigned, and an offline check cannot know about a newer revocation until its trust list is refreshed.</p><a className="site-button navy" href="/sample?view=case">Explore the sample record <Glyph/></a></section>;}

function Contact() {
  const [prepared,setPrepared] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const topic = String(data.get("topic")); const body = `Name: ${data.get("name")}\nEmail: ${data.get("email")}\n\n${data.get("message")}`; window.location.href = `mailto:nericollin@thepackproof.com?subject=${encodeURIComponent(`PackProof — ${topic}`)}&body=${encodeURIComponent(body)}`; setPrepared(true); }
  return <section className="contact-grid site-width page-intro"><div><Eyebrow>GET IN TOUCH</Eyebrow><h1>Let’s talk<br /><span>PackProof.</span></h1><p>A question, an idea, or a workflow you’d like to improve? We’d like to hear it.</p><a className="contact-email" href="mailto:nericollin@thepackproof.com"><Glyph name="mail" />nericollin@thepackproof.com</a><div className="contact-note"><span className="status-dot" /><p>Product questions, partnerships,<br />and thoughtful feedback welcome.</p></div></div><form className="contact-form" onSubmit={submit}><h2>What’s on your mind?</h2><div className="form-pair"><label>Your name<input name="name" autoComplete="name" placeholder="Alex Morgan" required maxLength={120} /></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="alex@company.com" required maxLength={254} /></label></div><label>How can we help?<select name="topic"><option>Product question</option><option>Account support</option><option>Partnership</option><option>Feedback</option></select></label><label>Your message<textarea name="message" placeholder="Tell us a little about what you have in mind…" required rows={5} maxLength={4000} /></label><button className="site-button navy" type="submit">Open email draft <Glyph /></button><p className="form-explanation" role="status">{prepared ? "Your email draft is ready in your email app. Review it and press Send there. If it did not open, use the email address on this page." : "Opens your email app with a prepared message. Nothing is sent until you choose to send it."}</p></form></section>;
}

function Legal({ kind }: { kind: "privacy" | "terms" }) { const doc = legalDocumentByKind(kind); return <section className="public-legal site-width"><div className="page-intro"><Eyebrow>THE DETAILS</Eyebrow><h1>{doc.title}</h1><p>{doc.description}</p><span className="legal-date">Last updated {doc.lastUpdated}</span><p className="legal-draft">Draft for review. Company details and legal contact information still need to be confirmed before public launch.</p></div><div className="legal-layout"><nav aria-label="On this page"><span className="micro-label">ON THIS PAGE</span>{doc.sections.map(s => <a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</nav><article>{doc.sections.map(s => <section id={s.id} key={s.id}><h2>{s.title}</h2>{s.paragraphs.map(p => <p key={p}>{p}</p>)}{s.bullets && <ul>{s.bullets.map(p => <li key={p}>{p}</li>)}</ul>}{s.closingParagraphs?.map(p => <p key={p}>{p}</p>)}</section>)}</article></div></section>; }

function Demo() { return <><section className="page-intro site-width sample-intro"><Eyebrow>INTERACTIVE SAMPLE · NO CUSTOMER DATA</Eyebrow><h1>Open the record.<br/><span>Go straight to the evidence.</span></h1><p>Play an illustrative packing clip, jump to a source moment, inspect the timeline, and review a sample buyer receipt or case packet.</p></section><section className="demo-stage site-width"><div className="demo-sidebar"><Brand/><span className="micro-label">SAMPLE PROOF</span><p>Fictional order #1042<br/>One ceramic mug</p><p>No real delivery, customer, or PackProof capture is represented.</p><a className="site-button navy small" href="/signup">Create a real Proof <Glyph size={16}/></a></div><div className="demo-main"><SampleRecord large/><p className="demo-caption">This uses the same evidence player, timeline and tracking components as the workspace. Sample actions stay within this fictional record.</p></div></section><CTA/></>; }

export function AuthFrame({ children }: { children: ReactNode }) { return <div className="auth-experience"><div className="auth-story"><Brand dark /><div><Eyebrow light>WELCOME TO YOUR WORKSPACE</Eyebrow><h2>Every detail.<br />In good hands.</h2><p>A place for your orders, your evidence,<br />and a clearer record of every shipment.</p></div><img src="/packproof-hero.png" alt="Carefully sealed package" width="1536" height="1024" /><span className="auth-caption"><span className="status-dot" /> From packed to preserved.</span></div><div className="auth-form-panel"><a className="auth-back" href="/">← Back to PackProof</a>{children}<div className="auth-assistance">Need a hand? <a href="/contact">Get in touch</a></div></div></div>; }

function currentPath() { return window.location.pathname.replace(/\/$/, "") || "/"; }
export function Website() {
  const [path,setPath] = useState(currentPath);
  useEffect(installNavigationContext, []);
  useEffect(() => { const update = () => { setPath(currentPath()); }; window.addEventListener("popstate",update); window.addEventListener("packproof:navigate",update); return () => { window.removeEventListener("popstate",update); window.removeEventListener("packproof:navigate",update); }; },[]);
  useEffect(() => { const titles: Record<string,string> = {"/":"Every package. A clearer record.","/about":"About us","/how-it-works":"How it works","/sample":"Explore the app","/contact":"Contact us","/login":"Log in","/signup":"Create an account","/app":"Your workspace","/privacy":"Privacy policy","/terms":"Terms of service"}; document.title = `${titles[path] ?? "Your workspace"} — PackProof`; },[path]);
  const publicPaths = ["/", "/about", "/how-it-works", "/sample", "/contact", "/proof-anywhere", "/privacy", "/terms", "/new/privacy", "/new/terms"];
  if (!publicPaths.includes(path) && /^\/(app|login|signup|proofs|new|scan|activity|account|developer|receipt|invitations|fulfillment|station|stores|p)(\/|$)/.test(path)) return <Suspense fallback={<main className="app-loading" role="status"><Brand /><p>Opening PackProof…</p></main>}><App authInitialView={path === "/signup" ? "create-account" : "sign-in"} /></Suspense>;
  return <div className="public-site"><a className="skip-link" href="#main-content">Skip to content</a>{path === "/" ? <Landing /> : <><SiteHeader /><main id="main-content">{path === "/about" ? <About /> : path === "/how-it-works" ? <HowItWorks /> : path === "/sample" ? <Demo /> : path === "/contact" ? <Contact /> : path === "/proof-anywhere" ? <ProofAnywhere/> : ["/privacy","/new/privacy","/terms","/new/terms"].includes(path) ? <Legal kind={path.endsWith("privacy") ? "privacy" : "terms"} /> : <section className="page-intro site-width"><Eyebrow>PAGE NOT FOUND</Eyebrow><h1>This one’s<br />off the route.</h1><p>Let’s get you back to a clearer path.</p><a href="/" className="site-button navy">Back to PackProof <Glyph /></a></section>}</main><Footer /></>}</div>;
}
