import {build as bundle} from 'esbuild';
import {build as vite} from 'vite';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
process.chdir(root);
await mkdir('dist/main',{recursive:true});
const marker=JSON.parse(await readFile(path.join(root,'../config/rnd/research-build.json'),'utf8'));
const research=marker.researchOnly===true;
const channel=process.env.APP_ENV??'development';
if(research && channel!=='development')throw new Error('Experimental source cannot create a distribution build.');
if(research){process.env.VITE_PACKPROOF_RND='1';for(const key of ['PACKPROOF_COGNITO_CLIENT_ID','PACKPROOF_COGNITO_USER_POOL_ID','PACKPROOF_UPDATES_URL','PACKPROOF_SENTRY_DSN','SENTRY_DSN'])if(process.env[key])throw new Error('Research build cannot inherit remote identity, updates or telemetry.');}
if(!['development','staging','production'].includes(channel))throw new Error('APP_ENV must be development, staging or production');
const config={channel,research,apiBaseUrl:process.env.PACKPROOF_API_BASE_URL??(research?'http://127.0.0.1:3000':''),webBaseUrl:process.env.PACKPROOF_WEB_BASE_URL??(research?'http://127.0.0.1:5173':'https://thepackproof.com'),cognito:{region:process.env.PACKPROOF_COGNITO_REGION??'us-east-1',clientId:process.env.PACKPROOF_COGNITO_CLIENT_ID??'',userPoolId:process.env.PACKPROOF_COGNITO_USER_POOL_ID??''},updateUrl:process.env.PACKPROOF_UPDATES_URL??'',sentryDsn:process.env.PACKPROOF_SENTRY_DSN??process.env.SENTRY_DSN??''};
if(channel!=='development'&&(!config.apiBaseUrl||!config.cognito.clientId||!config.cognito.userPoolId))throw new Error('Signed builds require explicit API and Cognito configuration.');
if(research && ![config.apiBaseUrl,config.webBaseUrl].every(value=>['localhost','127.0.0.1','[::1]'].includes(new URL(value).hostname)))throw new Error('Research endpoints must be loopback.');
await writeFile('dist/main/runtime-config.json',JSON.stringify(config,null,2));
for(const name of ['index','preload'])await bundle({entryPoints:[`src/main/${name}.ts`],outfile:`dist/main/${name}.cjs`,bundle:true,platform:'node',target:'node24',format:'cjs',external:['electron','electron-updater','@sentry/node'],sourcemap:false});
await vite({configFile:path.join(root,'vite.config.ts')});
