import {afterAll,beforeAll,describe,expect,it,vi} from 'vitest';
import request from 'supertest';
import {createHarness,createUser,auth,type TestHarness} from './helpers.js';
import {submitIntakeObservation} from '../src/intake/context.js';
import {readFile} from 'node:fs/promises';
import {generateKeyPairSync,sign} from 'node:crypto';
import {initializeEvidenceUpload,commitEvidence} from '../src/domain/evidence.js';
import {commitAttestation} from '../src/domain/attestations.js';
import {finalizeProof} from '../src/domain/finalize.js';
import {previewDisclosure,createDisclosureGrant} from '../src/domain/disclosure.js';
import {getPublicProof} from '../src/domain/public-proof.js';
import {sha256Hex} from '../src/hash.js';
import {createCaptureSession,completeCaptureSession} from '../src/domain/capture-sessions.js';
import {appendIdentifierObservations,getIdentifierReview,checkpointIdentifiers,decideIdentifier,ensureIdentifierBarrier,identifierCandidates,identifierProjection,sealedIdentifiers} from '../src/identifiers/service.js';
import {indexIdentifierItems} from '../src/identifiers/catalog.js';
import {attestationContext} from '../src/domain/attestation-context.js';
import {buildProofRecoverySnapshot} from '../src/domain/recovery-journal.js';
import type {IdentifierObservation} from '../src/identifiers/types.js';
let h:TestHarness,seller:string,other:string;const tenant='storefront:shopify:identifier-shop';let n=0;
const connection='identifier-real-shop';
async function order(sku='sku-A.01',gtin='036000291452',store=connection,account='identifier-shop') {
 const id=`order-${++n}`;
 const result=await submitIntakeObservation(h.db,h.clock,seller,{receiptId:id,sourceKind:'API_OBSERVED',adapterKey:'shopify',adapterVersion:'test-real-data-boundary',externalOrderId:id,orderReference:id,items:[{title:`Item ${sku}`,quantity:1,sku,gtin,variant:'Blue'}],physicalFulfillment:true,paid:true,cancelled:false,fulfillmentScope:'FULL_ORDER'}, {provider:'shopify',externalAccountReference:account,namespaceSource:'STOREFRONT_API',connectionId:store,verified:true});
 return {proofId:result.proofId!,snapshotId:result.snapshot!.id,transactionId:result.transactionId!};
}
function event(sessionId:string,rawText:string,sequence=1,symbology='ean13'):IdentifierObservation {return {schemaVersion:1,clientEventId:`event-${sequence}`,captureSessionId:sessionId,sequence,rawText,rawBytes:null,decoderEncoding:null,symbology,symbologyIdentifier:null,source:'LIVE_CAMERA_ANALYSIS',mediaTimeMs:1200,timestampOrigin:'MONOTONIC_APPROXIMATE',timestampUncertaintyMs:150,recordingRef:sessionId,adapterVersion:'adapter/1',decoderVersion:'decoder/1',capabilityProfile:'test',frameWidth:1080,frameHeight:1920,coordinateSpace:'FRAME_PIXELS',bounds:null,firstSeenMs:1200,lastSeenMs:1200,sightings:1};}
async function capture(o:Awaited<ReturnType<typeof order>>) {return createCaptureSession(h.db,h.clock,seller,o.proofId,{client:'NATIVE_CAMERA',idempotencyKey:`capture-${++n}`});}
beforeAll(async()=>{h=await createHarness();seller=await createUser(h);other=await createUser(h);await h.db.query(`INSERT INTO integration_connections(id,owner_user_id,adapter_key,provider,external_account_reference,credential_reference,status,created_at,updated_at) VALUES($1,$2,'shopify','shopify','identifier-shop','not-a-real-credential','ACTIVE',now(),now())`,[connection,seller]);vi.stubEnv('IDENTIFIER_CAPTURE_ENABLED','true');vi.stubEnv('IDENTIFIER_AUTOFILL_ENABLED','true');vi.stubEnv('IDENTIFIER_REVIEW_ENABLED','true');vi.stubEnv('IDENTIFIER_TENANTS',tenant);vi.stubEnv('IDENTIFIER_SURFACES','ANDROID,WEB');},30000);
afterAll(async()=>{vi.unstubAllEnvs();await h?.close();});
describe('scoped optional identifier enrichment',()=>{
 it('pins default-off behavior, eligibility and replayed session policy',async()=>{const o=await order();vi.stubEnv('IDENTIFIER_CAPTURE_ENABLED','false');const off=await capture(o);expect(off.identifierPolicy?.captureEnabled).toBe(false);await expect(appendIdentifierObservations(h.db,h.clock,seller,o.proofId,off.id,{events:[event(off.id,'036000291452')]})).rejects.toMatchObject({code:'IDENTIFIER_DISABLED'});vi.stubEnv('IDENTIFIER_CAPTURE_ENABLED','true');expect((await getIdentifierReview(h.db,seller,o.proofId,off.id)).enabled).toBe(false);});
 it('resolves real source title, routes product plus label independently, and never creates carrier jobs',async()=>{const o=await order(),s=await capture(o);const r=await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'0036000291452'),event(s.id,'1Z999AA10123456784',2,'code128')]});expect(r.observations.map(o=>[o.route,o.state])).toEqual([['PRODUCT','MATCH'],['SHIPPING','UNKNOWN']]);expect(r.observations[0].product?.title).toBe('Item sku-A.01');expect((await h.db.query('SELECT * FROM capture_shipment_jobs WHERE transaction_id=$1',[o.transactionId])).rows).toHaveLength(0);});
 it('rejects cross-account scope, sequence collision and changed replay while preserving original result',async()=>{const o=await order(),s=await capture(o),e=event(s.id,'0036000291452');const first=await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[e]});const second=await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[e]});expect(second).toEqual(first);await expect(appendIdentifierObservations(h.db,h.clock,other,o.proofId,s.id,{events:[e]})).rejects.toMatchObject({httpStatus:403});await expect(appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[{...e,rawText:'96385074'}]})).rejects.toMatchObject({code:'IDENTIFIER_EVENT_CONFLICT'});await expect(appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[{...e,clientEventId:'different'}]})).rejects.toMatchObject({code:'IDENTIFIER_SEQUENCE_CONFLICT'});});
 it('preserves exact SKU punctuation and case and handles SKU/tracking overlap conservatively',async()=>{const o=await order('1Z999AA10123456784','96385074'),s=await capture(o);const r=await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'1Z999AA10123456784',1,'code128'),event(s.id,'sku-A.01',2,'code128'),event(s.id,'SKU-A.01',3,'code128')]});expect(r.observations[0].route).toBe('AMBIGUOUS');expect(r.observations[1].identifiers[0]).toMatchObject({type:'SKU',value:'sku-A.01'});expect(r.observations[2].state).toBe('UNKNOWN');});
 it('same item in two orders remains explicit candidates without any new Proof or binding',async()=>{await order('candidate-item','4006381333931');await order('candidate-item','4006381333931');const before=await h.db.query('SELECT count(*) FROM proofs');const r=await identifierCandidates(h.db,seller,{integrationAccountId:connection,rawText:'4006381333931',symbology:'ean13'});expect(r.products).toHaveLength(1);expect(r.orders).toHaveLength(2);expect((await h.db.query('SELECT count(*) FROM proofs')).rows).toEqual(before.rows);await expect(identifierCandidates(h.db,other,{integrationAccountId:connection,rawText:'4006381333931',symbology:'ean13'})).rejects.toMatchObject({code:'IDENTIFIER_SOURCE_FORBIDDEN'});});
 it('material mismatch requires attributed review; stale decisions and checkpoint gaps cannot bypass it',async()=>{const o=await order(),s=await capture(o);let r=await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'4006381333931')]});expect(r.reviewRequired).toBe(true);const cp={clientEventId:'cp',revision:r.revision,lastSequence:1,coverage:'UNAVAILABLE',omittedEvents:0};await expect(checkpointIdentifiers(h.db,h.clock,seller,o.proofId,s.id,cp)).rejects.toMatchObject({code:'IDENTIFIER_REVIEW_REQUIRED'});await expect(ensureIdentifierBarrier(h.db,h.clock,o.proofId,s.id)).rejects.toMatchObject({code:'IDENTIFIER_REVIEW_REQUIRED'});const decision={clientEventId:'decision',observationId:r.observations[0].observationId,revision:0,decision:'NOT_THIS_SHIPMENT',reason:'A different product remained on the bench.'};await expect(decideIdentifier(h.db,h.clock,seller,o.proofId,s.id,decision)).rejects.toMatchObject({code:'IDENTIFIER_REVIEW_STALE'});r=await decideIdentifier(h.db,h.clock,seller,o.proofId,s.id,{...decision,revision:r.revision});expect(r.reviewRequired).toBe(false);r=await checkpointIdentifiers(h.db,h.clock,seller,o.proofId,s.id,{...cp,revision:r.revision,coverage:'COMPLETE'});expect(r.checkpoint).not.toBeNull();expect(r.observations[0].state).toBe('CONFLICT');expect(r.observations[0].decision?.actorId).toBe(seller);});
 it('optional outage preserves a stable partial checkpoint and new events are supplemental without changing authorized digest',async()=>{const o=await order(),s=await capture(o);await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'0036000291452',2)]});const before=await attestationContext(h.db,o.transactionId);await h.db.transaction(tx=>ensureIdentifierBarrier(tx,h.clock,o.proofId,s.id));const after=await attestationContext(h.db,o.transactionId);expect(before.contextSha256).not.toBe(after.contextSha256);const r=await getIdentifierReview(h.db,seller,o.proofId,s.id);expect(r.coverage).toBe('PARTIAL');await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'4006381333931',3)]});expect((await attestationContext(h.db,o.transactionId)).contextSha256).toBe(after.contextSha256);expect((await getIdentifierReview(h.db,seller,o.proofId,s.id)).observations[1].supplemental).toBe(true);expect((await sealedIdentifiers(h.db,o.proofId))?.checkpoints[0].observations).toHaveLength(1);const recovery=await buildProofRecoverySnapshot(h.db,o.proofId) as {rows:Record<string,unknown[]>};expect(recovery.rows.capture_identifier_checkpoints).toHaveLength(1);expect(recovery.rows.intake_order_snapshots).toHaveLength(1);expect(recovery.rows.intake_source_observations).toHaveLength(1);});
 it('drops unrelated QR payloads before persistence and rejects oversized input',async()=>{const o=await order(),s=await capture(o);await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'WIFI:S:private-network;P:secret-password;;',1,'qr')]});const serialized=JSON.stringify((await h.db.query('SELECT observation_json,resolution_json FROM capture_identifier_observations WHERE session_id=$1',[s.id])).rows);expect(serialized).not.toContain('secret-password');expect(serialized).not.toContain('private-network');await expect(appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'x'.repeat(4097),2,'qr')]})).rejects.toMatchObject({code:'IDENTIFIER_OBSERVATION_INVALID'});expect((await identifierProjection(h.db,o.proofId))?.observations[0].observation.rawText).toBe('');});
 it('keeps other stores isolated and shows disconnected sources honestly',async()=>{const store='other-store';await h.db.query(`INSERT INTO integration_connections(id,owner_user_id,adapter_key,provider,external_account_reference,credential_reference,status,created_at,updated_at) VALUES($1,$2,'shopify','shopify','other-shop','not-a-real-credential','ACTIVE',now(),now())`,[store,seller]);await order('store-only','5901234123457',store,'other-shop');const o=await order(),s=await capture(o);expect((await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'5901234123457')]})).observations[0].state).toBe('UNKNOWN');await h.db.query("UPDATE integration_connections SET status='DISABLED' WHERE id=$1",[store]);expect((await identifierCandidates(h.db,seller,{integrationAccountId:store,rawText:'5901234123457',symbology:'ean13'})).state).toBe('FORBIDDEN');});
 it('exposes optional HTTP capability and enforces authenticated candidate scope',async()=>{const caps=await request(h.app).get('/capabilities');expect(caps.body.identifiers).toMatchObject({schemaVersions:[1],productionQualified:false,paidLookupCalls:0});const r=await request(h.app).post('/me/intake/identifier-candidates').set(auth(seller)).send({integrationAccountId:connection,rawText:'4006381333931',symbology:'ean13'});expect(r.status).toBe(200);expect(r.body.orders.length).toBeGreaterThanOrEqual(2);});
 it('seals finalized bytes once, appends a signed late interpretation and requires explicit identifier disclosure consent',async()=>{
  const o=await order(),s=await capture(o);await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'0036000291452')]});
  const media=await readFile(new URL('./fixtures/camera-recording.mp4',import.meta.url));
  await completeCaptureSession(h.db,h.clock,seller,o.proofId,s.id,{sha256:sha256Hex(media),byteSize:media.length,contentType:'video/mp4'});
  const upload=await initializeEvidenceUpload(h.db,h.clock,h.objectStore,seller,o.proofId,{contentType:'video/mp4',evidenceType:'FULFILLMENT_CAPTURE',captureSessionId:s.id,idempotencyKey:'final-video'});
  await h.objectStore.put(upload.objectKey,media,'video/mp4');await commitEvidence(h.db,h.clock,h.objectStore,seller,o.proofId,upload.evidenceId);
  await commitAttestation(h.db,h.clock,seller,o.proofId,{statement:'PACKED_DESCRIBED_ITEM',relatedEvidenceId:upload.evidenceId});
  const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'});const signer={async signManifest(input:{canonicalJson:string}){return {algorithm:'ECDSA_SHA_256' as const,keyId:'fixture-signing-key',signatureBase64:sign('sha256',Buffer.from(input.canonicalJson),pair.privateKey).toString('base64'),signedAt:h.clock.now().toISOString()};}};
  const sealed=await finalizeProof(h.db,h.clock,seller,o.proofId,signer);
  const legacy=await previewDisclosure(h.db,seller,o.proofId,{purpose:'SHARED_PROOF'});expect(legacy.identifiers).toBeUndefined();
  const optedIn=await previewDisclosure(h.db,seller,o.proofId,{purpose:'SHARED_PROOF',itemIdentifiersReviewed:true});expect(optedIn.identifiers?.observations[0].evidenceId).toBe(upload.evidenceId);expect(optedIn.identifiers?.observations[0].identifiers[0].type).toBe('GTIN');expect(optedIn.identifiers?.observations[0].observation.rawText).toBe('');
  const grant=await createDisclosureGrant(h.db,h.clock,seller,o.proofId,{purpose:'SHARED_PROOF',itemIdentifiersReviewed:true,originalsReviewed:true,previewHash:optedIn.disclosure.viewHash,publicWebBaseUrl:'https://example.test'});expect((await getPublicProof(h.db,h.clock,grant.token!)).identifiers?.observations).toHaveLength(1);
  const later=await appendIdentifierObservations(h.db,h.clock,seller,o.proofId,s.id,{events:[event(s.id,'4006381333931',2)]},signer);expect(later.observations[1].supplemental).toBe(true);
  expect((await h.db.query('SELECT * FROM proof_supplements WHERE proof_id=$1',[o.proofId])).rows).toHaveLength(1);
  expect((await finalizeProof(h.db,h.clock,seller,o.proofId,signer)).manifest.canonicalJson).toBe(sealed.manifest.canonicalJson);
  await expect(h.db.query('UPDATE capture_identifier_observations SET supplemental=false WHERE session_id=$1',[s.id])).rejects.toThrow('IDENTIFIER_EVIDENCE_IMMUTABLE');
  await expect(h.db.query("UPDATE capture_sessions SET identifier_policy=NULL WHERE id=$1",[s.id])).rejects.toThrow('IDENTIFIER_POLICY_IMMUTABLE');
 },20000);
 it('uses the scoped index at 10,000 rows and measures bounded warm lookup',async()=>{await h.db.query(`INSERT INTO identifier_aliases(id,owner_user_id,tenant_key,connection_id,identifier_type,normalized_value,source_ref,source_revision,product_key,product_json,observed_at) SELECT 'bench-'||i,$1,$2,$3,'SKU','bench-sku-'||i,'bench-source-'||i,'fixture-revision','bench-product-'||i,'{"title":"Isolated benchmark fixture","variant":null,"sku":null,"gtin":null,"imageUrl":null,"externalItemId":null}'::jsonb,now() FROM generate_series(1,10000) i`,[seller,tenant,connection]);await h.db.query('ANALYZE identifier_aliases');const plan=await h.db.query('EXPLAIN SELECT * FROM identifier_aliases WHERE owner_user_id=$1 AND tenant_key=$2 AND connection_id=$3 AND identifier_type=$4 AND normalized_value=$5',[seller,tenant,connection,'SKU','bench-sku-9999']);expect(JSON.stringify(plan.rows)).toContain('identifier_alias_lookup');const samples:number[]=[];for(let i=0;i<30;i++){const start=performance.now();await h.db.query('SELECT * FROM identifier_aliases WHERE owner_user_id=$1 AND tenant_key=$2 AND connection_id=$3 AND identifier_type=$4 AND normalized_value=$5',[seller,tenant,connection,'SKU','bench-sku-9999']);samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);console.info(`Identifier index: 10,000 rows; 30 warm lookups; p95 ${samples[28].toFixed(2)} ms (PGlite test harness, not production)`);expect(samples[28]).toBeLessThan(150);},20000);
});
