import { createHmac } from 'node:crypto';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { StripeBillingAdapter,stripeBillingConfigFromEnv,verifyStripeSignature,type StripeBillingConfig } from '../src/billing/stripe-adapter.js';
import { bindBillingCustomer,ingestVerifiedBillingEvent } from '../src/billing/usage-ledger.js';
import { createPgliteDatabase } from '../src/db/pglite.js';
import { migrate } from '../src/db/migrate.js';
import type { Database } from '../src/db/database.js';
const now=new Date('2026-09-07T12:00:00Z'),clock={now:()=>new Date(now)},ts=Math.floor(now.getTime()/1000);
const secret=['whsec','syntheticfixtureonly0000000000'].join('_');
const config:StripeBillingConfig={account:'acct_fixture',environment:'sandbox',apiVersion:'2026-08-27.dahlia',accountMode:'direct',credentialReference:'sm:packproof/test-only/stripe'};
const credentials={getCredentials:async()=>({adapterKey:'stripe-billing',credentialReference:config.credentialReference,material:{apiKey:['rk','test','syntheticfixtureonly0000000'].join('_'),webhookSecret:secret}})};
const payment={id:'pi_payment',object:'payment_intent',livemode:false,status:'succeeded',currency:'usd',customer:'cus_buyer',amount_received:2900,latest_charge:'ch_payment'};
const refund={id:'re_partial',object:'refund',status:'succeeded',currency:'usd',amount:500,payment_intent:'pi_payment',charge:'ch_payment',balance_transaction:'txn_refund'};
function event(isRefund=false,overrides:Record<string,unknown>={}){return{id:isRefund?'evt_refund':'evt_payment',object:'event',api_version:config.apiVersion,livemode:false,created:ts-5,type:isRefund?'refund.updated':'payment_intent.succeeded',data:{object:isRefund?refund:payment},...overrides};}
function signed(value:unknown,time=ts){const rawBody=Buffer.from(JSON.stringify(value));return{rawBody,signature:`t=${time},v1=${createHmac('sha256',secret).update(`${time}.`).update(rawBody).digest('hex')}`};}
function fixture(overrides:Record<string,unknown>={}){
 const calls:Array<{url:string;init?:RequestInit}>=[];
 const values:Record<string,unknown>={'/v1/account':{id:'acct_fixture',object:'account'},'/v1/payment_intents/pi_payment':payment,'/v1/refunds/re_partial':refund,
 '/v1/charges/ch_payment':{id:'ch_payment',object:'charge',status:'succeeded',paid:true,livemode:false,customer:'cus_buyer',payment_intent:'pi_payment',currency:'usd',balance_transaction:'txn_payment'},
 '/v1/balance_transactions/txn_payment':{id:'txn_payment',object:'balance_transaction',amount:2900,currency:'usd',source:'ch_payment',created:ts-100},
 '/v1/balance_transactions/txn_refund':{id:'txn_refund',object:'balance_transaction',amount:-500,currency:'usd',source:'re_partial',created:ts-30},
 '/v1/invoices':{object:'list',has_more:false,data:[{id:'in_fixture',object:'invoice',livemode:false,customer:'cus_buyer',currency:'usd',status:'paid',amount_due:2900,amount_paid:2900,created:ts-100,email:'private@example.test'}]},
 '/v1/subscriptions/sub_fixture':{id:'sub_fixture',object:'subscription',customer:'cus_buyer',livemode:false},
 '/v1/billing_portal/sessions':{id:'bps_fixture',object:'billing_portal.session',customer:'cus_buyer',url:'https://billing.stripe.com/p/session/synthetic'},...overrides};
 const fetcher=(async(url:URL|RequestInfo,init?:RequestInit)=>{calls.push({url:String(url),init});const u=new URL(String(url));expect(u.origin).toBe('https://api.stripe.com');return new Response(JSON.stringify(values[u.pathname]??{}),{status:values[u.pathname]?200:404,headers:{'Content-Type':'application/json'}});}) as typeof fetch;
 return{calls,adapter:new StripeBillingAdapter(config,credentials,clock,fetcher),fetcher};
}
let db:Database,close:()=>Promise<void>;
beforeAll(async()=>{const x=await createPgliteDatabase();db=x.db;close=x.close;await migrate(db);for(const id of ['stripe-user','stripe-other'])await db.query('INSERT INTO users(id,created_at,updated_at) VALUES($1,$2,$2)',[id,now.toISOString()]);await bindBillingCustomer(db,clock,{provider:'stripe',environment:'sandbox',providerAccount:'acct_fixture',customerReference:'cus_buyer',userId:'stripe-user'});},30000);
afterAll(async()=>{await close();});
describe('optional Stripe accounting boundary',()=>{
 it('disables absent provider and refuses partial or unmanaged configuration',()=>{expect(stripeBillingConfigFromEnv({})).toBeNull();expect(()=>stripeBillingConfigFromEnv({PACKPROOF_BILLING_PROVIDER:'stripe'})).toThrow();expect(()=>new StripeBillingAdapter({...config,credentialReference:'env:SECRET'},credentials,clock)).toThrow('managed');});
 it('validates original bytes, rotation signatures and fresh timestamps before network',async()=>{const input=signed(event()),f=fixture();expect(()=>verifyStripeSignature(input.rawBody,`${input.signature},v1=${'0'.repeat(64)}`,secret,clock)).not.toThrow();await expect(f.adapter.verifyAndNormalize({...input,rawBody:Buffer.concat([input.rawBody,Buffer.from(' ')])})).rejects.toMatchObject({code:'STRIPE_SIGNATURE_INVALID'});for(const d of [-301,301])await expect(f.adapter.verifyAndNormalize(signed(event(),ts+d))).rejects.toMatchObject({code:'STRIPE_SIGNATURE_EXPIRED'});await expect(f.adapter.verifyAndNormalize({...input,signature:`t=${ts},${input.signature}`})).rejects.toThrow();expect(f.calls).toHaveLength(0);});
 it('refuses other environment, version, account, status and currency before financial reads',async()=>{for(const e of [event(false,{livemode:true}),event(false,{api_version:'2025-01-01'}),event(false,{account:'acct_other'}),event(false,{context:'acct_other'}),event(true,{data:{object:{...refund,status:'pending'}}}),event(false,{data:{object:{...payment,currency:'eur'}}})]){const f=fixture();await expect(f.adapter.verifyAndNormalize(signed(e))).rejects.toThrow();expect(f.calls).toHaveLength(0);}});
 it('uses authenticated account and balance booking time rather than notification time',async()=>{const f=fixture(),r=await f.adapter.verifyAndNormalize(signed(event()));expect(r).toEqual({eventReference:'evt_payment',customerReference:'cus_buyer',subjectReference:'pi_payment',paymentReference:'pi_payment',kind:'payment_settled',occurredAt:new Date((ts-100)*1000).toISOString(),amountMinor:2900,currency:'USD'});expect(f.calls.every(c=>c.init?.method==='GET')).toBe(true);await expect(fixture({'/v1/account':{object:'account',id:'acct_other'}}).adapter.verifyAndNormalize(signed(event()))).rejects.toMatchObject({code:'STRIPE_ACCOUNT_MISMATCH'});await expect(fixture({'/v1/balance_transactions/txn_payment':{id:'txn_payment',object:'balance_transaction',amount:2900,currency:'usd',source:'ch_other',created:ts-100}}).adapter.verifyAndNormalize(signed(event()))).rejects.toMatchObject({code:'STRIPE_BALANCE_MISMATCH'});});
 it('persists repeated payment and succeeded partial-refund notifications only once',async()=>{const f=fixture();await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event()));expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event()))).toMatchObject({replayed:true,ledgerInserted:false});expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event(false,{id:'evt_again',created:ts-1})))).toMatchObject({ledgerInserted:false});await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event(true)));expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event(true,{id:'evt_refundagain',created:ts-1})))).toMatchObject({ledgerInserted:false});const rows=(await db.query('SELECT kind,amount_minor FROM billing_payment_ledger WHERE user_id=$1 ORDER BY kind',['stripe-user'])).rows;expect(rows.map(r=>Number(r.amount_minor))).toEqual([2900,500]);});
 it('deduplicates immediately succeeded refund.created and later refund.updated',async()=>{const f=fixture();expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event(true,{id:'evt_created',type:'refund.created'})))).toMatchObject({ledgerInserted:false});});
 it('appends one verified failed-refund credit and accepts the historical original debit after reordering',async()=>{const failed={...refund,status:'failed',failure_balance_transaction:'txn_failure'},f=fixture({'/v1/refunds/re_partial':failed,'/v1/balance_transactions/txn_failure':{id:'txn_failure',object:'balance_transaction',amount:500,currency:'usd',source:'re_partial',created:ts-2}});const input=event(true,{id:'evt_failed',type:'refund.failed',data:{object:failed}});expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(input))).toMatchObject({ledgerInserted:true});expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed({...input,id:'evt_failedagain'}))).toMatchObject({ledgerInserted:false});expect(await ingestVerifiedBillingEvent(db,clock,f.adapter,signed(event(true,{id:'evt_historicalcreated',type:'refund.created'})))).toMatchObject({ledgerInserted:false});const sum=(await db.query("SELECT SUM(CASE WHEN kind='refund_settled' THEN -amount_minor ELSE amount_minor END) AS net FROM billing_payment_ledger WHERE user_id='stripe-user'")).rows[0];expect(Number(sum.net)).toBe(2900);const normalized=await f.adapter.verifyAndNormalize(signed(input));await expect(ingestVerifiedBillingEvent(db,clock,{...f.adapter,provider:'stripe',environment:'sandbox',providerAccount:'acct_fixture',verifyAndNormalize:async()=>({...normalized,eventReference:'evt_orphancredit',subjectReference:'re_unseen'})},signed(input))).rejects.toMatchObject({code:'BILLING_REFUND_RECONCILIATION_REQUIRED'});});
 it('uses only persisted own-account invoice bindings and projects no PII',async()=>{const f=fixture();await expect(f.adapter.listOwnInvoices(db,'stripe-other',{customerReference:'cus_buyer'})).rejects.toMatchObject({code:'BILLING_CUSTOMER_NOT_BOUND'});expect(f.calls).toHaveLength(0);const r=await f.adapter.listOwnInvoices(db,'stripe-user');expect(r.invoices[0]).toMatchObject({invoiceReference:'in_fixture',amountPaidMinor:2900});expect(JSON.stringify(r)).not.toContain('email');expect(new URL(f.calls[1].url).searchParams.get('customer')).toBe('cus_buyer');});
 it('requires explicit portal configuration and stable idempotency without canceling directly',async()=>{const f=fixture(),input={subscriptionReference:'sub_fixture',operationId:'cancel-operation-1'};await expect(f.adapter.createOwnCancellationPortal(db,'stripe-user',input)).rejects.toMatchObject({code:'STRIPE_PORTAL_DISABLED'});const a=new StripeBillingAdapter({...config,portalCancellation:{configuration:'bpc_fixture',returnUrl:'https://packproof.example/account'}},credentials,clock,f.fetcher);expect(await a.createOwnCancellationPortal(db,'stripe-user',input)).toMatchObject({cancellationCompleted:false,chargesCreated:false});await a.createOwnCancellationPortal(db,'stripe-user',input);const posts=f.calls.filter(c=>c.init?.method==='POST');expect(posts).toHaveLength(2);expect(posts[0].url).toBe('https://api.stripe.com/v1/billing_portal/sessions');expect((posts[0].init?.headers as Record<string,string>)['Idempotency-Key']).toBe((posts[1].init?.headers as Record<string,string>)['Idempotency-Key']);expect(String(posts[0].init?.body)).toContain('subscription_cancel');});
 it('scans only authenticated bounded event references and refetches actual accounting facts',async()=>{const f=fixture({'/v1/events':{object:'list',has_more:false,data:[event()]},'/v1/events/evt_payment':event()});const page=await f.adapter.listAccountingEventReferences({start:'2026-09-06T00:00:00.000Z',end:now.toISOString()});expect(page).toEqual({events:[{eventReference:'evt_payment',createdAt:new Date((ts-5)*1000).toISOString()}],hasMore:false,nextStartingAfter:null});const query=new URL(f.calls[1].url).searchParams;expect(query.get('limit')).toBe('100');expect(query.getAll('types[]')).toContain('refund.failed');expect(await f.adapter.readVerifiedAccountingEvent('evt_payment')).toMatchObject({subjectReference:'pi_payment',amountMinor:2900});expect(f.calls.every(c=>c.init?.method==='GET')).toBe(true);});
 it('rejects event scan gaps, foreign scope and stalled pagination',async()=>{const f=fixture();await expect(f.adapter.listAccountingEventReferences({start:'2026-07-01T00:00:00.000Z',end:now.toISOString()})).rejects.toMatchObject({code:'STRIPE_EVENT_HISTORY_GAP'});expect(f.calls).toHaveLength(0);const bad=fixture({'/v1/events':{object:'list',has_more:false,data:[event(false,{livemode:true})]}});await expect(bad.adapter.listAccountingEventReferences({start:'2026-09-06T00:00:00.000Z',end:now.toISOString()})).rejects.toMatchObject({code:'STRIPE_ENVIRONMENT_MISMATCH'});const stuck=fixture({'/v1/events':{object:'list',has_more:true,data:[event()]}});await expect(stuck.adapter.listAccountingEventReferences({start:'2026-09-06T00:00:00.000Z',end:now.toISOString(),startingAfter:'evt_payment'})).rejects.toMatchObject({code:'STRIPE_EVENT_CURSOR_STALLED'});});
 it('rejects foreign subscriptions before any portal mutation',async()=>{const f=fixture({'/v1/subscriptions/sub_fixture':{id:'sub_fixture',object:'subscription',livemode:false,customer:'cus_other'}}),a=new StripeBillingAdapter({...config,portalCancellation:{configuration:'bpc_fixture',returnUrl:'https://packproof.example/account'}},credentials,clock,f.fetcher);await expect(a.createOwnCancellationPortal(db,'stripe-user',{subscriptionReference:'sub_fixture',operationId:'cancel-operation-2'})).rejects.toMatchObject({code:'STRIPE_CUSTOMER_MISMATCH'});expect(f.calls.every(c=>c.init?.method==='GET')).toBe(true);});
});
