import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import {createPgliteDatabase} from '../src/db/pglite.js';
import {migrate} from '../src/db/migrate.js';
import {bindBillingCustomer,type VerifiedProviderEvent} from '../src/billing/usage-ledger.js';
import {processStripeBillingReconciliation,type AccountingEventSource} from '../src/billing/daily-reconciliation.js';
import {DomainError} from '../src/domain/errors.js';
import type {Database} from '../src/db/database.js';
let db:Database,close:()=>Promise<void>,now:Date;const clock={now:()=>new Date(now)},baseline='2026-09-05T00:00:00.000Z';
const event=(id:string,amount=2900):VerifiedProviderEvent=>({eventReference:id,customerReference:'cus_fixture',subjectReference:id.replace('evt_','pi_'),paymentReference:id.replace('evt_','pi_'),kind:'payment_settled',occurredAt:'2026-09-06T10:00:00.000Z',amountMinor:amount,currency:'USD'});
function source(pages:Record<string,{events:Array<{eventReference:string;createdAt:string}>;hasMore:boolean;nextStartingAfter:string|null}>,read?:AccountingEventSource['readVerifiedAccountingEvent']){const calls:string[]=[];return{calls,provider:'stripe',environment:'sandbox' as const,providerAccount:'acct_fixture',listAccountingEventReferences:async(input:{start:string;end:string;startingAfter?:string})=>{calls.push(input.startingAfter??'first');return pages[input.startingAfter??'first'];},readVerifiedAccountingEvent:read??(async id=>event(id))};}
const queued=(id:string)=>({eventReference:id,createdAt:'2026-09-06T10:00:00.000Z'});
beforeEach(async()=>{now=new Date('2026-09-07T12:00:00.000Z');const x=await createPgliteDatabase();db=x.db;close=x.close;await migrate(db);await db.query('INSERT INTO users(id,created_at,updated_at) VALUES($1,$2,$2)',['daily-user',now.toISOString()]);await bindBillingCustomer(db,clock,{provider:'stripe',environment:'sandbox',providerAccount:'acct_fixture',customerReference:'cus_fixture',userId:'daily-user'});},30000);
afterEach(async()=>{await close();});
describe('durable daily provider reconciliation',()=>{
 it('advances a bounded cursor without HTTP and reconciles overlap only once',async()=>{const s=source({first:{events:[queued('evt_one')],hasMore:true,nextStartingAfter:'evt_one'},evt_one:{events:[queued('evt_two')],hasMore:false,nextStartingAfter:null}});expect(await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline,maxEventsPerRun:1})).toMatchObject({state:'PENDING',processed:1});now=new Date(now.getTime()+2000);expect(await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline})).toMatchObject({state:'COMPLETE',processed:1,financialReconciliation:'unreconciled'});expect(s.calls).toEqual(['first','evt_one']);now=new Date('2026-09-08T12:00:00Z');await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline});now=new Date(now.getTime()+2000);await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline});expect((await db.query('SELECT * FROM billing_payment_ledger')).rows).toHaveLength(2);});
 it('does not claim unsupported history and persists a visible gap without provider calls',async()=>{const s=source({});const old='2026-07-01T00:00:00.000Z';await processStripeBillingReconciliation(db,clock,s,{initialStartAt:old});expect(s.calls).toEqual([]);expect((await db.query('SELECT state,last_error_code FROM billing_provider_reconciliation')).rows[0]).toMatchObject({state:'BLOCKED',last_error_code:'STRIPE_EVENT_HISTORY_GAP'});});
 it('recovers lost responses via immutable ledger dedupe and expired leases',async()=>{const s=source({first:{events:[queued('evt_one')],hasMore:false,nextStartingAfter:null}});await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline});await db.query("UPDATE billing_provider_reconciliation SET state='RUNNING',lease_token='lost',lease_until=$1,next_attempt_at=$2",[new Date(now.getTime()-1).toISOString(),now.toISOString()]);await db.query("UPDATE billing_reconciliation_events SET state='PENDING',next_attempt_at=$1",[now.toISOString()]);expect(await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline})).toMatchObject({state:'COMPLETE',processed:1});expect((await db.query('SELECT * FROM billing_payment_ledger')).rows).toHaveLength(1);});
 it('keeps failures pending, records terminal failures and refuses a reset baseline',async()=>{const s=source({first:{events:[queued('evt_bad')],hasMore:false,nextStartingAfter:null}},async()=>{throw new DomainError('STRIPE_PROVIDER_UNAVAILABLE','Synthetic provider outage',502);});expect(await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline})).toMatchObject({state:'PENDING',processed:0});await db.query("UPDATE billing_reconciliation_events SET attempts=11,next_attempt_at=$1",[now.toISOString()]);now=new Date(now.getTime()+3000);expect(await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline})).toMatchObject({state:'BLOCKED'});expect((await db.query('SELECT * FROM billing_payment_ledger')).rows).toEqual([]);await expect(processStripeBillingReconciliation(db,clock,s,{initialStartAt:'2026-09-06T00:00:00.000Z'})).rejects.toMatchObject({code:'BILLING_BASELINE_CONFLICT'});});
 it('retains reversal ordering without exhausting attempts and counts no never-settled money',async()=>{const s=source({first:{events:[queued('evt_reverse'),queued('evt_pending')],hasMore:false,nextStartingAfter:null}},async id=>{throw new DomainError(id==='evt_reverse'?'BILLING_REFUND_RECONCILIATION_REQUIRED':'STRIPE_EVENT_NOT_SETTLED','Synthetic ordering fixture',409);});await processStripeBillingReconciliation(db,clock,s,{initialStartAt:baseline});const rows=(await db.query('SELECT event_reference,state,attempts FROM billing_reconciliation_events ORDER BY event_reference')).rows;expect(rows).toEqual([{event_reference:'evt_pending',state:'IGNORED',attempts:1},{event_reference:'evt_reverse',state:'PENDING',attempts:0}]);expect((await db.query('SELECT * FROM billing_payment_ledger')).rows).toEqual([]);});
});
