import { randomUUID } from 'node:crypto';
import express from 'express';
import request from 'supertest';
import {BearerUserAdapter} from '../src/auth/adapter.js';
import {createObservationRouter,observationConfigFromEnv} from '../src/analytics/observation-router.js';
import { afterEach, describe, expect, it } from 'vitest';
import { createHarness, createUser, commitProofEvidence, type TestHarness } from './helpers.js';
import { createTransaction } from '../src/domain/transactions.js';
import { createOrGetProof } from '../src/domain/create-proof.js';
import { createCaptureSession, completeCaptureSession } from '../src/domain/capture-sessions.js';
import { initializeEvidenceUpload } from '../src/domain/evidence.js';
import { buildWeeklyReport } from '../src/analytics/program-metrics.js';
import { createProgramDataset, recordProgramConsent, getProgramConsent, startProgramTiming, appendProgramTiming, exportProgramObservations, STUDY_STATEMENT_VERSION } from '../src/analytics/observation-export.js';
const config={key:'dedicated-test-analytics-key-at-least-32-bytes',keyVersion:'test-v1'};
let now=new Date('2026-09-07T12:00:00.000Z');const clock={now:()=>new Date(now)};
describe('governed operational observations',()=>{
  let h:TestHarness;
  afterEach(async()=>{await h?.close();now=new Date('2026-09-07T12:00:00.000Z');});
  async function setup(){h=await createHarness(clock);const user=await createUser(h);const dataset=await createProgramDataset(h.db,clock,config);return {user,...dataset};}
  const consent=(datasetRef:string,decision:'grant'|'withdraw'='grant')=>({datasetRef,operationNonce:randomUUID(),decision,statementVersion:STUDY_STATEMENT_VERSION});
  const start=(datasetRef:string)=>({datasetRef,operationNonce:randomUUID(),clientStartedAt:clock.now().toISOString(),deviceClass:'web',channel:'manual',taskKind:'packproof'});
  const ended=(datasetRef:string,attemptRef:string)=>({datasetRef,attemptRef,operationNonce:randomUUID(),phase:'ended',outcome:'failed',elapsedMs:5500,activeMs:700,offlineMs:4800,unattendedMs:400,errorCode:'network'});
  const period=(datasetRef:string)=>({datasetRef,start:'2026-09-07T00:00:00.000Z',end:'2026-09-08T00:00:00.000Z',asOf:clock.now().toISOString()});
  it('requires explicit consent for this account and dataset and rejects arbitrary metadata',async()=>{
    const f=await setup();expect((await getProgramConsent(h.db,config,f.user,f.datasetRef)).granted).toBe(false);
    await expect(startProgramTiming(h.db,clock,config,f.user,start(f.datasetRef))).rejects.toMatchObject({code:'STUDY_CONSENT_REQUIRED'});
    await recordProgramConsent(h.db,clock,config,f.user,consent(f.datasetRef));
    await expect(startProgramTiming(h.db,clock,config,f.user,{...start(f.datasetRef),barcode:'private'})).rejects.toMatchObject({code:'INVALID_STUDY_REQUEST'});
    const attempt=await startProgramTiming(h.db,clock,config,f.user,start(f.datasetRef));
    const other=await createUser(h);await expect(appendProgramTiming(h.db,clock,config,other,ended(f.datasetRef,attempt.attemptRef))).rejects.toMatchObject({code:'STUDY_CONSENT_REQUIRED'});
    await recordProgramConsent(h.db,clock,config,other,consent(f.datasetRef));
    await expect(appendProgramTiming(h.db,clock,config,other,ended(f.datasetRef,attempt.attemptRef))).rejects.toMatchObject({code:'STUDY_ATTEMPT_NOT_FOUND'});
    const second=await createProgramDataset(h.db,clock,config);
    await expect(startProgramTiming(h.db,clock,config,f.user,start(second.datasetRef))).rejects.toMatchObject({code:'STUDY_CONSENT_REQUIRED'});
    await expect(getProgramConsent(h.db,{...config,key:'different-key-material-that-is-long-enough'},f.user,f.datasetRef)).rejects.toMatchObject({code:'STUDY_UNAVAILABLE'});
  });
  it('replays lost-response operations exactly, keeps failures and enforces append-only timing facts',async()=>{
    const f=await setup();const grant=consent(f.datasetRef);await recordProgramConsent(h.db,clock,config,f.user,grant);
    await recordProgramConsent(h.db,clock,config,f.user,grant);
    const request=start(f.datasetRef),first=await startProgramTiming(h.db,clock,config,f.user,request);
    expect(await startProgramTiming(h.db,clock,config,f.user,request)).toEqual(first);
    await expect(startProgramTiming(h.db,clock,config,f.user,{...request,channel:'other'})).rejects.toMatchObject({code:'STUDY_OPERATION_CONFLICT'});
    const failed=ended(f.datasetRef,first.attemptRef);await appendProgramTiming(h.db,clock,config,f.user,failed);await appendProgramTiming(h.db,clock,config,f.user,failed);
    await expect(appendProgramTiming(h.db,clock,config,f.user,{...failed,elapsedMs:6000})).rejects.toMatchObject({code:'STUDY_OPERATION_CONFLICT'});
    await expect(h.db.query("UPDATE program_timing_events SET outcome='succeeded' WHERE attempt_ref=$1",[first.attemptRef])).rejects.toThrow('AUDIT_IMMUTABLE');
    await startProgramTiming(h.db,clock,config,f.user,start(f.datasetRef));
    now=new Date(now.getTime()+6000);const exported=await exportProgramObservations(h.db,clock,config,period(f.datasetRef));
    expect(exported.coverage.clientTaskStarts).toBe(2);expect(exported.coverage.clientTasksWithoutTerminalEvent).toBe(1);
    expect(exported.timingObservations.find(row=>row.phase==='ended')).toMatchObject({outcome:'failed',offlineMs:4800,authority:'client'});
    expect(exported.observations.effortTasks).toHaveLength(2);expect(exported.observations.payments).toEqual([]);
    expect(exported.events.every(event=>event.authority==='client')).toBe(true);
    const saved=JSON.stringify((await h.db.query('SELECT * FROM program_timing_events')).rows);
    for(const privateValue of [f.user,request.operationNonce,failed.operationNonce])expect(saved).not.toContain(privateValue);
    expect(JSON.stringify(exported)).not.toContain(f.user);expect(()=>buildWeeklyReport(exported.observations)).not.toThrow();
  });
  it('withdrawal prevents new or queued intake while retaining previously contributed observations',async()=>{
    const f=await setup();await recordProgramConsent(h.db,clock,config,f.user,consent(f.datasetRef));
    const attempt=await startProgramTiming(h.db,clock,config,f.user,start(f.datasetRef));
    now=new Date(now.getTime()+1000);await recordProgramConsent(h.db,clock,config,f.user,consent(f.datasetRef,'withdraw'));
    await expect(appendProgramTiming(h.db,clock,config,f.user,ended(f.datasetRef,attempt.attemptRef))).rejects.toMatchObject({code:'STUDY_CONSENT_REQUIRED'});
    const exported=await exportProgramObservations(h.db,clock,config,period(f.datasetRef));expect(exported.coverage.clientTaskStarts).toBe(1);expect(exported.coverage.clientTasksWithoutTerminalEvent).toBe(1);
    expect((await getProgramConsent(h.db,config,f.user,f.datasetRef)).granted).toBe(false);
    now=new Date(now.getTime()+1000);await recordProgramConsent(h.db,clock,config,f.user,consent(f.datasetRef));
    await expect(appendProgramTiming(h.db,clock,config,f.user,ended(f.datasetRef,attempt.attemptRef))).rejects.toMatchObject({code:'STUDY_CONSENT_INTERVAL_CHANGED'});
  });
  it('exports all canonical initialized uploads and starts without treating database commit as preservation',async()=>{
    const f=await setup();await recordProgramConsent(h.db,clock,config,f.user,consent(f.datasetRef));
    now=new Date(now.getTime()+1000);
    const transaction=await createTransaction(h.db,clock,f.user,{itemTitle:'Never export this private title'}),proof=await createOrGetProof(h.db,clock,f.user,transaction.transactionId);
    const capture=await createCaptureSession(h.db,clock,f.user,proof.proofId,{client:'WEB_CAMERA',idempotencyKey:'pending-capture'});
    await completeCaptureSession(h.db,clock,f.user,proof.proofId,capture.id,{sha256:'a'.repeat(64),byteSize:128,contentType:'video/mp4'});
    await initializeEvidenceUpload(h.db,clock,h.objectStore,f.user,proof.proofId,{idempotencyKey:'pending-upload',captureSessionId:capture.id,evidenceType:'FULFILLMENT_CAPTURE',contentType:'video/mp4',byteSize:128});
    await commitProofEvidence(h,f.user,proof.proofId,{evidenceType:'FULFILLMENT_CAPTURE',idempotencyKey:'committed-original'});
    await createCaptureSession(h.db,clock,f.user,proof.proofId,{client:'WEB_CAMERA',idempotencyKey:'never-uploaded'});
    now=new Date(now.getTime()+1000);const exported=await exportProgramObservations(h.db,clock,config,period(f.datasetRef));
    expect(exported.coverage.canonicalCaptureStarts).toBe(3);expect(exported.coverage.canonicalUploadAttempts).toBe(2);
    expect(exported.observations.uploadIntents.filter(row=>row.committedAt)).toHaveLength(1);
    expect(exported.observations.uploadIntents.every(row=>row.durableReceiptAt===null)).toBe(true);
    expect(exported.events.filter(row=>row.eventName==='upload.intent')).toHaveLength(2);
    expect(exported.events.some(row=>row.eventName==='preservation.completed')).toBe(false);
    expect(exported.observations.orders).toEqual([]);expect(exported.observations.merchants[0]).toMatchObject({qualified:false,firstUsableAt:null,enrolledAt:null});
    for(const privateValue of [proof.proofId,transaction.transactionId,capture.id,'Never export this private title'])expect(JSON.stringify(exported)).not.toContain(privateValue);
  });
  it('authenticates router actions, defaults disabled, and never exposes dataset creation or export',async()=>{
    const f=await setup();expect(observationConfigFromEnv({})).toBeNull();
    expect(()=>observationConfigFromEnv({PACKPROOF_STUDY_ENABLED:'true'})).toThrow();
    const runtime=observationConfigFromEnv({PACKPROOF_STUDY_ENABLED:'true',PACKPROOF_ANALYTICS_KEY_BASE64:Buffer.from(config.key).toString('base64'),PACKPROOF_ANALYTICS_KEY_VERSION:config.keyVersion,PACKPROOF_STUDY_DATASET_REF:f.datasetRef})!;
    const app=express();app.use(express.json({limit:'8kb'}));app.use('/study',createObservationRouter({db:h.db,clock,auth:new BearerUserAdapter(h.db)},runtime));
    app.use((error:{httpStatus?:number;code?:string},_req:express.Request,res:express.Response,_next:express.NextFunction)=>{res.status(error.httpStatus??500).json({code:error.code});});
    expect((await request(app).get('/study/consent')).status).toBe(401);
    const own=await request(app).get('/study/consent').set('Authorization',`Bearer ${f.user}`);expect(own.body).toMatchObject({enabled:true,granted:false,datasetRef:f.datasetRef});
    await request(app).post('/study/consent').set('Authorization',`Bearer ${f.user}`).send(consent(f.datasetRef)).expect(200);
    await request(app).post('/study/timings/start').set('Authorization',`Bearer ${f.user}`).send({...start(f.datasetRef),authority:'server'}).expect(400);
    await request(app).post('/study/timings/start').set('Authorization',`Bearer ${f.user}`).send(start(f.datasetRef)).expect(201);
    await request(app).post('/study/export').set('Authorization',`Bearer ${f.user}`).send({}).expect(404);
    await request(app).post('/study/datasets').set('Authorization',`Bearer ${f.user}`).send({}).expect(404);
  });
});
