import {generateKeyPairSync,sign} from 'node:crypto';
import {createAttestationChallenge} from '../src/domain/attestation-authorization.js';
import {afterEach,describe,expect,it} from 'vitest';
import request from 'supertest';
import {auth,commitFulfillmentAndAttest,commitProofEvidence,createHarness,login,type TestHarness} from './helpers.js';
import {classifyProofPresentation,withLocalProofWork} from '../src/domain/proof-presentation.js';
import {createDisclosureGrant,previewDisclosure,reuseSharedProofLink} from '../src/domain/disclosure.js';
import {createAccessLink,revokeAccessLink} from '../src/domain/access-links.js';
import {getPublicProof} from '../src/domain/public-proof.js';
import {finalizeProof} from '../src/domain/finalize.js';
import {inviteCommerceReceiver,acceptCommerceReceiver,createCommerceStage} from '../src/domain/commerce-lifecycle.js';
import {initializeEvidenceUpload} from '../src/domain/evidence.js';
let h:TestHarness;
afterEach(async()=>{await h?.close();});
const base={proofId:'proof',status:'READY_FOR_EVIDENCE',role:'SELLER',canShare:true,fulfillmentCaptureCount:0};
describe('shared navigation presentation',()=>{
 it('distinguishes role, incomplete unrelated evidence, finalization, shipment delivery and unknown states',()=>{
  expect(classifyProofPresentation(base)).toMatchObject({needsAttention:true,completed:false,displayStatus:'Recording needed',nextAction:{type:'RECORD_PACKING',label:'Record packing'}});
  expect(classifyProofPresentation({...base,committedEvidenceCount:1})).toMatchObject({displayStatus:'Recording needed'});
  expect(classifyProofPresentation({...base,role:'BUYER'})).toMatchObject({needsAttention:false,displayStatus:'Waiting for participant'});
  expect(classifyProofPresentation({...base,status:'AWAITING_PARTICIPANT'})).toMatchObject({needsAttention:false});
  expect(classifyProofPresentation({...base,fulfillmentCaptureCount:1})).toMatchObject({displayStatus:'Confirmation needed',nextAction:{type:'REVIEW_CONFIRM'}});
  expect(classifyProofPresentation({...base,shipmentStatus:'DELIVERED'})).toMatchObject({completed:false,needsAttention:true});
  expect(classifyProofPresentation({...base,status:'FINALIZED',finalizedAt:'2026-09-08T00:00:00Z'})).toMatchObject({completed:true,needsAttention:false});
  expect(classifyProofPresentation({...base,status:'FINALIZED'})).toMatchObject({completed:false,diagnostic:'FINALIZED_TIMESTAMP_MISSING'});
  for(const status of ['CANCELLED','EXPIRED','CLOSED','FUTURE_STATE']) expect(classifyProofPresentation({...base,status})).toMatchObject({completed:false,needsAttention:false,nextAction:{type:'VIEW_PROOF'},diagnostic:`UNRECOGNIZED_PROOF_STATE:${status}`});
  expect(classifyProofPresentation({...base,orderCancelled:true})).toMatchObject({needsAttention:false,completed:false,displayStatus:'Order cancelled'});
 });
 it('prioritizes invitations and local recovery, and does not call uploading actionable or committed',()=>{
  const invitation=classifyProofPresentation({...base,invitationId:'invite'});
  expect(invitation).toMatchObject({needsAttention:true,nextAction:{type:'ACCEPT_INVITATION'},share:{available:false}});
  expect(withLocalProofWork(invitation,{state:'UPLOAD_INTERRUPTED'})).toEqual(invitation);
  const pending=withLocalProofWork(classifyProofPresentation(base),{state:'UPLOADING',progress:47});
  expect(pending).toMatchObject({needsAttention:false,completed:false,displayStatus:'Uploading · 47%'});
  expect(withLocalProofWork(pending,{state:'UPLOAD_INTERRUPTED'})).toMatchObject({needsAttention:true,nextAction:{type:'RESUME_UPLOAD'}});
  expect(withLocalProofWork(pending,{state:'CAPTURE_UNFINISHED'}).nextAction.type).toBe('RECOVER_RECORDING');
  expect(withLocalProofWork(pending,{state:'CAPTURE_UNFINISHED',canResumeCapture:true}).nextAction.type).toBe('CONTINUE_RECORDING');
  const receipt=classifyProofPresentation({...base,status:'FINALIZED',finalizedAt:'2026-09-08T00:00:00Z',role:'BUYER',canShare:false,pendingStage:{type:'RECEIPT',hasEvidence:false}});
  expect(receipt).toMatchObject({completed:true,needsAttention:true,nextAction:{type:'WORKFLOW_ACTION'},share:{available:false}});
  expect(withLocalProofWork(receipt,{state:'UPLOADING'})).toMatchObject({completed:true,needsAttention:false,displayStatus:'Uploading'});
  expect(withLocalProofWork(receipt,{state:'UPLOAD_INTERRUPTED'})).toMatchObject({completed:true,needsAttention:true,nextAction:{type:'RESUME_UPLOAD'}});
 });
});
async function proof(seller:string,title='Navigation shipment'){
 const txn=await request(h.app).post('/transactions').set(auth(seller)).send({itemTitle:title,shipping:{carrier:'UPS',trackingNumber:'PRIVATE-TRACKING'}});
 expect(txn.status).toBe(201);
 const created=await request(h.app).post(`/transactions/${txn.body.transactionId}/proof`).set(auth(seller));
 expect(created.status).toBe(200);
 return created.body.proofId as string;
}
describe('navigation collection and early scoped sharing',()=>{
 it('searches and filters the full accessible dataset, paginates without duplicates and leaves legacy clients unchanged',async()=>{
  h=await createHarness();const seller=await login(h.app,'navigation-seller');const buyer=await login(h.app,'navigation-buyer');
  const id=await proof(seller,'Needle shipment');
  // Controlled database fixtures exercise beyond the legacy 100-record boundary without invoking unrelated capture work.
  await h.db.query(`INSERT INTO transactions(id,created_by,created_at,updated_at,item_title) SELECT 'nav-t-'||n,$1,$2,$2,'Other shipment '||n FROM generate_series(1,105) n`,[seller,h.clock.now().toISOString()]);
  await h.db.query(`INSERT INTO proofs(id,transaction_id,status,created_at,updated_at,participation_policy,workflow_type) SELECT 'nav-p-'||n,'nav-t-'||n,'READY_FOR_EVIDENCE',$1,$1,'COUNTERPARTY_OPTIONAL','COMMERCE_SALE' FROM generate_series(1,105) n`,[h.clock.now().toISOString()]);
  await h.db.query(`INSERT INTO proof_participants(id,proof_id,user_id,role,joined_at) SELECT 'nav-pp-'||n,'nav-p-'||n,$1,'SELLER',$2 FROM generate_series(1,105) n`,[seller,h.clock.now().toISOString()]);
  const first=await request(h.app).get('/me/proofs?view=all&limit=100').set(auth(seller));
  expect(first.status).toBe(200);expect(first.body.total).toBe(106);expect(first.body.nextOffset).toBe(100);
  const second=await request(h.app).get('/me/proofs?view=all&limit=100&offset=100').set(auth(seller));expect(second.body.proofs).toHaveLength(6);expect(second.body.nextOffset).toBeNull();
  expect(new Set([...first.body.proofs,...second.body.proofs].map(row=>row.proofId)).size).toBe(106);
  const search=await request(h.app).get('/me/proofs?view=attention&q=Needle').set(auth(seller));expect(search.body.proofs).toHaveLength(1);expect(search.body.total).toBe(1);expect(search.body.proofs[0].proofId).toBe(id);
  const detail=await request(h.app).get(`/proofs/${id}`).set(auth(seller));expect(detail.body.presentation).toEqual(search.body.proofs[0].presentation);
  const legacy=await request(h.app).get('/me/proofs').set(auth(seller));expect(legacy.body.proofs).toHaveLength(100);expect(legacy.body).not.toHaveProperty('total');
  await request(h.app).post(`/proofs/${id}/invitations`).set(auth(seller)).send({inviteeUserId:buyer}).expect(201);
  const invitations=await request(h.app).get('/me/proofs?view=attention').set(auth(buyer));expect(invitations.body.proofs).toHaveLength(1);const invited=invitations.body.proofs[0];
  expect(invited.presentation.nextAction.type).toBe('ACCEPT_INVITATION');expect(invited.transaction.trackingNumber).toBeNull();
  expect((await request(h.app).get('/me/proofs').set(auth(buyer))).body.proofs).toEqual([]);
  await request(h.app).post(`/invitations/${invited.invitationId}/accept`).set(auth(buyer)).expect(200);
  const joined=await request(h.app).get('/me/proofs?view=all').set(auth(buyer));expect(joined.body.proofs).toHaveLength(1);expect(joined.body.proofs[0].presentation.needsAttention).toBe(false);expect(joined.body.proofs[0].invitationId).toBeNull();
  for(const q of ['view=unknown','limit=101','offset=-1','q[x]=secret']) await request(h.app).get(`/me/proofs?${q}`).set(auth(seller)).expect(400);
  await request(h.app).get('/me/proofs?view=all').expect(401);
 },30000);
 it('includes targeted receipt access once, preserves its existing permission boundary, and keeps completed evidence independently actionable',async()=>{
  h=await createHarness();const seller=await login(h.app,'receipt-list-seller');const receiver=await login(h.app,'receipt-list-receiver');const id=await proof(seller);
  await commitFulfillmentAndAttest(h,seller,id);await finalizeProof(h.db,h.clock,seller,id);await inviteCommerceReceiver(h.db,h.clock,seller,id,receiver);
  const invited=(await request(h.app).get('/me/proofs?view=all').set(auth(receiver))).body.proofs;
  expect(invited).toHaveLength(1);expect(invited[0]).toMatchObject({proofId:id,accessKind:'RECEIVER',invitationId:`receipt:${id}`,presentation:{completed:true,needsAttention:true,nextAction:{type:'ACCEPT_INVITATION'},share:{available:false}}});
  expect(invited[0].transaction.trackingNumber).toBeNull();
  await request(h.app).get(`/proofs/${id}`).set(auth(receiver)).expect(403);
  await acceptCommerceReceiver(h.db,h.clock,receiver,id);
  const joined=(await request(h.app).get('/me/proofs?view=attention').set(auth(receiver))).body.proofs;
  expect(joined).toHaveLength(1);expect(joined[0]).toMatchObject({accessKind:'RECEIVER',invitationId:null,presentation:{completed:true,needsAttention:true,nextAction:{type:'WORKFLOW_ACTION',label:'Record receipt'}}});
  await request(h.app).get(`/proofs/${id}/lifecycle`).set(auth(receiver)).expect(200);
  await createCommerceStage(h.db,h.clock,receiver,id,'RECEIPT');
  expect((await request(h.app).get('/me/proofs?view=completed').set(auth(receiver))).body.proofs).toHaveLength(1);
  const participantId=await proof(seller,'Participant receipt');
  await request(h.app).post(`/proofs/${participantId}/invitations`).set(auth(seller)).send({inviteeUserId:receiver}).expect(201);
  const inbox=(await request(h.app).get('/me/proofs?view=all').set(auth(receiver))).body.proofs;
  const invitation=inbox.find((row:{proofId:string})=>row.proofId===participantId);expect(invitation.accessKind).toBe('INVITATION');
  await request(h.app).post(`/invitations/${invitation.invitationId}/accept`).set(auth(receiver)).expect(200);
  await commitFulfillmentAndAttest(h,seller,participantId);await finalizeProof(h.db,h.clock,seller,participantId);
  await inviteCommerceReceiver(h.db,h.clock,seller,participantId,receiver);await acceptCommerceReceiver(h.db,h.clock,receiver,participantId);
  const participant=(await request(h.app).get('/me/proofs?view=all').set(auth(receiver))).body.proofs;
  expect(participant).toHaveLength(2);const row=participant.find((entry:{proofId:string})=>entry.proofId===participantId);expect(row.accessKind).toBe('PARTICIPANT');
  const detail=(await request(h.app).get(`/proofs/${participantId}`).set(auth(receiver))).body;
  expect(row.presentation).toEqual(detail.presentation);
 },30000);
 it('records required packing after supporting evidence and confirms the committed native original after losing all local capture state',async()=>{
  h=await createHarness();const seller=await login(h.app,'recovery-seller');const buyer=await login(h.app,'recovery-buyer');const id=await proof(seller);
  const invite=await request(h.app).post(`/proofs/${id}/invitations`).set(auth(seller)).send({inviteeUserId:buyer});expect(invite.status).toBe(201);
  const inbox=(await request(h.app).get('/invitations').set(auth(buyer))).body.invitations;
  await request(h.app).post(`/invitations/${inbox[0].invitationId}/accept`).set(auth(buyer)).expect(200);
  const supporting=await commitProofEvidence(h,seller,id,{evidenceType:'SELLER_EVIDENCE',contentType:'image/jpeg',bytes:Buffer.from('supporting original')});
  const before=(await request(h.app).get(`/proofs/${id}`).set(auth(seller))).body;
  expect(before.status).toBe('EVIDENCE_COMMITTED');expect(before.presentation.nextAction.type).toBe('RECORD_PACKING');
  const committed=await commitProofEvidence(h,seller,id,{evidenceType:'FULFILLMENT_CAPTURE',idempotencyKey:'packing-after-attachment'});
  // Re-fetch from the server: no local recording, journal or saved signature is consulted below.
  const current=(await request(h.app).get(`/proofs/${id}`).set(auth(seller))).body;
  const original=current.evidence.find((row:{evidenceId:string})=>row.evidenceId===committed.evidenceId);
  expect(original).toMatchObject({submittedBy:seller,captureClient:'NATIVE_CAMERA',captureSessionId:expect.any(String),validationStatus:'COMMITTED'});
  expect(current.presentation.nextAction.type).toBe('REVIEW_CONFIRM');
  const counterparty=(await request(h.app).get(`/proofs/${id}`).set(auth(buyer))).body;
  expect(counterparty.evidence.find((row:{evidenceId:string})=>row.evidenceId===committed.evidenceId)).toMatchObject({captureClient:null,captureSessionId:null});
  const keys=generateKeyPairSync('ec',{namedCurve:'prime256v1'});const publicKey=keys.publicKey.export({format:'der',type:'spki'}).toString('base64');
  const input={captureSessionId:original.captureSessionId,sha256:original.sha256,publicKey};
  await expect(createAttestationChallenge(h.db,h.clock,buyer,id,input)).rejects.toMatchObject({code:'PARTICIPANT_NOT_AUTHORIZED'});
  const challenge=await createAttestationChallenge(h.db,h.clock,seller,id,input);
  const authorization={challengeId:challenge.challengeId,signature:sign('sha256',Buffer.from(challenge.payload),keys.privateKey).toString('base64')};
  await request(h.app).post(`/proofs/${id}/attestations`).set(auth(seller)).send({statement:'PACKED_DESCRIBED_ITEM',relatedEvidenceId:committed.evidenceId,authorization}).expect(201);
  const finalized=await finalizeProof(h.db,h.clock,seller,id);
  expect(finalized.proof.status).toBe('FINALIZED');
  expect(finalized.proof.evidence.find(row=>row.evidenceId===supporting.evidenceId)?.sha256).toBe(supporting.sha256);
  expect(finalized.proof.evidence.find(row=>row.evidenceId===committed.evidenceId)?.sha256).toBe(original.sha256);
 },30000);
 it('shares the same unfinished record, reuses exactly the approved live scope, and protects uncommitted sources and access boundaries',async()=>{
  h=await createHarness();const seller=await login(h.app,'early-seller');const stranger=await login(h.app,'early-stranger');const buyer=await login(h.app,'early-buyer');const id=await proof(seller);
  const input={purpose:'SHARED_PROOF',publicWebBaseUrl:'https://example.test'};
  const preview=await previewDisclosure(h.db,seller,id,input);
  const link=await createDisclosureGrant(h.db,h.clock,seller,id,{...input,originalsReviewed:true,previewHash:preview.disclosure.viewHash});if(!('token' in link))throw Error('Missing token');
  expect((await getPublicProof(h.db,h.clock,link.token)).evidenceState).toEqual({code:'NOT_RECORDED',message:'Recording has not been added yet'});
  const upload=await initializeEvidenceUpload(h.db,h.clock,h.objectStore,seller,id,{contentType:'image/jpeg',idempotencyKey:'pending-photo'});
  await h.objectStore.put(upload.objectKey,Buffer.from('PRIVATE PENDING BYTES'),'image/jpeg');
  const pending=await getPublicProof(h.db,h.clock,link.token);expect(pending.evidenceState.code).toBe('UPLOADING');expect(pending.evidence).toEqual([]);expect(pending.nextAction).toBeNull();expect(JSON.stringify(pending)).not.toContain(upload.objectKey);
  await request(h.app).get(`/public/proofs/${link.token}/evidence/${upload.evidenceId}`).expect(403);
  const same=await reuseSharedProofLink(h.db,h.clock,seller,id,link.token,input.publicWebBaseUrl);expect(same.url).toBe(link.url);expect(same.accessLinkId).toBe(link.accessLinkId);
  await request(h.app).post(`/proofs/${id}/disclosure/reuse`).set(auth(stranger)).send({token:link.token}).expect(403);
  const other=await proof(seller,'Other proof');await request(h.app).post(`/proofs/${other}/disclosure/reuse`).set(auth(seller)).send({token:link.token}).expect(404);
  const summary=await createAccessLink(h.db,h.clock,seller,id,{scope:'SUMMARY',publicWebBaseUrl:input.publicWebBaseUrl});await expect(reuseSharedProofLink(h.db,h.clock,seller,id,summary.token,input.publicWebBaseUrl)).rejects.toMatchObject({code:'INSUFFICIENT_SCOPE'});
  const invitation=await request(h.app).post(`/proofs/${id}/invitations`).set(auth(seller)).send({inviteeUserId:buyer});expect(invitation.status).toBe(201);
  const inbox=await request(h.app).get('/invitations').set(auth(buyer));await request(h.app).post(`/invitations/${inbox.body.invitations[0].invitationId}/accept`).set(auth(buyer)).expect(200);
  await expect(previewDisclosure(h.db,buyer,id,input)).rejects.toMatchObject({code:'PARTICIPANT_NOT_AUTHORIZED'});
  await expect(previewDisclosure(h.db,buyer,id,{purpose:'CLAIMS_REVIEW'})).rejects.toMatchObject({code:'PARTICIPANT_NOT_AUTHORIZED'});
  await request(h.app).post(`/proofs/${id}/disclosure/reuse`).set(auth(buyer)).send({token:link.token}).expect(403);
  await revokeAccessLink(h.db,h.clock,seller,id,link.accessLinkId);await expect(reuseSharedProofLink(h.db,h.clock,seller,id,link.token,input.publicWebBaseUrl)).rejects.toMatchObject({code:'ACCESS_LINK_REVOKED'});
  expect((await request(h.app).get(`/proofs/${id}`).set(auth(seller))).body.status).toBe('READY_FOR_EVIDENCE');
 });
});
