import type {
  CanonicalProof,
  CommerceConnectionView,
  FulfillmentQueueItem,
  InvitationInboxView,
  ProofCollectionItem,
} from "../api/types";

export const summary: ProofCollectionItem = {
  schema: "packproof.proof.summary/v1",
  proofId: "proof_01ABCVERYLONGIDENTIFIERVALUE",
  transactionId: "txn_01",
  role: "SELLER",
  status: "READY_FOR_EVIDENCE",
  createdAt: "2026-08-30T12:00:00.000Z",
  updatedAt: "2026-08-30T12:05:00.000Z",
  finalizedAt: null,
  transaction: {
    externalReference: "ORD-48392",
    itemTitle: "Vintage camera",
    transactionDate: "2026-08-29",
    carrier: "UPS",
    trackingNumber: "1Z999",
  },
};

export const invitation: InvitationInboxView = {
  invitationId: "inv_01",
  proofId: "proof_01ABCVERYLONGIDENTIFIERVALUE",
  status: "PENDING",
  createdAt: "2026-08-30T12:01:00.000Z",
  expiresAt: null,
  inviter: { userId: "user_seller", username: "seller", displayName: "Seller" },
  transaction: {
    transactionId: "txn_01",
    itemTitle: "Vintage camera",
    externalReference: "ORD-48392",
  },
};

export const canonicalProof: CanonicalProof = {
  schema: "packproof.proof.canonical/v1",
  proofId: "proof_01ABCVERYLONGIDENTIFIERVALUE",
  transactionId: "txn_01",
  status: "EVIDENCE_COMMITTED",
  version: 1,
  createdAt: "2026-08-30T12:00:00.000Z",
  updatedAt: "2026-08-30T12:10:00.000Z",
  finalizedAt: null,
  manifestId: null,
  transaction: {
    transactionId: "txn_01",
    externalReference: "ORD-48392",
    transactionDate: "2026-08-29",
    itemTitle: "Vintage camera",
    itemDescription: "Black body",
    quantity: 1,
    transactionValue: 120,
    currency: "USD",
    createdBy: "user_seller",
    createdAt: "2026-08-30T12:00:00.000Z",
    updatedAt: "2026-08-30T12:00:00.000Z",
    metadata: {},
    shipping: {
      carrier: "UPS",
      service: null,
      trackingNumber: "1Z999",
      shipmentDate: null,
    },
    proofId: "proof_01ABCVERYLONGIDENTIFIERVALUE",
    proofStatus: "EVIDENCE_COMMITTED",
    sellerUserId: "user_seller",
    buyerUserId: "user_buyer",
  },
  participants: [
    {
      participantId: "prt_s",
      userId: "user_seller",
      role: "SELLER",
      status: "JOINED",
      invitationState: "ACCEPTED",
      joinedAt: "2026-08-30T12:00:00.000Z",
    },
    {
      participantId: "prt_b",
      userId: "user_buyer",
      role: "BUYER",
      status: "JOINED",
      invitationState: "ACCEPTED",
      joinedAt: "2026-08-30T12:02:00.000Z",
    },
  ],
  invitations: [],
  evidence: [
    {
      evidenceId: "evd_1",
      evidenceType: "SELLER_EVIDENCE",
      validationStatus: "COMMITTED",
      submittedBy: "user_seller",
      createdAt: "2026-08-30T12:08:00.000Z",
      receivedAt: "2026-08-30T12:08:00.000Z",
      committedAt: "2026-08-30T12:09:00.000Z",
      sha256: "8af291d4deadbeefcafebabef00d000011112222333344445555666677778888",
      byteSize: 12,
      digest: {
        algorithm: "SHA-256",
        sha256: "8af291d4deadbeefcafebabef00d000011112222333344445555666677778888",
      },
    },
  ],
  attestations: [
    {
      kind: "ATTESTATION",
      attestationId: "att_1",
      attestedBy: "user_seller",
      statement: "PACKED_DESCRIBED_ITEM",
      relatedEvidenceId: "evd_1",
      createdAt: "2026-08-30T12:09:30.000Z",
      digest: { algorithm: "SHA-256", sha256: "aa".repeat(32) },
    },
  ],
  events: [
    {
      eventId: "aud_1",
      eventType: "PROOF_CREATED",
      actorUserId: "user_seller",
      at: "2026-08-30T12:00:00.000Z",
      data: {},
    },
    {
      eventId: "aud_2",
      eventType: "PARTICIPANT_JOINED",
      actorUserId: "user_buyer",
      at: "2026-08-30T12:02:00.000Z",
      data: {},
    },
    {
      eventId: "aud_3",
      eventType: "EVIDENCE_COMMITTED",
      actorUserId: "user_seller",
      at: "2026-08-30T12:09:00.000Z",
      data: {},
    },
  ],
  facts: [
    {
      kind: "FACT",
      name: "EVIDENCE_DIGEST_RECORDED",
      at: "2026-08-30T12:09:00.000Z",
      data: { sha256: "8af291d4deadbeefcafebabef00d000011112222333344445555666677778888" },
    },
  ],
  external: {
    records: [
      {
        kind: "EXTERNAL",
        field: "transaction.itemTitle",
        value: "Vintage camera",
        source: "PARTICIPANT_SUPPLIED",
        verifiedByPackProof: false,
      },
      {
        kind: "EXTERNAL",
        field: "shipping.trackingNumber",
        value: "1Z999",
        source: "PARTICIPANT_SUPPLIED",
        verifiedByPackProof: false,
      },
    ],
    references: [
      {
        tenantKey: "packproof:transaction",
        externalTransactionId: "ORD-48392",
        source: "PARTICIPANT_SUPPLIED",
      },
    ],
  },
  integrity: {
    algorithm: "SHA-256",
    evidence: [
      {
        evidenceId: "evd_1",
        sha256: "8af291d4deadbeefcafebabef00d000011112222333344445555666677778888",
      },
    ],
    manifestSha256: null,
  },
  shipmentObservations: {
    shippingId: "shp_1",
    identity: {
      carrier: "UPS",
      service: null,
      trackingNumber: "1Z999",
      shipmentDate: null,
    },
    events: [],
    latest: null,
  },
  chronology: [
    {
      id: "aud_1",
      occurredAt: "2026-08-30T12:00:00.000Z",
      category: "PROOF",
      title: "Proof created",
      description: null,
      source: "PACKPROOF",
      relatedEntityId: "aud_1",
      eventType: "PROOF_CREATED",
    },
    {
      id: "aud_2",
      occurredAt: "2026-08-30T12:02:00.000Z",
      category: "PROOF",
      title: "Participant joined",
      description: null,
      source: "PACKPROOF",
      relatedEntityId: "aud_2",
      eventType: "PARTICIPANT_JOINED",
    },
    {
      id: "aud_3",
      occurredAt: "2026-08-30T12:09:00.000Z",
      category: "PROOF",
      title: "Packing evidence committed",
      description: "Integrity confirmed",
      source: "PACKPROOF",
      relatedEntityId: "aud_3",
      eventType: "EVIDENCE_COMMITTED",
    },
  ],
};

export const fulfillmentItem: FulfillmentQueueItem = {
  transactionId: "txn_ds_1001",
  proofId: "proof_ds_1001",
  connectionId: "icn_demo",
  provider: "demo-storefront",
  providerDisplay: "Demo Storefront",
  externalAccountReference: "demo-store-001",
  externalOrderId: "DS-1001",
  externalReference: "DS-1001",
  items: [
    {
      itemId: "itm_1",
      externalItemId: "line-1001-1",
      position: 1,
      title: "Pokémon Booster Box",
      description: "Sealed English booster box",
      sku: "SKU-1001",
      quantity: 1,
      unitValue: 229,
      currency: "USD",
    },
  ],
  itemSummary: "Pokémon Booster Box",
  itemCount: 1,
  transactionValue: 229,
  currency: "USD",
  orderedAt: "2026-08-01T15:00:00.000Z",
  proofStatus: "READY_FOR_EVIDENCE",
  participationPolicy: "COUNTERPARTY_OPTIONAL",
  sellerPackingAttested: false,
  evidenceCount: 0,
  pendingEvidenceCount: 0,
  fulfillmentCaptureCount: 0,
  canComplete: false,
  workflowState: "READY_TO_PACK",
};

export const fulfillmentNext: FulfillmentQueueItem = {
  ...fulfillmentItem,
  transactionId: "txn_ds_1002",
  proofId: "proof_ds_1002",
  externalOrderId: "DS-1002",
  externalReference: "DS-1002",
  items: [
    {
      itemId: "itm_2",
      externalItemId: "line-1002-1",
      position: 1,
      title: "Vintage Watch",
      description: null,
      sku: null,
      quantity: 1,
      unitValue: 1500,
      currency: "USD",
    },
  ],
  itemSummary: "Vintage Watch",
  transactionValue: 1500,
};

export const demoConnection: CommerceConnectionView = {
  connectionId: "icn_demo",
  adapterKey: "demo-storefront",
  provider: "demo-storefront",
  providerDisplay: "Demo Storefront",
  externalAccountReference: "demo-store-001",
  status: "ACTIVE",
  lastSyncAt: null,
  lastErrorCode: null,
  retryable: null,
  readyOrderCount: 7,
};
