import "fake-indexeddb/auto";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { App } from "../App";
import { PackProofApi } from "../api/client";
import { saveSession } from "../auth/session";
import { canonicalWorkspacePath, rememberProofListState } from "../proof-list-state";
import { clearViewState } from "../navigation-context";
import { ProofsScreen } from "../screens/ProofsScreen";
import { ProofScreen } from "../screens/ProofScreen";
import { SharingCode } from "../components/SharingCode";
import { PrivacySharePanel } from "../components/PrivacySharePanel";
import { SharedProofRecord } from "../components/SharedProofRecord";
import { classifyProofPresentation } from "../../../backend/src/domain/proof-presentation";
import { canonicalProof, summary } from "./fixtures";
const json = (value: unknown) => new Response(JSON.stringify(value), { headers: { "content-type": "application/json" } });
beforeEach(() => { localStorage.clear(); sessionStorage.clear(); window.history.replaceState({}, "", "/proofs"); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
it("replaces legacy routes while preserving canonical identities and list parameters", () => {
  for (const path of ["/app", "/home", "/overview", "/activity"]) expect(canonicalWorkspacePath(path)).toBe("/proofs");
  expect(canonicalWorkspacePath("/fulfillment/proof-7?q=camera")).toBe("/proofs/proof-7?q=camera");
  expect(canonicalWorkspacePath("/station?proof=proof-7&reference=ORD-8")).toBe("/proofs/proof-7?reference=ORD-8");
  expect(canonicalWorkspacePath("/proofs/proof-7/complete")).toBe("/proofs/proof-7");
  expect(canonicalWorkspacePath("/p/existing-share-token")).toBe("/p/existing-share-token");
  rememberProofListState("account-a", { view: "attention", query: "private title" });
  expect(canonicalWorkspacePath("/proofs", "account-a")).toBe("/proofs?filter=attention");
  expect(canonicalWorkspacePath("/proofs?filter=all", "account-a")).toBe("/proofs?filter=all");
  expect(canonicalWorkspacePath("/proofs", "account-b")).toBe("/proofs");
  clearViewState();
  expect(canonicalWorkspacePath("/proofs", "account-a")).toBe("/proofs");
});
it("loads search matches beyond the first server page and rejects a broken pagination cursor", async () => {
  const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
    const url = new URL(String(input), "https://test.example");
    expect(url.searchParams.get("q")).toBe("camera");
    return json(url.searchParams.get("offset") === "0" ? { proofs: [summary], nextOffset: 100 } : { proofs: [{ ...summary, proofId: "later-proof" }], nextOffset: null });
  });
  vi.stubGlobal("fetch", fetchMock);
  const api = new PackProofApi({ baseUrl: "", getToken: () => "test" });
  expect((await api.listProofs({ view: "all", q: "camera" })).proofs.map(item => item.proofId)).toEqual([summary.proofId, "later-proof"]);
  expect(fetchMock).toHaveBeenCalledTimes(2);
  fetchMock.mockImplementation(async () => json({ proofs: [summary], nextOffset: 0 }));
  await expect(api.listProofs({ view: "all", q: "camera" })).rejects.toThrow("could not be loaded completely");
});
it("opens Proofs directly with one creation action and only Proofs and Connections in primary navigation", async () => {
  saveSession({ apiBaseUrl: "", authMode: "dev", userId: "navigation-test", username: "seller", displayName: "Seller", token: "test-token", refreshToken: null, accessExpiresAt: null, subject: "seller" });
  vi.stubGlobal("fetch", vi.fn(async (input: RequestInfo | URL) => String(input).includes("/me/proofs?") ? json({ proofs: [summary], nextOffset: null }) : json({ proofs: [], invitations: [] })));
  window.history.replaceState({}, "", "/app");
  render(<App />);
  expect(await screen.findByRole("button", { name: /Vintage camera. Recording needed. Record packing/ })).toBeVisible();
  expect(window.location.pathname).toBe("/proofs");
  expect(screen.getAllByRole("button", { name: "New Proof" })).toHaveLength(1);
  expect(screen.getByRole("link", { name: "Connections" })).toBeInTheDocument();
  expect(screen.queryByRole("link", { name: "Orders" })).not.toBeInTheDocument();
  expect(screen.queryByRole("link", { name: "Overview" })).not.toBeInTheDocument();
});
const listProps = { proofs: [], view: "all" as const, query: "", loading: false, error: null, onChange: vi.fn(), onRetry: vi.fn(), onOpenProof: vi.fn(), onOpenInvitation: vi.fn(), onOpenReceiver: vi.fn(), onCreate: vi.fn() };
it("keeps failed loading distinct from empty lists and routes receiver invitations through their existing access flow", async () => {
  const { rerender } = render(<ProofsScreen {...listProps} error="Network unavailable" />);
  expect(screen.getByRole("alert")).toHaveTextContent("Network unavailable");
  expect(screen.queryByText("No Proofs yet")).not.toBeInTheDocument();
  rerender(<ProofsScreen {...listProps} view="attention" />);
  expect(screen.getByText("Nothing needs your attention")).toBeInTheDocument();
  const invitationRow = { ...summary, accessKind: "RECEIVER" as const, invitationId: "receipt:proof", presentation: classifyProofPresentation({ proofId: summary.proofId, status: "FINALIZED", invitationId: "receipt:proof", role: "BUYER" }) };
  rerender(<ProofsScreen {...listProps} proofs={[invitationRow, invitationRow]} />);
  const row = screen.getAllByRole("button", { name: /Vintage camera. Invitation received/ });
  expect(row).toHaveLength(1);
  await userEvent.click(row[0]);
  expect(listProps.onOpenReceiver).toHaveBeenCalledWith(summary.proofId);
  expect(listProps.onOpenInvitation).not.toHaveBeenCalled();
});
it("keeps Share in the persisted seller record header before recording and exposes no buyer sharing action", () => {
  const api = { recoveryScope: "scope", getRecoveryStatus: vi.fn().mockResolvedValue(null), featureRequest: vi.fn().mockResolvedValue({ snapshot: { data: { anchors: [] } } }) } as unknown as PackProofApi;
  const proof = { ...canonicalProof, status: "READY_FOR_EVIDENCE", evidence: [] };
  const { rerender } = render(<ProofScreen proof={proof} api={api} currentUserId="user_seller" loading={false} error={null} busy={false} shipmentIntegrity={null} />);
  expect(screen.getByRole("button", { name: "Share" })).toBeVisible();
  expect(screen.getByText("Recording has not been added yet")).toBeInTheDocument();
  rerender(<ProofScreen proof={proof} api={api} currentUserId="user_buyer" loading={false} error={null} busy={false} shipmentIntegrity={null} />);
  expect(screen.queryByRole("button", { name: "Share" })).not.toBeInTheDocument();
});
it("reuses the cached disclosure grant without creating another and checks current authorization before copying", async () => {
  const grant = { accessLinkId: "grant-1", proofId: canonicalProof.proofId, scope: "EVIDENCE_VIEW", token: "cached-token", url: "https://proof.example/p/cached-token", createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 86400000).toISOString(), revokedAt: null };
  sessionStorage.setItem(`packproof.view.share.scope.user_seller.${canonicalProof.proofId}.SHARED_PROOF`, JSON.stringify(grant));
  const featureRequest = vi.fn(async () => grant);
  const api = { recoveryScope: "scope", featureRequest } as unknown as PackProofApi;
  const user = userEvent.setup();
  const copy = vi.spyOn(navigator.clipboard, "writeText").mockResolvedValue();
  render(<PrivacySharePanel api={api} proof={canonicalProof} currentUserId="user_seller" />);
  await user.click(screen.getByRole("button", { name: "Copy link" }));
  expect(featureRequest).toHaveBeenCalledExactlyOnceWith(canonicalProof.proofId, "disclosure/reuse", "POST", { token: "cached-token" });
  expect(copy).toHaveBeenCalledExactlyOnceWith(grant.url);
  expect(await screen.findByText("Link copied.")).toBeInTheDocument();
});
it("does not report a failed clipboard operation or dismissed share sheet as delivery", async () => {
  const user = userEvent.setup();
  vi.spyOn(navigator.clipboard, "writeText").mockRejectedValue(new Error("Clipboard permission denied"));
  Object.defineProperty(navigator, "share", { configurable: true, value: vi.fn().mockRejectedValue(new DOMException("Cancelled", "AbortError")) });
  render(<SharingCode url="https://proof.example/p/token" expiresAt={null} />);
  await user.click(screen.getByRole("button", { name: "Copy link" }));
  expect(await screen.findByRole("alert")).toHaveTextContent("Clipboard permission denied");
  expect(screen.queryByText("Link copied.")).not.toBeInTheDocument();
  await user.click(screen.getByRole("button", { name: "Share link" }));
  expect(await screen.findByText("Sharing dismissed.")).toBeInTheDocument();
});
it("shows the server incomplete state without exposing pending evidence or participant controls", async () => {
  render(<SharedProofRecord proof={{ schema: "packproof.proof.public/v1", proofId: "proof", status: "READY_FOR_EVIDENCE", scope: "EVIDENCE_VIEW", workflowType: "COMMERCE_SALE", workflowStage: "PACKING", nextAction: null, evidence: [], evidenceState: { code: "UPLOADING", message: "Evidence is still uploading" }, join: { eligible: false, requiresAuthentication: true, message: "" } }} />);
  expect(screen.getByText("Evidence is still uploading")).toBeInTheDocument();
  expect(screen.queryByRole("button", { name: "Record packing" })).not.toBeInTheDocument();
  expect(screen.queryByRole("video")).not.toBeInTheDocument();
});
