// GENERATED by scripts/generate-rnd-client.mjs; DO NOT EDIT.
// Input + generator SHA-256: 68e53c5043dbf4954572922dfba9235baf8d8060d5faf7e4682945cdd69e2d81
export const RND_API_VERSION = "0.1.0-rnd.1";
export const RND_API_SCHEMA_DIGEST = "68e53c5043dbf4954572922dfba9235baf8d8060d5faf7e4682945cdd69e2d81";
const routes = {
  "getCapabilities": {
    "method": "GET",
    "template": "/rnd/capabilities",
    "pathParameters": {},
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "recordConsent": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/consents",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "issueCaptureIntent": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/capture-intents",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "startCaptureIntent": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/capture-intents/{intent}/start",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "intent": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "closeCaptureIntent": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/capture-intents/{intent}/close",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "intent": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "uploadCaptureSidecar": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/capture-intents/{intent}/sidecars/{name}",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "intent": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "name": {
        "type": "string",
        "pattern": "^(research-acquisition\\.json|native-journal\\.jsonl|research-frame-[0-5]\\.pgm)$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "issueLiveChallenge": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/live-challenges",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "requestAnalysis": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/analyses",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "listAnalyses": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/analyses",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "requestComparison": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/comparisons",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "requestDerivative": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/derivatives",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "getAnalysis": {
    "method": "GET",
    "template": "/rnd/analyses/{analysisId}",
    "pathParameters": {
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "listExtensions": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/extensions",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {
      "after": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      }
    },
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "exportResearchMetadata": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/exports",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "downloadResearchZip": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/export.zip",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": true
  },
  "getAnalysisArtifact": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/analyses/{analysisId}/artifacts/{index}",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "index": {
        "type": "integer",
        "minimum": 0
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": true
  },
  "derivativeReview": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/analyses/{analysisId}/review",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "downloadDerivativeZip": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/analyses/{analysisId}/export.zip",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": true
  },
  "createEnrollment": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/enrollments",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "listEnrollments": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/enrollments",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "addAnnotation": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/annotations",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "listAnnotations": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/annotations",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "issuePlatformChallenge": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/platform-challenges",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "verifyPlatformChallenge": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/platform-challenges/{challengeId}/verify",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "challengeId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "createDerivativeGrant": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/analyses/{analysisId}/grants",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "listDerivativeGrants": {
    "method": "GET",
    "template": "/proofs/{id}/rnd/analyses/{analysisId}/grants",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "revokeDerivativeGrant": {
    "method": "POST",
    "template": "/proofs/{id}/rnd/derivative-grants/{grantId}/revoke",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      },
      "grantId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": true,
    "binary": false
  },
  "redeemDerivativeGrant": {
    "method": "POST",
    "template": "/rnd/derivative-grants/redeem",
    "pathParameters": {},
    "queryParameters": {},
    "idempotent": false,
    "body": true,
    "binary": true
  },
  "getMetrics": {
    "method": "GET",
    "template": "/admin/rnd/metrics",
    "pathParameters": {},
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "retryAnalysis": {
    "method": "POST",
    "template": "/admin/rnd/analyses/{analysisId}/retry",
    "pathParameters": {
      "analysisId": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": true,
    "body": true,
    "binary": false
  },
  "importLearningReport": {
    "method": "POST",
    "template": "/admin/rnd/learning-reports",
    "pathParameters": {},
    "queryParameters": {},
    "idempotent": false,
    "body": true,
    "binary": false
  },
  "listLearningReports": {
    "method": "GET",
    "template": "/admin/rnd/learning-reports",
    "pathParameters": {},
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  },
  "exportLearningReport": {
    "method": "GET",
    "template": "/admin/rnd/learning-reports/{id}/export",
    "pathParameters": {
      "id": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9_:./-]{1,180}$"
      }
    },
    "queryParameters": {},
    "idempotent": false,
    "body": false,
    "binary": false
  }
};
export const RND_OPERATIONS = Object.freeze(Object.keys(routes));
const own = (value,key) => Object.prototype.hasOwnProperty.call(value,key);
function validateParameter(value,schema,name) {
 if(schema.type==='integer') {
  if(!Number.isSafeInteger(value)||value<schema.minimum||schema.maximum!==undefined&&value>schema.maximum)throw new TypeError('Invalid '+name);
 } else if(typeof value!=='string'||schema.pattern&&!new RegExp(schema.pattern).test(value)||schema.minLength!==undefined&&value.length<schema.minLength||schema.maxLength!==undefined&&value.length>schema.maxLength)throw new TypeError('Invalid '+name);
 if(value==='.'||value==='..')throw new TypeError('Invalid '+name);
 return String(value);
}
/** Pure transport builder. Body/schema/cryptographic policy remains server-authoritative. */
export function buildRndRequest(operationId,input={}) {
 if(!own(routes,operationId))throw new TypeError('Unknown R&D operation');
 const route=routes[operationId],headers={Accept:route.binary?'application/octet-stream':'application/json'};
 for(const key of Object.keys(input))if(!['path','query','body','idempotencyKey','signal'].includes(key))throw new TypeError('Unexpected request field: '+key);
 for(const key of Object.keys(input.path??{}))if(!own(route.pathParameters,key))throw new TypeError('Unexpected path parameter');
 let pathname=route.template;
 for(const [key,schema] of Object.entries(route.pathParameters))pathname=pathname.replace('{'+key+'}',encodeURIComponent(validateParameter(input.path?.[key],schema,key)));
 const query=new URLSearchParams();
 for(const [key,value] of Object.entries(input.query??{})){
  if(!own(route.queryParameters,key))throw new TypeError('Unexpected query parameter');
  if(value!==undefined)query.set(key,validateParameter(value,route.queryParameters[key],key));
 }
 if(query.size)pathname+='?'+query.toString();
 if(route.idempotent)headers['Idempotency-Key']=validateParameter(input.idempotencyKey,{type:'string',pattern:'^[a-zA-Z0-9_:./-]{1,180}$'},'Idempotency-Key');
 else if(input.idempotencyKey!==undefined)throw new TypeError('Operation does not accept an idempotency key');
 if(route.body){if(input.body===undefined)throw new TypeError('Request body required');headers['Content-Type']='application/json';}
 else if(input.body!==undefined)throw new TypeError('Operation does not accept a request body');
 return {path:pathname,method:route.method,body:input.body,headers};
}
export class RndApiError extends Error {
 constructor(status,code,message,details){super(message);this.name='RndApiError';this.status=status;this.code=code;this.details=details;}
}
/** No token storage, background retry, refresh, or account selection is performed. */
export function createRndClient({baseUrl='',fetch:transport=globalThis.fetch,headers:configuredHeaders,credentials}={}) {
 if(typeof transport!=='function')throw new TypeError('A fetch implementation is required');
 if(typeof baseUrl!=='string'||/[?#]/.test(baseUrl))throw new TypeError('baseUrl must not include query or fragment');
 const base=baseUrl.replace(/\/$/,'');
 const request=async(operationId,input={})=>{
  const built=buildRndRequest(operationId,input);
  const initial=typeof configuredHeaders==='function'?await configuredHeaders():configuredHeaders;
  const headers=new Headers(initial);
  for(const [name,value] of Object.entries(built.headers))headers.set(name,value);
  const response=await transport(base+built.path,{method:built.method,headers,body:built.body===undefined?undefined:JSON.stringify(built.body),signal:input.signal,...(credentials===undefined?{}:{credentials}),redirect:'error',cache:'no-store'});
  if(!response.ok){let details;try{details=await response.json();}catch{details=null;}throw new RndApiError(response.status,details?.error?.code??'RND_HTTP_ERROR',details?.error?.message??('Research request failed ('+response.status+')'),details);}
  return routes[operationId].binary?response.arrayBuffer():response.json();
 };
 return Object.freeze({request,...Object.fromEntries(RND_OPERATIONS.map(id=>[id,input=>request(id,input)]))});
}
