import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spoolCommittedEvidence,spoolPreservedStream} from './media-files.js';
import {streamPreservedObject} from './evidence.js';
import {MEDIA_MAX_BYTES} from './media-admission.js';
import type {Database} from '../db/database.js';
import type {Clock} from '../clock.js';
import type {ObjectStore} from '../s3/object-store.js';
import {canonicalize} from '../canonical.js';
import {sha256Hex} from '../hash.js';
import {newId} from '../ids.js';
import {DomainError} from './errors.js';
import {getSignatureCase, type SignatureCasePreview} from './signature.js';
import {appendAudit} from './audit.js';
import {RECIPIENT_PROFILES,recipientProfile,validateRecipientFiles,type RecipientProfile,type EncodedRecipientFile} from '../export/recipient-profiles.js';
import {extractRecipientFrame,renderFactsImages,recipientPdf,RENDERER_VERSION} from '../export/recipient-renderer.js';
import {zipFiles} from '../export/zip.js';
type Frame={evidenceId:string;offsetMs:number;label:string};
type ExportRequest={caseId:string;caseSha256:string;profile:RecipientProfile;frames:Frame[];narrative:string;destinationDeadline:string;destinationInstructionsReviewed:true;scopeStatement:string};
type FileMeta={name:string;contentType:string;byteSize:number;sha256:string;objectKey:string;pages:number};
type Artifact={schema:string;jobId:string;proofId:string;caseId:string;caseSha256:string;snapshotId:string;snapshotSha256:string;manifestSha256:string|null;recordAsOf?:{sequence:number;sha256:string|null;snapshotAt:string};profile:RecipientProfile;scope:string;approvedNarrative:string;destinationDeadline:string;files:FileMeta[];sources:Array<{evidenceId:string;sourceSha256:string;requestedOffsetMs:number;presentationTimestampMs:number;extractionTool:string;recipeVersion:string;crop:null;transform:string;originalFrameSha256:string;originalFrameObjectKey:string;derivedFileSha256:string}>;gaps:string[];createdAt:string;portalAcceptance:'NOT_TESTED';submission:'MERCHANT_CONTROLLED'};
type Job={id:string;proof_id:string;case_id:string;actor_user_id:string;request_json:string;request_sha256:string;state:string;attempts:number;artifact_json:string|null;artifact_sha256:string|null;failure_code:string|null;created_at:string};
const fail=(code:string,message:string,status=409)=>new DomainError(code,message,status);
export function listRecipientProfiles(clock:Clock){return {profiles:RECIPIENT_PROFILES.map(p=>({...p,reviewRequired:clock.now().getTime()>=Date.parse(p.reviewAfter)})),limitations:'Profile constraints are checked against official instructions. Actual case deadlines, portal acceptance and reviewer comprehension require separate confirmation.'};}
export async function queueRecipientExport(db:Database,clock:Clock,actor:string,proofId:string,input:Record<string,unknown>){
 const profile=recipientProfile(input.profileId,clock.now());
 if(typeof input.caseId!=='string'||typeof input.idempotencyKey!=='string'||!input.idempotencyKey.trim()||input.idempotencyKey.length>200)throw fail('EXPORT_INPUT_INVALID','A case, destination profile and retry key are required.',400);
 if(input.destinationInstructionsReviewed!==true||typeof input.destinationDeadline!=='string'||!Number.isFinite(Date.parse(input.destinationDeadline))||Date.parse(input.destinationDeadline)<=clock.now().getTime())throw fail('EXPORT_DESTINATION_REVIEW_REQUIRED','Check the actual destination instructions and enter its future submission deadline.');
 const packet=await getSignatureCase(db,actor,proofId,input.caseId);
 if(packet.createdBy!==actor)throw fail('EXPORT_CREATOR_REQUIRED','Create your own scoped case preview before preparing destination files.',403);
 if(typeof input.narrative!=='string'||input.narrative.length>2000)throw fail('EXPORT_NARRATIVE_INVALID','Supporting text must be at most 2,000 characters.',400);
 if(!Array.isArray(input.frames)||input.frames.length<1||input.frames.length>4)throw fail('EXPORT_FRAME_SELECTION_REQUIRED','Select one to four relevant source frames.',400);
 const frames=input.frames.map((x:any)=>{if(!x||typeof x.evidenceId!=='string'||!Number.isSafeInteger(x.offsetMs)||x.offsetMs<0||x.offsetMs>21600000||typeof x.label!=='string'||!x.label.trim()||x.label.length>120)throw fail('EXPORT_FRAME_INVALID','Each frame needs an evidence ID, offset and short factual label.',400);const source=packet.preview.evidence.find(e=>e.evidenceId===x.evidenceId);if(!source||!source.contentType.startsWith('video/'))throw fail('EXPORT_SOURCE_OUTSIDE_SCOPE','Select a recording included in this case scope.',403);if(source.capturedDurationMs!=null&&x.offsetMs>=source.capturedDurationMs)throw fail('EXPORT_FRAME_RANGE','The selected frame is outside the recording.');return {evidenceId:x.evidenceId,offsetMs:x.offsetMs,label:x.label.trim()};});
 const req:ExportRequest={caseId:input.caseId,caseSha256:packet.sha256,profile,frames,narrative:input.narrative.trim(),destinationDeadline:new Date(input.destinationDeadline).toISOString(),destinationInstructionsReviewed:true,scopeStatement:'Scoped snapshot of this Proof. Only the selected case fields and frames are included; other evidence or contrary observations may exist.'};
 const json=canonicalize(req),hash=sha256Hex(json);
 return db.transaction(async tx=>{
  await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[actor]);
  const old=(await tx.query<Job>('SELECT * FROM recipient_export_jobs WHERE proof_id=$1 AND actor_user_id=$2 AND idempotency_key=$3',[proofId,actor,input.idempotencyKey])).rows[0];
  if(old){if(old.request_sha256!==hash)throw fail('EXPORT_RETRY_CONFLICT','Changed text, profile, selection or deadline requires a new preview and approval.');return jobView(old);}
  const n=(await tx.query<{count:string}>("SELECT count(*) AS count FROM recipient_export_jobs WHERE actor_user_id=$1 AND created_at>$2",[actor,new Date(clock.now().getTime()-3600000).toISOString()])).rows[0];if(Number(n.count)>=10)throw fail('EXPORT_RATE_LIMIT','Up to ten recipient packets may be prepared per hour.',429);
  const row=(await tx.query<Job>(`INSERT INTO recipient_export_jobs(id,proof_id,case_id,actor_user_id,idempotency_key,request_json,request_sha256,profile_id,state,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'QUEUED',$9) RETURNING *`,[newId('rex'),proofId,input.caseId,actor,input.idempotencyKey,json,hash,profile.id,clock.now().toISOString()])).rows[0];return jobView(row);
 });
}
function jobView(j:Job){return {jobId:j.id,proofId:j.proof_id,caseId:j.case_id,state:j.state,requestSha256:j.request_sha256,artifactSha256:j.artifact_sha256,artifact:j.artifact_json?JSON.parse(j.artifact_json):null,failureCode:j.failure_code,createdAt:j.created_at};}
async function loadJob(db:Database,actor:string,proofId:string,id:string){const j=(await db.query<Job>('SELECT * FROM recipient_export_jobs WHERE id=$1 AND proof_id=$2',[id,proofId])).rows[0];if(!j)throw fail('EXPORT_NOT_FOUND','Recipient packet is unavailable.',404);await getSignatureCase(db,actor,proofId,j.case_id);if(j.actor_user_id!==actor)throw fail('EXPORT_NOT_FOUND','Recipient packet is unavailable.',404);if(sha256Hex(j.request_json)!==j.request_sha256||(j.artifact_json&&sha256Hex(j.artifact_json)!==j.artifact_sha256))throw fail('EXPORT_INTEGRITY_FAILURE','The packet integrity check failed.');return j;}
export async function getRecipientExport(db:Database,actor:string,proofId:string,id:string){const j=await loadJob(db,actor,proofId,id);return {...jobView(j),approval:(await db.query('SELECT actor_user_id AS "actorUserId",artifact_sha256 AS "artifactSha256",approved_at AS "approvedAt" FROM recipient_export_approvals WHERE job_id=$1',[id])).rows[0]??null};}
export async function approveRecipientExport(db:Database,clock:Clock,store:ObjectStore,actor:string,proofId:string,id:string,input:Record<string,unknown>){const j=await loadJob(db,actor,proofId,id);if(j.state!=='READY'||!j.artifact_json||input.artifactSha256!==j.artifact_sha256)throw fail('EXPORT_PREVIEW_CHANGED','Review the exact completed files before approving.');if(input.legibilityConfirmed!==true)throw fail('EXPORT_LEGIBILITY_REQUIRED','Confirm that the selected facts and images are readable in the exact files.');const a=JSON.parse(j.artifact_json) as Artifact;await approvedFileBytes(store,a.files);if(Date.parse(a.destinationDeadline)<=clock.now().getTime())throw fail('EXPORT_DEADLINE_PASSED','The recorded destination deadline has passed. Review the current case before creating a new packet.');
 await db.transaction(async tx=>{const r=await tx.query('INSERT INTO recipient_export_approvals(job_id,actor_user_id,artifact_sha256,approved_at,legibility_confirmed) VALUES($1,$2,$3,$4,true) ON CONFLICT(job_id) DO NOTHING RETURNING job_id',[id,actor,j.artifact_sha256,clock.now().toISOString()]);if(r.rowCount)await appendAudit(tx,{proofId,actorUserId:actor,eventType:'RECIPIENT_EXPORT_APPROVED',eventData:{jobId:id,artifactSha256:j.artifact_sha256,profileVersion:a.profile.version,caseSha256:a.caseSha256,files:a.files.map(f=>({name:f.name,sha256:f.sha256,byteSize:f.byteSize})),legibilityConfirmed:true},at:clock.now()});});return getRecipientExport(db,actor,proofId,id);}
async function approvedFileBytes(store:ObjectStore,files:FileMeta[]){const bytes:Buffer[]=[];for(const f of files){const obj=await store.get(f.objectKey);if(!obj||obj.body.length!==f.byteSize||sha256Hex(obj.body)!==f.sha256)throw fail('EXPORT_INTEGRITY_FAILURE','A stored packet file no longer matches its approved digest.');bytes.push(obj.body);}return bytes;}
export async function readRecipientExportFile(db:Database,store:ObjectStore,actor:string,proofId:string,id:string,index:number,preview=false){const j=await loadJob(db,actor,proofId,id);if(j.state!=='READY'||!j.artifact_json)throw fail('EXPORT_NOT_READY','The packet is still being prepared.');if(!preview&&!(await db.query('SELECT job_id FROM recipient_export_approvals WHERE job_id=$1 AND artifact_sha256=$2',[id,j.artifact_sha256])).rows[0])throw fail('EXPORT_APPROVAL_REQUIRED','Approve the exact files before downloading the submission.');const a=JSON.parse(j.artifact_json) as Artifact,f=a.files[index];if(!Number.isInteger(index)||!f)throw fail('EXPORT_FILE_NOT_FOUND','File is unavailable.',404);return {file:f,bytes:(await approvedFileBytes(store,[f]))[0]};}
export async function downloadRecipientExport(db:Database,store:ObjectStore,actor:string,proofId:string,id:string){const j=await loadJob(db,actor,proofId,id);if(j.state!=='READY'||!j.artifact_json||!(await db.query('SELECT job_id FROM recipient_export_approvals WHERE job_id=$1 AND artifact_sha256=$2',[id,j.artifact_sha256])).rows[0])throw fail('EXPORT_APPROVAL_REQUIRED','Approve the exact files before downloading the submission.');const a=JSON.parse(j.artifact_json) as Artifact,bytes=await approvedFileBytes(store,a.files);const receipt=await getRecipientExport(db,actor,proofId,id);return zipFiles([...a.files.map((f,i)=>({name:`submission/${f.name}`,bytes:bytes[i]})),{name:'supporting-text.txt',bytes:Buffer.from(a.approvedNarrative)},{name:'verification-receipt.json',bytes:Buffer.from(canonicalize(receipt))},{name:'READ-ME.txt',bytes:Buffer.from('Upload only the files inside submission/ to the selected destination; paste approved supporting text where accepted. The ZIP and verification receipt are for your records. No dispute was submitted by PackProof. Portal acceptance, deadline and claim outcome are separate from format validation.')}]);}
function factualText(p:SignatureCasePreview,r:ExportRequest){const events=p.shipping?.events??[],selected=events.slice(-8);return ['PackProof - evidence for review',p.title,`Proof: ${p.proofId}`,`Snapshot: ${p.snapshotId}`,`Source snapshot SHA-256: ${p.snapshotSha256}`,r.scopeStatement,`Record status: ${p.status??'Withheld'}`,`Order reference: ${p.order?.externalReference??'Not included'}`,`Parcel: ${p.order?.parcelId??'No allocation declared'}`,`Allocation: ${p.order?.allocationAssurance??'Not established'}`,`Tracking identifier: ${p.shipping?.trackingNumber??'Not included'}`,`Item: ${p.order?.itemTitle??'Not included'}`,`Quantity: ${p.order?.quantity??'Not available'}`,`Order facts source: ${p.order?.source??'Not included'}`,'','Supporting text (user supplied):',r.narrative||'No additional narrative.','','Shipping observations:',...selected.map(e=>`${e.occurredAt}: ${e.title}; source ${e.source}; provider ${e.provider??'none'}; environment ${e.providerEnvironment??'unknown'}`),...(events.length>8?[`${events.length-8} earlier observations omitted from this concise packet.`]:[]),...(!events.length?['No carrier delivery observation included.']:[]),'Carrier-reported delivery does not verify contents or recipient identity.','Address-match evidence: not established by this packet.','','Declarations:',...p.statements.slice(0,3).map(s=>`${s.statement} (source: ${s.source})`),...(p.statements.length>3?['Additional declarations omitted from this scoped packet.']:[]),'','Material gaps:',...p.gaps,'Scope excludes original video bytes. Selected stills are embedded below.','PackProof makes no decision about fault, liability or claim eligibility.'].join('\n');}
export async function processRecipientExport(db:Database,clock:Clock,store:ObjectStore){
 const lease=newId('exportlease'),now=clock.now();
 await db.query("UPDATE recipient_export_jobs SET state='FAILED',failure_code='EXPORT_ATTEMPTS_EXHAUSTED',lease_token=NULL,lease_until=NULL WHERE state='RENDERING' AND lease_until<=$1 AND attempts>=3",[now.toISOString()]);
 const j=await db.transaction(async tx=>{const row=(await tx.query<Job>("SELECT * FROM recipient_export_jobs WHERE (state='QUEUED' OR (state='RENDERING' AND lease_until<=$1)) AND (lease_until IS NULL OR lease_until<=$1) AND attempts<3 ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED",[now.toISOString()])).rows[0];if(!row)return null;await tx.query("UPDATE recipient_export_jobs SET state='RENDERING',attempts=attempts+1,lease_token=$2,lease_until=$3 WHERE id=$1",[row.id,lease,new Date(now.getTime()+10*60000).toISOString()]);return row;});if(!j)return {processed:0,failed:0};
 try{if(sha256Hex(j.request_json)!==j.request_sha256)throw fail('EXPORT_INTEGRITY_FAILURE','Request changed.');const r=JSON.parse(j.request_json) as ExportRequest;recipientProfile(r.profile.id,clock.now());const packet=await getSignatureCase(db,j.actor_user_id,j.proof_id,j.case_id);if(packet.sha256!==r.caseSha256)throw fail('EXPORT_SOURCE_CHANGED','Case preview changed.');const p=packet.preview;
 const images=await renderFactsImages(factualText(p,r)),sources:Artifact['sources']=[];
 for(const [i,f] of r.frames.entries()){
  const media=p.evidence.find(e=>e.evidenceId===f.evidenceId);if(!media)throw fail('EXPORT_SOURCE_OUTSIDE_SCOPE','Selected evidence is no longer authorized.',403);
  const row=media.stageId?(await db.query<{id:string;object_key:string;object_version_id:string|null;content_type:string;sha256:string;byte_size:string}>("SELECT e.id,e.object_key,e.object_version_id,e.content_type,e.sha256,e.byte_size FROM commerce_stage_evidence e JOIN commerce_stages s ON s.id=e.stage_id WHERE e.id=$1 AND s.id=$2 AND s.proof_id=$3 AND e.committed_at IS NOT NULL AND e.discarded_at IS NULL",[media.evidenceId,media.stageId,j.proof_id])).rows[0]:(await db.query<{id:string;object_key:string;object_version_id:string|null;content_type:string;sha256:string;byte_size:string}>("SELECT id,object_key,object_version_id,content_type,sha256,byte_size FROM evidence WHERE id=$1 AND proof_id=$2 AND validation_status='COMMITTED'",[media.evidenceId,j.proof_id])).rows[0];
  if(!row||row.sha256!==media.sha256||Number(row.byte_size)>MEDIA_MAX_BYTES)throw fail('EXPORT_SOURCE_LIMIT','Selected source is unavailable or exceeds the accepted recording limit.');
  const sourceDir=await mkdtemp(path.join(os.tmpdir(),'packproof-recipient-source-'));let rendered:Awaited<ReturnType<typeof extractRecipientFrame>>;
  try {const filename=path.join(sourceDir,'source');const spooled=media.stageId?await spoolPreservedStream(await streamPreservedObject(store,row),filename,MEDIA_MAX_BYTES):await spoolCommittedEvidence(db,store,j.actor_user_id,j.proof_id,media.evidenceId,filename,MEDIA_MAX_BYTES);if(spooled.sha256!==media.sha256)throw fail('EXPORT_SOURCE_INTEGRITY','Original evidence integrity failed.');rendered=await extractRecipientFrame(filename,f.offsetMs,f.label);}finally{await rm(sourceDir,{recursive:true,force:true});}
  const frameHash=sha256Hex(rendered.originalFrame),frameKey=`recipient-exports/${j.proof_id}/${j.id}/original-frame-${i}-${frameHash}`;await store.put(frameKey,rendered.originalFrame,'image/png');rendered.file.name=`frame-${i+1}.jpg`;images.push(rendered.file);sources.push({evidenceId:media.evidenceId,sourceSha256:media.sha256,requestedOffsetMs:f.offsetMs,presentationTimestampMs:rendered.actualMs,extractionTool:rendered.toolVersion,recipeVersion:RENDERER_VERSION,crop:null,transform:'Full frame scaled proportionally into 1500x2000 white page; factual caption added.',originalFrameSha256:frameHash,originalFrameObjectKey:frameKey,derivedFileSha256:sha256Hex(rendered.file.bytes)});
 }
 const files:EncodedRecipientFile[]=r.profile.destination==='STRIPE_DISPUTE'?[recipientPdf(images)]:images;const validation=validateRecipientFiles(r.profile,files);if(validation.bytes>r.profile.targetBytes)throw fail('EXPORT_RELEVANCE_REQUIRED','Select fewer relevant frames or shorter text to retain readable files within the conservative size budget.',413);
 const metadata:FileMeta[]=[];for(const file of files){const hash=sha256Hex(file.bytes),key=`recipient-exports/${j.proof_id}/${j.id}/${hash}`;await store.put(key,file.bytes,file.contentType);metadata.push({name:file.name,contentType:file.contentType,byteSize:file.bytes.length,sha256:hash,objectKey:key,pages:file.pages});}
 const artifact:Artifact={schema:'packproof.recipient-export.v1',jobId:j.id,proofId:j.proof_id,caseId:j.case_id,caseSha256:packet.sha256,snapshotId:p.snapshotId,snapshotSha256:p.snapshotSha256,manifestSha256:p.coreManifestSha256,...(p.recordAsOf?{recordAsOf:p.recordAsOf}:{}),profile:r.profile,scope:r.scopeStatement,approvedNarrative:r.narrative,destinationDeadline:r.destinationDeadline,files:metadata,sources,gaps:[...p.gaps,'Address-match evidence is not established by this packet.','PayPal protection eligibility is not established.'],createdAt:clock.now().toISOString(),portalAcceptance:'NOT_TESTED',submission:'MERCHANT_CONTROLLED'};
 const json=canonicalize(artifact),hash=sha256Hex(json);await db.query("UPDATE recipient_export_jobs SET state='READY',artifact_json=$3,artifact_sha256=$4,completed_at=$5,lease_token=NULL,lease_until=NULL,failure_code=NULL WHERE id=$1 AND lease_token=$2",[j.id,lease,json,hash,clock.now().toISOString()]);return {processed:1,failed:0};
 }catch(error){const code=error instanceof DomainError?error.code:'EXPORT_RENDER_FAILED';const retry=!(error instanceof DomainError)&&j.attempts+1<3;await db.query("UPDATE recipient_export_jobs SET state=$4,failure_code=$3,lease_token=NULL,lease_until=$5 WHERE id=$1 AND lease_token=$2",[j.id,lease,code,retry?'QUEUED':'FAILED',retry?new Date(clock.now().getTime()+30000*2**j.attempts).toISOString():null]);return {processed:0,failed:1};}
}
