import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { OnboardingController, STEPS, type Transport } from '../../../packages/onboarding/model';
import './onboarding.css';
export const replayTutorial=()=>window.dispatchEvent(new Event('packproof:replay-tutorial'));
export function Onboarding({api,accountKey,dashboard,ready=true,onDashboard,onCreate,onViewProof,capture=false,secured=false}:{api:Transport;accountKey:string;dashboard:boolean;ready?:boolean;onDashboard:()=>void;onCreate:()=>void;onViewProof:(id:string)=>void;capture?:boolean;secured?:boolean}) {
 const [controller]=useState(()=>new OnboardingController(api,{read:async()=>localStorage.getItem(`packproof:onboarding:${accountKey}`),write:async value=>{localStorage.setItem(`packproof:onboarding:${accountKey}`,value);}}));
 const [,render]=useState(0);const [captureSecured,setCaptureSecured]=useState(false);const [cameraDismissed,setCameraDismissed]=useState(false);const [securedDismissed,setSecuredDismissed]=useState(false);
 const callbacks=useRef({onDashboard,onCreate,onViewProof});callbacks.current={onDashboard,onCreate,onViewProof};
 useEffect(()=>{const off=controller.subscribe(()=>render(n=>n+1));void controller.load();const refresh=()=>void controller.refresh();const saved=()=>{setCaptureSecured(true);setCameraDismissed(true);refresh();};window.addEventListener('packproof:capture-secured',saved);const replay=()=>{callbacks.current.onDashboard();controller.start(true);};window.addEventListener('online',refresh);window.addEventListener('focus',refresh);window.addEventListener('packproof:replay-tutorial',replay);const timer=setInterval(refresh,15000);return()=>{off();controller.stop();clearInterval(timer);window.removeEventListener('packproof:capture-secured',saved);window.removeEventListener('online',refresh);window.removeEventListener('focus',refresh);window.removeEventListener('packproof:replay-tutorial',replay);};},[controller]);
 const {state,step,open,replay}=controller.snapshot;
 useEffect(()=>{if(dashboard&&ready&&!open)controller.start();},[controller,dashboard,ready,state?.onboarding_completed,state?.current_version,open]);
 const coaching=state?.onboarding_enrolled&&!state.first_proof_coaching_completed&&!open;
 return <>{open&&dashboard&&ready&&<OnboardingOverlay step={step} replay={replay} onViewed={()=>controller.viewed()} onBack={()=>controller.move(-1)} onNext={()=>{if(step===STEPS.length-1){controller.finish();callbacks.current.onCreate();}else controller.move(1);}} onSkip={()=>controller.finish(true)}/>}
 {coaching&&state.first_proof_completed&&state.first_proof_id?<aside className="onboarding-coach" role="status"><strong>Your first Proof is complete.</strong><div><button onClick={()=>{controller.dismissCoaching();callbacks.current.onViewProof(state.first_proof_id!);}}>View Proof</button><button aria-label="Dismiss guidance" onClick={()=>controller.dismissCoaching()}>Dismiss</button></div></aside>:coaching&&capture&&!cameraDismissed?<aside className="onboarding-coach" role="status"><span>Keep recording while you pack. One continuous capture preserves the sequence.</span><button onClick={()=>setCameraDismissed(true)}>Got it</button><button onClick={()=>controller.dismissCoaching()}>Dismiss guidance</button></aside>:coaching&&(secured||captureSecured)&&!securedDismissed?<aside className="onboarding-coach" role="status"><strong>Capture secured locally</strong><p>Your upload continues automatically. You may leave this screen.</p><button onClick={()=>setSecuredDismissed(true)}>Got it</button><button onClick={()=>controller.dismissCoaching()}>Dismiss guidance</button></aside>:null}</>;
}
export function OnboardingOverlay({step,replay,onViewed,onBack,onNext,onSkip}:{step:number;replay:boolean;onViewed:()=>void;onBack:()=>void;onNext:()=>void;onSkip:()=>void}) {
 const card=useRef<HTMLDivElement>(null);const layer=useRef<HTMLDivElement>(null);const [bounds,setBounds]=useState({x:12,y:12,w:0,h:0,top:80,left:12,above:false});const [found,setFound]=useState(false);
 const actions=useRef({onViewed,onSkip});actions.current={onViewed,onSkip};
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const siblings=[...document.body.children].filter(el=>el!==layer.current&&el instanceof HTMLElement) as HTMLElement[];const old=siblings.map(el=>el.inert);siblings.forEach(el=>{el.inert=true;});card.current?.focus();return()=>{siblings.forEach((el,i)=>{el.inert=old[i];});previous?.focus?.();};},[]);
 useEffect(()=>{
  let viewed=false;let target:Element|null=null;
  const measure=()=>{const next=document.querySelector(`[data-onboarding~="${STEPS[step].target}"]`);if(!next){setFound(false);return;}if(next!==target){target=next;target.scrollIntoView({block:'nearest',behavior:'instant'});}const r=target.getBoundingClientRect();if(!r.width||!r.height){setFound(false);return;}
   const width=Math.min(360,window.innerWidth-24),height=card.current?.offsetHeight??230;const x=Math.max(6,r.left-5),y=Math.max(6,r.top-5),w=Math.min(r.width+10,window.innerWidth-x-6),h=Math.min(r.height+10,window.innerHeight-y-6);
   const above=(STEPS[step].position==='above'&&y>height+24)||y+h+height+24>window.innerHeight;const top=Math.max(12,Math.min(above?y-height-16:y+h+16,window.innerHeight-height-12));
   setBounds({x,y,w,h,top,left:Math.max(12,Math.min(x,window.innerWidth-width-12)),above});setFound(true);if(!viewed){viewed=true;actions.current.onViewed();}
  };
  measure();const observer=new ResizeObserver(measure);observer.observe(document.documentElement);if(card.current)observer.observe(card.current);window.addEventListener('resize',measure);window.addEventListener('scroll',measure,true);const timer=setInterval(measure,500);return()=>{observer.disconnect();clearInterval(timer);window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure,true);};
 },[step]);
 return createPortal(<div className="onboarding-layer" ref={layer} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();onSkip();}if(event.key==='Tab'){const nodes=card.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===card.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}}>
  <div className="onboarding-spotlight" style={{left:bounds.x,top:bounds.y,width:found?bounds.w:0,height:found?bounds.h:0}}/>
  <div ref={card} role="dialog" aria-modal="true" aria-labelledby="onboarding-title" aria-describedby="onboarding-body" tabIndex={-1} className="onboarding-card" style={{top:bounds.top,left:bounds.left}}>
   {found&&<span className={`onboarding-pointer ${bounds.above?'below':'above'}`} aria-hidden="true"/>}<div className="onboarding-meta">{replay?'Tutorial':'Getting started'} · {step+1} of {STEPS.length}</div><h2 id="onboarding-title">{STEPS[step].title}</h2><p id="onboarding-body">{STEPS[step].body}</p>
   {!found&&<p role="status">Waiting for this control to load…</p>}<div className="onboarding-actions"><button onClick={onSkip}>Skip</button><span/><button disabled={step===0} onClick={onBack}>Back</button><button className="onboarding-primary" disabled={!found} onClick={onNext}>{step===STEPS.length-1?'Create Proof':'Next'}</button></div>
  </div></div>,document.body);
}
