import type { CommerceConnectionView, FulfillmentQueueItem, ProofCollectionItem } from "../api/types";
import { Glyph } from "../site/Brand";
import { useViewState } from "../navigation-context";

export function OverviewScreen({ proofs, orders, connections, loading, error, onGo }: {
  proofs: ProofCollectionItem[]; orders: FulfillmentQueueItem[]; connections: CommerceConnectionView[];
  loading: boolean; error: string | null; onGo: (path: string) => void;
}) {
  const [filter, setFilter] = useViewState("overview.filter", "ready");
  const inProgress = proofs.filter(p => p.status !== "FINALIZED");
  const finished = proofs.filter(p => p.status === "FINALIZED");
  const issues = connections.filter(c => c.lastErrorCode || c.status === "NEEDS_REAUTH");
  const firstRun = !proofs.length;
  return <main className="page stack overview-work">
    <div className="workspace-heading"><div><p className="workspace-overline">YOUR WORKSPACE</p><h1 className="page-title">{firstRun ? "Your next shipment starts here." : "Ready when you are."}</h1><p>{firstRun ? "Start with your store’s order. Record the packing. Share the Proof." : "Pick up an order and keep the packing moving."}</p></div><a className="btn btn-secondary" href="/new" onClick={e => { e.preventDefault(); onGo("/new"); }}>One-off shipment</a></div>
    {error && <div className="banner banner-error" role="alert">{error}<button className="btn btn-secondary" onClick={() => onGo("/app")}>Try again</button></div>}
    {issues.length > 0 && <section className="section attention-queue"><h2>Needs your attention</h2>{issues.map(c => <div key={c.connectionId}><span><strong>{c.providerDisplay}</strong><p>{c.status === "NEEDS_REAUTH" ? "Reconnect your store to resume importing orders." : "An order check needs attention. Your existing Proofs are preserved."}</p></span><button className="btn btn-secondary" onClick={() => onGo("/stores")}>{c.status === "NEEDS_REAUTH" ? "Reconnect store" : "Review connection"}</button></div>)}</section>}
    {!loading && !connections.length && firstRun && <section className="onboarding-next"><span className="feature-icon"><Glyph name="store" size={28}/></span><div><p className="panel-eyebrow">START WITH YOUR ORDER</p><h2>Connect your selling platform.</h2><p>Check supported providers and choose automatic order intake. Existing eligible sales become ready to record.</p><button className="btn" onClick={() => onGo("/stores")}>Connect a store <Glyph size={16}/></button> <a href="/sample">View a sample Proof</a></div></section>}
    <div className="overview-summary" aria-label="Choose your work">{[{id:"ready",label:"Needs recording",count:orders.length},{id:"progress",label:"In progress",count:inProgress.length},{id:"finished",label:"Ready to share",count:finished.length}].map(s => <button key={s.id} aria-pressed={filter === s.id} onClick={() => setFilter(s.id)}><strong>{loading ? "—" : s.count}</strong><span>{s.label}</span></button>)}</div>
    <section className="section work-queue"><div className="section-head"><div><p className="panel-eyebrow">YOUR NEXT ACTION</p><h2>{filter === "ready" ? "Orders ready to record" : filter === "progress" ? "Continue a Proof" : "Completed Proofs"}</h2></div><button className="btn btn-secondary" onClick={() => onGo(filter === "ready" ? "/fulfillment" : "/proofs")}>View all</button></div>
    {loading ? <p role="status">Checking your workspace…</p> : filter === "ready" ? orders.length ? <div className="ready-order-list">{orders.slice(0,8).map(o => <article key={o.proofId} data-context-anchor={`order-${o.proofId}`}><span className="ready-order-icon"><Glyph name="box"/></span><div><strong>{o.itemSummary}</strong><p>{o.providerDisplay} · Order {o.externalReference || o.externalOrderId}</p></div><button className="btn" onClick={() => onGo(`/station?proof=${encodeURIComponent(o.proofId)}&reference=${encodeURIComponent(o.externalReference || o.externalOrderId)}`)}>Record packing <Glyph name="film" size={16}/></button></article>)}</div> : <div className="queue-empty"><Glyph name="box" size={32}/><h3>{connections.length ? "No orders are waiting to be packed." : "Your orders will be ready here."}</h3><p>{connections.length ? "Check Connections for automatic intake status and the last successful check." : "Connect a supported store, or start a one-off shipment."}</p><button className="btn btn-secondary" onClick={() => onGo("/stores")}>{connections.length ? "Check connections" : "Connect a store"}</button></div> : <div className="ready-order-list">{(filter === "progress" ? inProgress : finished).slice(0,8).map(p => <article key={p.proofId} data-context-anchor={`proof-${p.proofId}`}><span className="ready-order-icon"><Glyph name={p.status === "FINALIZED" ? "shield" : "film"}/></span><div><strong>{p.transaction.itemTitle || "Shipment"}</strong><p>{p.status === "FINALIZED" ? "Captured record locked · ready to review and share" : "Open the record to continue its next step"}</p></div><button className="btn" onClick={() => onGo(`/proofs/${encodeURIComponent(p.proofId)}`)}>{p.status === "FINALIZED" ? "View Proof" : "Continue"}</button></article>)}{!(filter === "progress" ? inProgress : finished).length && <p className="empty">{filter === "progress" ? "No unfinished Proofs." : "Finish your first Proof to see it here."}</p>}</div>}
    </section>
    {firstRun && <ol className="first-proof-steps" aria-label="Your first Proof"><li aria-current={!connections.length ? "step" : undefined}><strong>1 · Bring in an order</strong><span>Connect a store or add a one-off sale.</span></li><li aria-current={connections.length && !proofs.length ? "step" : undefined}><strong>2 · Record the packing</strong><span>Show the item, the box, and the seal.</span></li><li><strong>3 · Finish and share</strong><span>Review the recording and preview the recipient’s view.</span></li></ol>}
  </main>;
}
