import {useEffect,useState} from "react";
import type {PackProofApi} from "../api/client";
type Entry={linkId:string;state:string;note?:string;reason?:string;previousProofId?:string;proofId?:string;events?:Array<{eventId:string;state:string;note:string;createdAt:string}>};
type Preview={proofId:string;recipientUserId:string;linkIds:string[];entries:Entry[];limitations:string[]};
function HistoryPreview({preview}:{preview:Preview}){return <div className="case-preview"><h3>Selected item history</h3>{preview.entries.map(e=><article key={e.linkId}><strong>{e.state.replaceAll("_"," ")}</strong><p>{e.note||e.reason}</p>{e.events?.map(v=><blockquote key={v.eventId}>{v.state} · {new Date(v.createdAt).toLocaleString()}<p>{v.note}</p></blockquote>)}</article>)}{preview.limitations.map(l=><p className="note" key={l}>{l}</p>)}<details><summary>Exact selected history contents</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(preview,null,2)}</pre></details></div>;}
export function HistoryHandoff({api,proofId,entries}:{api:PackProofApi;proofId:string;entries:Entry[]}){
  const [selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(""),[users,setUsers]=useState<Array<{userId:string;username:string|null;displayName:string|null}>>([]),[recipient,setRecipient]=useState(""),[preview,setPreview]=useState<{preview:Preview;previewSha256:string}|null>(null),[shared,setShared]=useState<{shareId:string;path:string}|null>(null),[incoming,setIncoming]=useState<{preview:Preview;changedSinceApproval:boolean}|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const incomingId=new URLSearchParams(location.search).get("historyShare");
  useEffect(()=>{if(incomingId)void api.featureRequest<{preview:Preview;changedSinceApproval:boolean}>(proofId,`signature/history/shares/${encodeURIComponent(incomingId)}`).then(setIncoming).catch(e=>setError(e.message));},[api,proofId,incomingId]);
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:"History handoff unavailable.");}finally{setBusy(false);}}
  return <section className="stack" aria-label="Selected history handoff">{error&&<p className="banner banner-error" role="alert">{error}</p>}{incoming&&<><p className="panel-eyebrow">HISTORY SHARED WITH YOU</p>{incoming.changedSinceApproval&&<p className="note">Permissions or consent changed since this selection was approved. Unavailable entries remain withheld.</p>}<HistoryPreview preview={incoming.preview}/></>}
    <details><summary>Preview a selected history handoff</summary><p>Choose existing links and an account. Both accounts must already have permission and consent for every source; sharing this selection grants no private recording access.</p>{entries.filter(e=>e.state!=="UNAVAILABLE").map(e=><label className="row" key={e.linkId}><input type="checkbox" checked={selected.includes(e.linkId)} onChange={event=>{setSelected(v=>event.target.checked?[...v,e.linkId]:v.filter(id=>id!==e.linkId));setPreview(null);setShared(null);}}/>{e.note||e.state}</label>)}<form className="row" onSubmit={e=>{e.preventDefault();void run(async()=>setUsers((await api.searchUsers(query)).users));}}><label className="field"><span>Recipient’s PackProof username</span><input value={query} onChange={e=>setQuery(e.target.value)} maxLength={120}/></label><button className="btn btn-secondary" disabled={busy||query.trim().length<3}>Find account</button></form>{users.map(u=><button className="btn btn-secondary" key={u.userId} aria-pressed={recipient===u.userId} onClick={()=>{setRecipient(u.userId);setPreview(null);setShared(null);}}>{u.displayName||u.username} · @{u.username}</button>)}<button className="btn" disabled={busy||!recipient||!selected.length} onClick={()=>void run(async()=>setPreview(await api.featureRequest(proofId,"signature/history/preview","POST",{recipientUserId:recipient,linkIds:selected})))}>Preview selected entries</button>{preview&&<><HistoryPreview preview={preview.preview}/><button className="btn" disabled={busy} onClick={()=>void run(async()=>setShared(await api.featureRequest(proofId,"signature/history/share","POST",{recipientUserId:recipient,linkIds:selected,previewSha256:preview.previewSha256})))}>Approve this selection and create handoff</button></>}{shared&&<><a href={shared.path}>Open approved history handoff</a><button className="btn btn-secondary" onClick={()=>void navigator.clipboard.writeText(location.origin+shared.path)}>Copy handoff link</button><button className="btn btn-secondary" disabled={busy} onClick={()=>void run(async()=>{await api.featureRequest(proofId,`signature/history/shares/${shared.shareId}/revoke`,"POST",{});setShared(null);})}>Revoke handoff</button><p className="note">Nothing has been sent. Only the selected authorized account can open this handoff.</p></>}</details>
  </section>;
}
