import { useEffect, useRef, useState } from "react";
import type { PackProofApi } from "../api/client";
import type { CanonicalProof } from "../api/types";

type Mask = {x:number;y:number;width:number;height:number};
type Derivative = {derivativeId:string;evidenceId:string;status:string;sha256:string|null;contentType:string;transform?:{type?:string}};
export function MediaPrivacyTools({api,proof}:{api:PackProofApi;proof:CanonicalProof}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
  const [derivatives,setDerivatives]=useState<Derivative[]>([]),[maskSource,setMaskSource]=useState(""),[masks,setMasks]=useState<Mask[]>([]);
  const [sourceUrl,setSourceUrl]=useState<string|null>(null),[reviewUrl,setReviewUrl]=useState<string|null>(null),[reviewing,setReviewing]=useState<Derivative|null>(null);
  const owned=useRef<string[]>([]);
  const pendingStart=useRef<{x:number;y:number}|null>(null);
  const evidence=proof.evidence.filter(e=>e.validationStatus==="COMMITTED");
  const refresh=async()=>setDerivatives((await api.featureRequest<{derivatives:Derivative[]}>(proof.proofId,"disclosure/redactions")).derivatives);
  useEffect(()=>{void refresh().catch(()=>undefined);return()=>owned.current.forEach(url=>URL.revokeObjectURL(url));},[api,proof.proofId]);
  const changed=()=>{setNotice(null);};
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:"Sharing could not be completed.");}finally{setBusy(false);}}
  async function openSource(id:string){setMaskSource(id);setMasks([]);setReviewing(null);setReviewUrl(null);setSourceUrl(null);await run(async()=>{const url=URL.createObjectURL(await api.getEvidenceBlob(proof.proofId,id));owned.current.push(url);setSourceUrl(url);});}
  const source=evidence.find(e=>e.evidenceId===maskSource);
  return <section className="section stack"><h2>Private media copies</h2><p className="note">These copies do not replace original recordings in the shared Proof.</p>{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}    <details><summary>Create a redacted copy</summary><p>Mark private regions. Opaque masks cover these regions throughout the video; audio and hidden metadata are removed. Review the resulting copy before making it shareable.</p><div className="scope-checks">{evidence.filter(e=>e.contentType?.startsWith("video/")||e.contentType?.startsWith("image/")).map((e,i)=><button className="btn btn-secondary" disabled={busy} key={e.evidenceId} onClick={()=>void openSource(e.evidenceId)}>Review source {i+1}</button>)}</div>
      {sourceUrl&&<><div className="redaction-editor" style={{position:"relative",touchAction:"none",maxWidth:720}} onPointerDown={e=>{if((e.target as HTMLElement).closest("video")&&source?.contentType?.startsWith("video/"))return;const r=e.currentTarget.getBoundingClientRect();pendingStart.current={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{const start=pendingStart.current;if(!start)return;const r=e.currentTarget.getBoundingClientRect();const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));const width=Math.abs(x-start.x),height=Math.abs(y-start.y);if(width>.01&&height>.01)setMasks(old=>[...old,{x:Math.min(start.x,x),y:Math.min(start.y,y),width,height}]);pendingStart.current=null;}}>
        {source?.contentType?.startsWith("video/")?<video src={sourceUrl} controls playsInline style={{width:"100%",display:"block"}} aria-label="Private original for redaction review"/>:<img src={sourceUrl} style={{width:"100%",display:"block"}} alt="Private original for redaction review"/>}{masks.map((m,i)=><div key={i} aria-hidden style={{position:"absolute",pointerEvents:"none",left:`${m.x*100}%`,top:`${m.y*100}%`,width:`${m.width*100}%`,height:`${m.height*100}%`,background:"#071b2ac9",border:"2px solid #4fd0ff"}}/>)}</div><p className="note">The overlay above is an editing guide. Only the server-rendered copy is shared.</p><button className="btn btn-secondary" onClick={()=>setMasks(old=>[...old,{x:.05,y:.65,width:.9,height:.3}])}>Add private-region mask</button>{masks.map((m,i)=><fieldset key={i}><legend>Mask {i+1} · percentage of original frame</legend><div className="scope-checks">{(["x","y","width","height"] as const).map(key=><label key={key}>{key}<input type="number" min={0} max={100} step={1} value={Math.round(m[key]*100)} onChange={e=>{const v=Math.max(0,Math.min(1,Number(e.target.value)/100));setMasks(old=>old.map((item,j)=>j===i?{...item,[key]:v}:item));}}/></label>)}<button className="btn btn-secondary" onClick={()=>setMasks(old=>old.filter((_,j)=>j!==i))}>Remove mask</button></div></fieldset>)}<button className="btn" disabled={busy||!masks.length||masks.some(m=>m.width<=0||m.height<=0||m.x+m.width>1||m.y+m.height>1)} onClick={()=>void run(async()=>{const d=await api.featureRequest<Derivative>(proof.proofId,`disclosure/redactions/${maskSource}`,"POST",{masks});await refresh();if(d.status!=="READY"){setNotice("Redaction queued. Refresh rendering status below to review it when ready.");return;}setReviewing(d);const url=URL.createObjectURL(await api.featureDownload(proof.proofId,`disclosure/redactions/${d.derivativeId}/media`));owned.current.push(url);setReviewUrl(url);})}>{busy?"Rendering redacted copy…":"Render private regions out"}</button></>}
      <button className="btn btn-secondary" disabled={busy} onClick={()=>void run(refresh)}>Refresh rendering status</button>{derivatives.filter(d=>d.status==="PENDING"||d.status==="FAILED").map(d=><p role="status" key={d.derivativeId}>{d.status==="PENDING"?"Redacted copy queued or rendering. Original is withheld.":"Rendering failed. Adjust masks and submit a new copy; no original is shared."}</p>)}
      {derivatives.filter(d=>d.status==="READY").map((d,i)=><button className="btn btn-secondary" disabled={busy} key={d.derivativeId} onClick={()=>void run(async()=>{setReviewing(d);const url=URL.createObjectURL(await api.featureDownload(proof.proofId,`disclosure/redactions/${d.derivativeId}/media`));owned.current.push(url);setReviewUrl(url);})}>Review rendered copy {i+1}</button>)}
      {reviewUrl&&reviewing&&<div className="case-preview"><h3>Review the actual redacted copy</h3>{reviewing.contentType?.startsWith("image/")?<img src={reviewUrl} alt="Server-rendered redacted copy"/>:<video src={reviewUrl} controls playsInline aria-label="Server-rendered redacted copy"/>}<p>Play the full copy and inspect all frames before approval. If any private region is still visible, make a new mask and render again.</p><button className="btn" disabled={busy||!reviewing.sha256} onClick={()=>void run(async()=>{await api.featureRequest(proof.proofId,`disclosure/redactions/${reviewing.derivativeId}/approve`,"POST",{sha256:reviewing.sha256});await refresh();setReviewing(null);setReviewUrl(null);changed();setNotice("Private copy saved. Shared Proof links still include the original recordings.");})}>Save reviewed copy</button></div>}
    </details></section>;
}
