import {useEffect,useRef,useState} from "react";
import QRCode from "qrcode";
import type {PackProofApi} from "../api/client";
import type {FulfillmentQueueItem} from "../api/types";
type Command={sequence:number;type:"SELECT_ORDER"|"START"|"FINISH"|"NEXT";proofId:string|null;idempotencyKey:string};
type Station={id:string;state:string;paired:boolean;proofId:string|null;captureSessionId:string|null;lastSequence:number;acknowledgedSequence:number;expiresAt:string;commands:Command[];capture?:{state:string}|null};
type Device={id:string;role:"CONTROLLER"|"CAMERA";token:string;pairingUrl?:string;pendingAck?:{sequence:number;captureSessionId?:string};pendingCommand?:Command};
export function RelayStationPanel({api,userId,queue,selectProof,start,finish,localProofId,localPhase,onRole}:{api:PackProofApi;userId:string;queue:FulfillmentQueueItem[];selectProof:(id:string)=>Promise<void>;start:(onSessionIssued?:(id:string)=>void)=>Promise<string|undefined>;finish:()=>Promise<void>;localProofId?:string;localPhase:string;onRole:(role:"CAMERA"|"CONTROLLER"|null)=>void}){
  const storageKey=`packproof.relay.${api.recoveryScope}.${userId}`;
  const [device,setDevice]=useState<Device|null>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||"null");}catch{return null;}}),[station,setStation]=useState<Station|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[armed,setArmed]=useState(false),[scan,setScan]=useState(""),[qr,setQr]=useState<string|null>(null);
  const [pairing,setPairing]=useState(()=>new URLSearchParams(location.hash.replace(/^#/,"")));
  const ownsCamera=useRef(false);
  useEffect(()=>{if(device?.role!=="CAMERA")return;let release:()=>void=()=>undefined;let active=true;if(!navigator.locks){setError("This browser cannot safely coordinate paired camera tabs. Use a browser with Web Locks support.");return;}void navigator.locks.request(`packproof-camera-${userId}-${device.id}`,{ifAvailable:true},async lock=>{if(!lock){if(active)setError("This paired camera is already active in another tab. Close that tab before resuming here.");return;}ownsCamera.current=true;await new Promise<void>(resolve=>{release=resolve;if(!active)resolve();});ownsCamera.current=false;});return()=>{active=false;release();};},[device?.id,device?.role,userId]);
  const deviceRef=useRef(device),callbacks=useRef({selectProof,start,finish}),processing=useRef(false),local=useRef({localProofId,localPhase,armed});deviceRef.current=device;callbacks.current={selectProof,start,finish};local.current={localProofId,localPhase,armed};
  function save(value:Device|null){deviceRef.current=value;setDevice(value);if(value)localStorage.setItem(storageKey,JSON.stringify(value));else localStorage.removeItem(storageKey);}
  useEffect(()=>{onRole(device?.role||null);},[device?.role,onRole]);
  useEffect(()=>{if(!device?.pairingUrl){setQr(null);return;}let active=true;void QRCode.toDataURL(device.pairingUrl,{width:224,margin:3}).then(url=>{if(active)setQr(url);});return()=>{active=false;};},[device?.pairingUrl]);
  useEffect(()=>{if(!device)return;let active=true;async function poll(){if(processing.current)return;processing.current=true;try{
    const d=deviceRef.current;if(!d)return;const next=await api.relayRequest<Station>(`/${d.id}`,"GET",undefined,d.token);if(!active)return;setStation(next);
    if(d.role!=="CAMERA"||!ownsCamera.current)return;
    if(d.pendingAck){await api.relayRequest(`/${d.id}/ack`,"POST",d.pendingAck,d.token);save({...d,pendingAck:undefined});return;}
    const command=next.commands?.[0];if(!command)return;
    if(command.type==="SELECT_ORDER"||command.type==="NEXT"){
      if(!command.proofId)throw new Error("Order is missing from this command.");await callbacks.current.selectProof(command.proofId);
    }else if(command.type==="START"){
      if(!local.current.armed){setError("Controller requested recording. Enable this camera below to continue.");return;}
      if(local.current.localProofId!==next.proofId)throw new Error("Camera and controller orders differ. Reopen the selected order before recording.");
      const id=await callbacks.current.start(id=>save({...d,pendingAck:{sequence:command.sequence,captureSessionId:id}}));if(!id)throw new Error("Recording did not start. Check camera access on this device.");
      const updated={...d,pendingAck:{sequence:command.sequence,captureSessionId:id}};save(updated);await api.relayRequest(`/${d.id}/ack`,"POST",updated.pendingAck,d.token);save({...updated,pendingAck:undefined});setError(null);return;
    }else{
      if(local.current.localProofId&&local.current.localProofId!==next.proofId)throw new Error("Finish command does not match the recording on this camera.");
      if(local.current.localPhase==="RECORDING")await callbacks.current.finish();
      const confirmed=await api.relayRequest<Station>(`/${d.id}`,"GET",undefined,d.token);
      if(!["RECORDED","UPLOADING","COMMITTED"].includes(confirmed.capture?.state||""))throw new Error("Finish saving on the camera. The controller will keep this order selected.");
    }
    const updated={...d,pendingAck:{sequence:command.sequence}};save(updated);await api.relayRequest(`/${d.id}/ack`,"POST",updated.pendingAck,d.token);save({...updated,pendingAck:undefined});setError(null);
  }catch(e){if(active)setError(e instanceof Error?e.message:"Station connection unavailable. The current order stays selected.");}finally{processing.current=false;}}
  void poll();const timer=setInterval(()=>void poll(),1500);return()=>{active=false;clearInterval(timer);};},[api,device?.id,device?.role]);
  async function action(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:"Station action failed.");}finally{setBusy(false);}}
  async function send(type:Command["type"],proofId?:string){const d=deviceRef.current;if(!d||!station)return;const command=d.pendingCommand||{type,sequence:station.lastSequence+1,idempotencyKey:crypto.randomUUID(),proofId:proofId||station.proofId};save({...d,pendingCommand:command});await api.relayRequest(`/${d.id}/commands`,"POST",command,d.token);save({...d,pendingCommand:undefined});setStation(await api.relayRequest<Station>(`/${d.id}`,"GET",undefined,d.token));}
  const waiting=station&&station.lastSequence!==station.acknowledgedSequence;
  return <section className="section relay-panel stack"><details open={!!device||!!pairing.get("relay")}><summary><strong>Packing Station Relay</strong> · one controller, one phone camera</summary><p className="note">Both devices must sign in to the same account. Pairing expires in five minutes; station access lasts eight hours. Unfinished recordings stay bound to their original order.</p>{error&&<p role="alert" className="banner banner-error">{error}</p>}
    {!device&&<div className="btn-row"><button className="btn btn-secondary" disabled={busy} onClick={()=>void action(async()=>{const created=await api.relayRequest<Station&{controllerToken:string;pairingToken:string}>("","POST",{});const url=`${location.origin}/station#relay=${encodeURIComponent(created.id)}&pair=${encodeURIComponent(created.pairingToken)}`;save({id:created.id,role:"CONTROLLER",token:created.controllerToken,pairingUrl:url});setStation(created);})}>Use this device as controller</button>{pairing.get("relay")&&<button className="btn" disabled={busy} onClick={()=>void action(async()=>{const id=pairing.get("relay")!;const result=await api.relayRequest<Station&{cameraToken:string}>(`/${id}/pair`,"POST",{pairingToken:pairing.get("pair")});save({id,role:"CAMERA",token:result.cameraToken});setStation(result);setPairing(new URLSearchParams());history.replaceState(history.state,"",location.pathname+location.search);})}>Pair this phone camera</button>}</div>}
    {device&&<><p role="status"><strong>{device.role==="CAMERA"?"Phone camera":"Controller"}</strong> · {station?.state.toLowerCase().replaceAll("_"," ")||"Reconnecting…"}{waiting?" · Waiting for camera acknowledgment":""}</p>{device.role==="CONTROLLER"&&!station?.paired&&<>{qr&&<img width={224} height={224} src={qr} alt="Pair the signed-in phone camera"/>}<p>Open this link on the signed-in phone, then choose Pair this phone camera.</p><a className="secret-value" href={device.pairingUrl}>{device.pairingUrl}</a></>}
      {device.role==="CAMERA"&&<><label className="row"><input type="checkbox" checked={armed} disabled={localPhase==="RECORDING"} onChange={e=>{if(!e.target.checked){setArmed(false);return;}void action(async()=>{const access=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});access.getTracks().forEach(t=>t.stop());setArmed(true);});}}/>Enable controller Start and Finish on this camera</label><p className="note">Keep this page open and the phone awake. Camera permissions and recording errors are shown on this device.</p></>}
      {device.role==="CONTROLLER"&&station?.paired&&<><label className="field"><span>Order for both devices</span><select value={station.proofId||""} disabled={busy||!!waiting||station.state==="RECORDING"||station.capture?.state==="RECORDED"||station.capture?.state==="UPLOADING"} onChange={e=>{if(e.target.value)void action(()=>send(station.proofId?"NEXT":"SELECT_ORDER",e.target.value));}}><option value="">Select an order</option>{queue.filter(q=>q.workflowState!=="COMPLETED"&&q.workflowState!=="REMOVED_FROM_FULFILLMENT").map(q=><option key={q.proofId} value={q.proofId}>{q.externalReference||q.externalOrderId} · {q.itemSummary}</option>)}</select></label><form className="row" onSubmit={e=>{e.preventDefault();const value=scan.trim();void action(async()=>{if(value==="PP:START")await send("START");else if(value==="PP:FINISH")await send("FINISH");else {const found=await api.resolvePackingStation(value);const proof=await api.createOrGetProof(found.transactionId);await send(station.proofId?"NEXT":"SELECT_ORDER",proof.proofId);}setScan("");});}}><label className="field"><span>Scan order reference or station command</span><input value={scan} onChange={e=>setScan(e.target.value)} autoComplete="off" disabled={busy||!!waiting}/></label><button className="btn btn-secondary" disabled={busy||!!waiting||!scan.trim()}>Use scan</button></form><p className="note">Command labels: PP:START and PP:FINISH. An order reference selects that order; it never starts recording.</p><div className="btn-row"><button className="btn" disabled={busy||!!waiting||station.state!=="SELECTED"} onClick={()=>void action(()=>send("START"))}>Start phone recording</button><button className="btn btn-danger" disabled={busy||!!waiting||station.state!=="RECORDING"} onClick={()=>void action(()=>send("FINISH"))}>Finish and save current order</button>{device.pendingCommand&&<button className="btn btn-secondary" disabled={busy} onClick={()=>void action(()=>send(device.pendingCommand!.type))}>Retry the same command</button>}</div><p className="note">{station.capture?.state==="COMMITTED"?"Recording saved. You can select the next order.":"The next order remains locked until this recording is committed."}</p></>}
      <div className="btn-row"><button className="btn btn-secondary" disabled={busy} onClick={()=>void action(async()=>{await api.relayRequest(`/${device.id}/renew`,"POST",{},device.token);})}>Renew station session</button><button className="btn btn-secondary" disabled={busy||localPhase==="RECORDING"||station?.state==="RECORDING"||station?.state==="SAVING"||!!waiting} onClick={()=>{save(null);setStation(null);setArmed(false);}}>Leave paired mode</button></div>
    </>}
  </details></section>;
}
