import {useEffect,useRef,useState} from "react";
import type {PackProofApi} from "../api/client";
import type {PublicProofView} from "../api/types";
export function ReturnAngleGuide({api,proofId,onGuide}:{api:PackProofApi;proofId:string;onGuide:(url:string|null)=>void}){
 const [thumbs,setThumbs]=useState<Array<{derivativeId:string;status:string;transform:{anchorId:string}}>>([]),[link,setLink]=useState(""),[view,setView]=useState<PublicProofView|null>(null),[token,setToken]=useState(""),[source,setSource]=useState<string|null>(null),[kind,setKind]=useState(""),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const video=useRef<HTMLVideoElement>(null),image=useRef<HTMLImageElement>(null),owned=useRef<string[]>([]);
 useEffect(()=>()=>{owned.current.forEach(url=>URL.revokeObjectURL(url));onGuide(null);},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:"That reference view is unavailable.");}finally{setBusy(false);}}
 function own(blob:Blob){const url=URL.createObjectURL(blob);owned.current.push(url);return url;}
 function frame(){const src=kind.startsWith("video/")?video.current:image.current;if(!src)return;const w=src instanceof HTMLVideoElement?src.videoWidth:src.naturalWidth,h=src instanceof HTMLVideoElement?src.videoHeight:src.naturalHeight;if(!w||!h)return;const canvas=document.createElement("canvas");canvas.width=Math.min(640,w);canvas.height=Math.round(h*canvas.width/w);canvas.getContext("2d")!.drawImage(src,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob)onGuide(own(blob));},"image/jpeg",.8);}
 return <details><summary>Match an authorized earlier view</summary><p className="note">Use an earlier view as a translucent positioning guide. It never becomes part of the recording, authenticates an item, or establishes a difference.</p>{error&&<p role="alert">{error}</p>}<button className="btn btn-secondary" disabled={busy} onClick={()=>void run(async()=>{const r=await api.featureRequest<{derivatives:typeof thumbs}>(proofId,"disclosure/thumbnails");setThumbs(r.derivatives.filter(t=>t.status==="READY"));if(!r.derivatives.some(t=>t.status==="READY"))setError("No prepared source frames are available. Open Proof Replay to prepare authorized chapter previews, or use a reviewed receipt link below.");})}>Choose my authorized source frames</button>{thumbs.map((t,i)=><button className="btn btn-secondary" key={t.derivativeId} disabled={busy} onClick={()=>void run(async()=>onGuide(own(await api.featureDownload(proofId,`disclosure/thumbnails/${t.derivativeId}/media`))))}>Use source frame {i+1}</button>)}<form className="stack" onSubmit={e=>{e.preventDefault();void run(async()=>{const u=new URL(link);if(u.origin!==location.origin||!u.pathname.startsWith("/p/"))throw new Error("Use a reviewed PackProof receipt link from this site.");const t=decodeURIComponent(u.pathname.slice(3));const loaded=await api.featureRequest<PublicProofView>(proofId,"signature/outbound-view","POST",{token:t});setToken(t);setView(loaded);onGuide(null);});}}><label className="field"><span>Or use a reviewed receipt link shared with you</span><input type="url" value={link} onChange={e=>setLink(e.target.value)} maxLength={1000}/></label><button className="btn btn-secondary" disabled={busy||!link}>Check shared reference</button></form>{view?.evidence?.filter(m=>m.representation==="DERIVATIVE").map((m,i)=><button className="btn btn-secondary" disabled={busy} key={m.evidenceId} onClick={()=>void run(async()=>{setSource(own(await api.getPublicEvidence(token,m.evidenceId)));setKind(m.contentType||"");})}>Open reviewed source {i+1}</button>)}{source&&<div>{kind.startsWith("video/")?<video ref={video} src={source} controls playsInline aria-label="Reviewed source for positioning"/>:<img ref={image} src={source} alt="Reviewed positioning source"/>}<button className="btn btn-secondary" onClick={frame}>Use this displayed frame as a guide</button></div>}<button className="btn btn-secondary" onClick={()=>onGuide(null)}>Remove guide</button><p className="note">The same access rules apply to every reference. No private original is loaded through a shared link. Lighting, angle and missing coverage may make views not comparable.</p></details>;
}
