import {useEffect,useState} from 'react';
import type {PackProofApi} from '../api/client';
import {randomId} from '../random-id';
import {flushStudyTimings,rememberStudyStatus,type StudyStatus} from '../analytics/study-capture';
export function StudyConsentPanel({api,userId}:{api:PackProofApi;userId:string}){
  const [status,setStatus]=useState<StudyStatus|null>(null),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  useEffect(()=>{let active=true;setStatus(null);setChecked(false);void api.studyRequest<StudyStatus>('/consent').then(value=>{if(active){setStatus(value);rememberStudyStatus(api,userId,value);}}).catch(()=>{});return()=>{active=false;};},[api,userId]);
  if(!status?.enabled||!status.datasetRef)return null;
  const save=async(decision:'grant'|'withdraw')=>{setBusy(true);setError(null);try{const value=await api.studyRequest<StudyStatus>('/consent','POST',{datasetRef:status.datasetRef,operationNonce:randomId(),decision,statementVersion:status.statementVersion});setStatus({...value,enabled:true});rememberStudyStatus(api,userId,{...value,enabled:true});setChecked(false);if(decision==='withdraw')await flushStudyTimings(api,userId);}catch{setError('The study preference could not be saved. Please retry.');}finally{setBusy(false);}};
  return <section className="card stack" aria-label="Optional capture timing study"><h2>Optional capture timing study</h2><p>{status.statement}</p><p className="note">The study records capture steps, label reading and mismatches, confirmation, recovery, and successful sharing, plus the software source build when known. It does not collect order details or label values.</p>{status.granted?<><p>You are contributing timings for this study from this account. Recording content is excluded.</p><button className="btn btn-secondary" disabled={busy} onClick={()=>void save('withdraw')}>Stop future study collection</button></>:<><label><input type="checkbox" checked={checked} onChange={event=>setChecked(event.target.checked)}/> I agree to the study statement above.</label><button className="btn" disabled={!checked||busy} onClick={()=>void save('grant')}>Join this timing study</button></>}{error&&<p role="alert">{error}</p>}</section>;
}
